// The MIT License (MIT)
//
// Copyright (c) 2018 Mateusz Pusz
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#pragma once

// This file is GENERATED by `scripts/codata_constants.py` from the NIST "allascii"
// tables checked in under `scripts/codata/`. Do not edit it manually; rerun the script.
//
// The NIST "adopted values": conventional constants fixed by CGPM/CIPM resolutions rather
// than measured, identical in every CODATA adjustment (the generator verifies that). They
// live directly in `mp_units::codata`, outside the adjustment namespaces, so entities
// defined through them (e.g. `yard_pound`'s `pound_force` through the standard gravity)
// keep a single stable type that does not change when the inline adjustment namespace
// moves to a newer release.

#include <mp-units/bits/module_macros.h>
#include <mp-units/systems/si/units.h>

#ifndef MP_UNITS_IN_MODULE_INTERFACE
#include <mp-units/framework/unit.h>
#endif

MP_UNITS_EXPORT
namespace mp_units::codata {

// clang-format off

// standard acceleration of gravity: 9.806 65 m s^-2 (exact)
inline constexpr struct standard_gravity final :
    named_constant<symbol_text{u8"g₀", "g_0"}, mag_ratio<980'665, 100'000> * si::metre / square(si::second)> {} standard_gravity;

// standard atmosphere: 101 325 Pa (exact)
inline constexpr struct standard_atmosphere final :
    named_constant<"atm", mag<101'325> * si::pascal> {} standard_atmosphere;

// standard-state pressure: 100 000 Pa (exact)
inline constexpr struct standard_state_pressure final :
    named_constant<"standard_state_pressure", mag<100'000> * si::pascal> {} standard_state_pressure;

// conventional value of Josephson constant: 483 597.9 e9 Hz V^-1 (exact)
inline constexpr struct conventional_value_of_josephson_constant final :
    named_constant<"K_J-90", mag_ratio<4'835'979, 10> * mag_power<10, 9> * si::hertz / si::volt> {} conventional_value_of_josephson_constant;

// conventional value of von Klitzing constant: 25 812.807 ohm (exact)
inline constexpr struct conventional_value_of_von_klitzing_constant final :
    named_constant<"R_K-90", mag_ratio<25'812'807, 1'000> * si::ohm> {} conventional_value_of_von_klitzing_constant;
// clang-format on

}  // namespace mp_units::codata
