// The MIT License (MIT)
//
// Copyright (c) 2018 Mateusz Pusz
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#pragma once

// This file is GENERATED by `scripts/codata_constants.py` from the NIST "allascii"
// tables checked in under `scripts/codata/`. Do not edit it manually; rerun the script.
//
// The CODATA 2014 adjustment: the last one before the 2019 SI redefinition, so h, e,
// k, and N_A are measured here and μ₀ is exact.
// See <mp-units/systems/codata.h> for the full description of the system.

#include <mp-units/bits/module_macros.h>
#include <mp-units/systems/codata/codata2014_essential.h>
#include <mp-units/systems/si/constants.h>
#include <mp-units/systems/si/units.h>

#ifndef MP_UNITS_IN_MODULE_INTERFACE
#include <mp-units/framework/unit.h>
#endif

MP_UNITS_EXPORT
namespace mp_units::codata {

namespace codata2014 {

// clang-format off

// {220} lattice spacing of silicon: 192.015 5714 e-12 m, u = 0.000 0032 e-12 m
inline constexpr struct lattice_spacing_of_silicon_220 final :
    named_constant<"lattice_spacing_of_silicon_220", mag_ratio<1'920'155'714, 10'000'000> * mag_power<10, -12> * si::metre, standard_uncertainty{mag_ratio<32, 10> * mag_power<10, -18> * si::metre}> {} lattice_spacing_of_silicon_220;

// alpha particle-electron mass ratio: 7294.299 541 36, u = 0.000 000 24
inline constexpr struct alpha_particle_electron_mass_ratio final :
    named_constant<"alpha_particle_electron_mass_ratio", mag_ratio<729'429'954'136, 100'000'000> * one, standard_uncertainty{mag_ratio<24, 10> * mag_power<10, -7> * one}> {} alpha_particle_electron_mass_ratio;

// alpha particle mass: 6.644 657 230 e-27 kg, u = 0.000 000 082 e-27 kg
inline constexpr struct alpha_particle_mass final :
    named_constant<symbol_text{u8"m_α", "m_alpha"}, mag_ratio<6'644'657'230, 1'000'000'000> * mag_power<10, -27> * si::kilogram, standard_uncertainty{mag_ratio<82, 10> * mag_power<10, -35> * si::kilogram}> {} alpha_particle_mass;

// alpha particle molar mass: 4.001 506 179 127 e-3 kg mol^-1, u = 0.000 000 000 063 e-3 kg mol^-1
inline constexpr struct alpha_particle_molar_mass final :
    named_constant<"alpha_particle_molar_mass", mag_ratio<4'001'506'179'127, 1'000'000'000'000> * mag_power<10, -3> * si::kilogram / si::mole, standard_uncertainty{mag_ratio<63, 10> * mag_power<10, -14> * si::kilogram / si::mole}> {} alpha_particle_molar_mass;

// alpha particle-proton mass ratio: 3.972 599 689 07, u = 0.000 000 000 36
inline constexpr struct alpha_particle_proton_mass_ratio final :
    named_constant<"alpha_particle_proton_mass_ratio", mag_ratio<397'259'968'907, 100'000'000'000> * one, standard_uncertainty{mag_ratio<36, 10> * mag_power<10, -10> * one}> {} alpha_particle_proton_mass_ratio;

// Angstrom star: 1.000 014 95 e-10 m, u = 0.000 000 90 e-10 m
inline constexpr struct angstrom_star final :
    named_constant<"angstrom_star", mag_ratio<100'001'495, 100'000'000> * mag_power<10, -10> * si::metre, standard_uncertainty{mag_ratio<90, 10> * mag_power<10, -17> * si::metre}> {} angstrom_star;

// atomic unit of 1st hyperpolarizability: 3.206 361 329 e-53 C^3 m^3 J^-2, u = 0.000 000 020 e-53 C^3 m^3 J^-2
inline constexpr struct atomic_unit_of_1st_hyperpolarizability final :
    named_constant<"atomic_unit_of_1st_hyperpolarizability", mag_ratio<3'206'361'329, 1'000'000'000> * mag_power<10, -53> * cubic(si::coulomb) * cubic(si::metre) / square(si::joule), standard_uncertainty{mag_ratio<20, 10> * mag_power<10, -61> * cubic(si::coulomb) * cubic(si::metre) / square(si::joule)}> {} atomic_unit_of_1st_hyperpolarizability;

// atomic unit of 2nd hyperpolarizability: 6.235 380 085 e-65 C^4 m^4 J^-3, u = 0.000 000 077 e-65 C^4 m^4 J^-3
inline constexpr struct atomic_unit_of_2nd_hyperpolarizability final :
    named_constant<"atomic_unit_of_2nd_hyperpolarizability", mag_ratio<6'235'380'085, 1'000'000'000> * mag_power<10, -65> * pow<4>(si::coulomb) * pow<4>(si::metre) / cubic(si::joule), standard_uncertainty{mag_ratio<77, 10> * mag_power<10, -73> * pow<4>(si::coulomb) * pow<4>(si::metre) / cubic(si::joule)}> {} atomic_unit_of_2nd_hyperpolarizability;

// atomic unit of charge density: 1.081 202 3770 e12 C m^-3, u = 0.000 000 0067 e12 C m^-3
inline constexpr struct atomic_unit_of_charge_density final :
    named_constant<"atomic_unit_of_charge_density", mag_ratio<10'812'023'770, 10'000'000'000> * mag_power<10, 12> * si::coulomb / cubic(si::metre), standard_uncertainty{mag_ratio<67, 10> * mag_power<10, 3> * si::coulomb / cubic(si::metre)}> {} atomic_unit_of_charge_density;

// atomic unit of current: 6.623 618 183 e-3 A, u = 0.000 000 041 e-3 A
inline constexpr struct atomic_unit_of_current final :
    named_constant<"atomic_unit_of_current", mag_ratio<6'623'618'183, 1'000'000'000> * mag_power<10, -3> * si::ampere, standard_uncertainty{mag_ratio<41, 10> * mag_power<10, -11> * si::ampere}> {} atomic_unit_of_current;

// atomic unit of electric dipole mom.: 8.478 353 552 e-30 C m, u = 0.000 000 052 e-30 C m
inline constexpr struct atomic_unit_of_electric_dipole_moment final :
    named_constant<"atomic_unit_of_electric_dipole_moment", mag_ratio<8'478'353'552, 1'000'000'000> * mag_power<10, -30> * si::coulomb * si::metre, standard_uncertainty{mag_ratio<52, 10> * mag_power<10, -38> * si::coulomb * si::metre}> {} atomic_unit_of_electric_dipole_moment;

// atomic unit of electric field: 5.142 206 707 e11 V m^-1, u = 0.000 000 032 e11 V m^-1
inline constexpr struct atomic_unit_of_electric_field final :
    named_constant<"atomic_unit_of_electric_field", mag_ratio<5'142'206'707, 1'000'000'000> * mag_power<10, 11> * si::volt / si::metre, standard_uncertainty{mag_ratio<32, 10> * mag_power<10, 3> * si::volt / si::metre}> {} atomic_unit_of_electric_field;

// atomic unit of electric field gradient: 9.717 362 356 e21 V m^-2, u = 0.000 000 060 e21 V m^-2
inline constexpr struct atomic_unit_of_electric_field_gradient final :
    named_constant<"atomic_unit_of_electric_field_gradient", mag_ratio<9'717'362'356, 1'000'000'000> * mag_power<10, 21> * si::volt / square(si::metre), standard_uncertainty{mag_ratio<60, 10> * mag_power<10, 13> * si::volt / square(si::metre)}> {} atomic_unit_of_electric_field_gradient;

// atomic unit of electric polarizability: 1.648 777 2731 e-41 C^2 m^2 J^-1, u = 0.000 000 0011 e-41 C^2 m^2 J^-1
inline constexpr struct atomic_unit_of_electric_polarizability final :
    named_constant<"atomic_unit_of_electric_polarizability", mag_ratio<16'487'772'731, 10'000'000'000> * mag_power<10, -41> * square(si::coulomb) * square(si::metre) / si::joule, standard_uncertainty{mag_ratio<11, 10> * mag_power<10, -50> * square(si::coulomb) * square(si::metre) / si::joule}> {} atomic_unit_of_electric_polarizability;

// atomic unit of electric potential: 27.211 386 02 V, u = 0.000 000 17 V
inline constexpr struct atomic_unit_of_electric_potential final :
    named_constant<"atomic_unit_of_electric_potential", mag_ratio<2'721'138'602, 100'000'000> * si::volt, standard_uncertainty{mag_ratio<17, 10> * mag_power<10, -7> * si::volt}> {} atomic_unit_of_electric_potential;

// atomic unit of electric quadrupole mom.: 4.486 551 484 e-40 C m^2, u = 0.000 000 028 e-40 C m^2
inline constexpr struct atomic_unit_of_electric_quadrupole_moment final :
    named_constant<"atomic_unit_of_electric_quadrupole_moment", mag_ratio<4'486'551'484, 1'000'000'000> * mag_power<10, -40> * si::coulomb * square(si::metre), standard_uncertainty{mag_ratio<28, 10> * mag_power<10, -48> * si::coulomb * square(si::metre)}> {} atomic_unit_of_electric_quadrupole_moment;

// atomic unit of force: 8.238 723 36 e-8 N, u = 0.000 000 10 e-8 N
inline constexpr struct atomic_unit_of_force final :
    named_constant<"atomic_unit_of_force", mag_ratio<823'872'336, 100'000'000> * mag_power<10, -8> * si::newton, standard_uncertainty{mag_ratio<10, 10> * mag_power<10, -15> * si::newton}> {} atomic_unit_of_force;

// atomic unit of mag. dipole mom.: 1.854 801 999 e-23 J T^-1, u = 0.000 000 011 e-23 J T^-1
inline constexpr struct atomic_unit_of_magnetic_dipole_moment final :
    named_constant<"atomic_unit_of_magnetic_dipole_moment", mag_ratio<1'854'801'999, 1'000'000'000> * mag_power<10, -23> * si::joule / si::tesla, standard_uncertainty{mag_ratio<11, 10> * mag_power<10, -31> * si::joule / si::tesla}> {} atomic_unit_of_magnetic_dipole_moment;

// atomic unit of mag. flux density: 2.350 517 550 e5 T, u = 0.000 000 014 e5 T
inline constexpr struct atomic_unit_of_magnetic_flux_density final :
    named_constant<"atomic_unit_of_magnetic_flux_density", mag_ratio<2'350'517'550, 1'000'000'000> * mag_power<10, 5> * si::tesla, standard_uncertainty{mag_ratio<14, 10> * mag_power<10, -3> * si::tesla}> {} atomic_unit_of_magnetic_flux_density;

// atomic unit of magnetizability: 7.891 036 5886 e-29 J T^-2, u = 0.000 000 0090 e-29 J T^-2
inline constexpr struct atomic_unit_of_magnetizability final :
    named_constant<"atomic_unit_of_magnetizability", mag_ratio<78'910'365'886, 10'000'000'000> * mag_power<10, -29> * si::joule / square(si::tesla), standard_uncertainty{mag_ratio<90, 10> * mag_power<10, -38> * si::joule / square(si::tesla)}> {} atomic_unit_of_magnetizability;

// atomic unit of mom.um: 1.992 851 882 e-24 kg m s^-1, u = 0.000 000 024 e-24 kg m s^-1
inline constexpr struct atomic_unit_of_momentum final :
    named_constant<"atomic_unit_of_momentum", mag_ratio<1'992'851'882, 1'000'000'000> * mag_power<10, -24> * si::kilogram * si::metre / si::second, standard_uncertainty{mag_ratio<24, 10> * mag_power<10, -32> * si::kilogram * si::metre / si::second}> {} atomic_unit_of_momentum;

// atomic unit of time: 2.418 884 326 509 e-17 s, u = 0.000 000 000 014 e-17 s
inline constexpr struct atomic_unit_of_time final :
    named_constant<"atomic_unit_of_time", mag_ratio<2'418'884'326'509, 1'000'000'000'000> * mag_power<10, -17> * si::second, standard_uncertainty{mag_ratio<14, 10> * mag_power<10, -28> * si::second}> {} atomic_unit_of_time;

// atomic unit of velocity: 2.187 691 262 77 e6 m s^-1, u = 0.000 000 000 50 e6 m s^-1
inline constexpr struct atomic_unit_of_velocity final :
    named_constant<"atomic_unit_of_velocity", mag_ratio<218'769'126'277, 100'000'000'000> * mag_power<10, 6> * si::metre / si::second, standard_uncertainty{mag_ratio<50, 10> * mag_power<10, -4> * si::metre / si::second}> {} atomic_unit_of_velocity;

// classical electron radius: 2.817 940 3227 e-15 m, u = 0.000 000 0019 e-15 m
inline constexpr struct classical_electron_radius final :
    named_constant<"r_e", mag_ratio<28'179'403'227, 10'000'000'000> * mag_power<10, -15> * si::metre, standard_uncertainty{mag_ratio<19, 10> * mag_power<10, -24> * si::metre}> {} classical_electron_radius;

// Cu x unit: 1.002 076 97 e-13 m, u = 0.000 000 28 e-13 m
inline constexpr struct copper_x_unit final :
    named_constant<"copper_x_unit", mag_ratio<100'207'697, 100'000'000> * mag_power<10, -13> * si::metre, standard_uncertainty{mag_ratio<28, 10> * mag_power<10, -20> * si::metre}> {} copper_x_unit;

// deuteron-electron mag. mom. ratio: -4.664 345 535 e-4, u = 0.000 000 026 e-4
inline constexpr struct deuteron_electron_magnetic_moment_ratio final :
    named_constant<"deuteron_electron_magnetic_moment_ratio", -mag_ratio<4'664'345'535, 1'000'000'000> * mag_power<10, -4> * one, standard_uncertainty{mag_ratio<26, 10> * mag_power<10, -12> * one}> {} deuteron_electron_magnetic_moment_ratio;

// deuteron-electron mass ratio: 3670.482 967 85, u = 0.000 000 13
inline constexpr struct deuteron_electron_mass_ratio final :
    named_constant<"deuteron_electron_mass_ratio", mag_ratio<367'048'296'785, 100'000'000> * one, standard_uncertainty{mag_ratio<13, 10> * mag_power<10, -7> * one}> {} deuteron_electron_mass_ratio;

// deuteron g factor: 0.857 438 2311, u = 0.000 000 0048
inline constexpr struct deuteron_g_factor final :
    named_constant<"g_d", mag_ratio<8'574'382'311, 10'000'000'000> * one, standard_uncertainty{mag_ratio<48, 10> * mag_power<10, -9> * one}> {} deuteron_g_factor;

// deuteron mag. mom.: 0.433 073 5040 e-26 J T^-1, u = 0.000 000 0036 e-26 J T^-1
inline constexpr struct deuteron_magnetic_moment final :
    named_constant<symbol_text{u8"μ_d", "mu_d"}, mag_ratio<4'330'735'040, 10'000'000'000> * mag_power<10, -26> * si::joule / si::tesla, standard_uncertainty{mag_ratio<36, 10> * mag_power<10, -35> * si::joule / si::tesla}> {} deuteron_magnetic_moment;

// deuteron mag. mom. to Bohr magneton ratio: 0.466 975 4554 e-3, u = 0.000 000 0026 e-3
inline constexpr struct deuteron_magnetic_moment_to_bohr_magneton_ratio final :
    named_constant<"deuteron_magnetic_moment_to_bohr_magneton_ratio", mag_ratio<4'669'754'554, 10'000'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<26, 10> * mag_power<10, -12> * one}> {} deuteron_magnetic_moment_to_bohr_magneton_ratio;

// deuteron mag. mom. to nuclear magneton ratio: 0.857 438 2311, u = 0.000 000 0048
inline constexpr struct deuteron_magnetic_moment_to_nuclear_magneton_ratio final :
    named_constant<"deuteron_magnetic_moment_to_nuclear_magneton_ratio", mag_ratio<8'574'382'311, 10'000'000'000> * one, standard_uncertainty{mag_ratio<48, 10> * mag_power<10, -9> * one}> {} deuteron_magnetic_moment_to_nuclear_magneton_ratio;

// deuteron mass: 3.343 583 719 e-27 kg, u = 0.000 000 041 e-27 kg
inline constexpr struct deuteron_mass final :
    named_constant<"m_d", mag_ratio<3'343'583'719, 1'000'000'000> * mag_power<10, -27> * si::kilogram, standard_uncertainty{mag_ratio<41, 10> * mag_power<10, -35> * si::kilogram}> {} deuteron_mass;

// deuteron molar mass: 2.013 553 212 745 e-3 kg mol^-1, u = 0.000 000 000 040 e-3 kg mol^-1
inline constexpr struct deuteron_molar_mass final :
    named_constant<"deuteron_molar_mass", mag_ratio<2'013'553'212'745, 1'000'000'000'000> * mag_power<10, -3> * si::kilogram / si::mole, standard_uncertainty{mag_ratio<40, 10> * mag_power<10, -14> * si::kilogram / si::mole}> {} deuteron_molar_mass;

// deuteron-neutron mag. mom. ratio: -0.448 206 52, u = 0.000 000 11
inline constexpr struct deuteron_neutron_magnetic_moment_ratio final :
    named_constant<"deuteron_neutron_magnetic_moment_ratio", -mag_ratio<44'820'652, 100'000'000> * one, standard_uncertainty{mag_ratio<11, 10> * mag_power<10, -7> * one}> {} deuteron_neutron_magnetic_moment_ratio;

// deuteron-proton mag. mom. ratio: 0.307 012 2077, u = 0.000 000 0015
inline constexpr struct deuteron_proton_magnetic_moment_ratio final :
    named_constant<"deuteron_proton_magnetic_moment_ratio", mag_ratio<3'070'122'077, 10'000'000'000> * one, standard_uncertainty{mag_ratio<15, 10> * mag_power<10, -9> * one}> {} deuteron_proton_magnetic_moment_ratio;

// deuteron-proton mass ratio: 1.999 007 500 87, u = 0.000 000 000 19
inline constexpr struct deuteron_proton_mass_ratio final :
    named_constant<"deuteron_proton_mass_ratio", mag_ratio<199'900'750'087, 100'000'000'000> * one, standard_uncertainty{mag_ratio<19, 10> * mag_power<10, -10> * one}> {} deuteron_proton_mass_ratio;

// deuteron rms charge radius: 2.1413 e-15 m, u = 0.0025 e-15 m
inline constexpr struct deuteron_rms_charge_radius final :
    named_constant<"r_d", mag_ratio<21'413, 10'000> * mag_power<10, -15> * si::metre, standard_uncertainty{mag_ratio<25, 10> * mag_power<10, -18> * si::metre}> {} deuteron_rms_charge_radius;

// electron charge to mass quotient: -1.758 820 024 e11 C kg^-1, u = 0.000 000 011 e11 C kg^-1
inline constexpr struct electron_charge_to_mass_quotient final :
    named_constant<"electron_charge_to_mass_quotient", -mag_ratio<1'758'820'024, 1'000'000'000> * mag_power<10, 11> * si::coulomb / si::kilogram, standard_uncertainty{mag_ratio<11, 10> * mag_power<10, 3> * si::coulomb / si::kilogram}> {} electron_charge_to_mass_quotient;

// electron-deuteron mag. mom. ratio: -2143.923 499, u = 0.000 012
inline constexpr struct electron_deuteron_magnetic_moment_ratio final :
    named_constant<"electron_deuteron_magnetic_moment_ratio", -mag_ratio<2'143'923'499, 1'000'000> * one, standard_uncertainty{mag_ratio<12, 10> * mag_power<10, -5> * one}> {} electron_deuteron_magnetic_moment_ratio;

// electron-deuteron mass ratio: 2.724 437 107 484 e-4, u = 0.000 000 000 096 e-4
inline constexpr struct electron_deuteron_mass_ratio final :
    named_constant<"electron_deuteron_mass_ratio", mag_ratio<2'724'437'107'484, 1'000'000'000'000> * mag_power<10, -4> * one, standard_uncertainty{mag_ratio<96, 10> * mag_power<10, -15> * one}> {} electron_deuteron_mass_ratio;

// electron g factor: -2.002 319 304 361 82, u = 0.000 000 000 000 52
inline constexpr struct electron_g_factor final :
    named_constant<"g_e", -mag_ratio<200'231'930'436'182, 100'000'000'000'000> * one, standard_uncertainty{mag_ratio<52, 10> * mag_power<10, -13> * one}> {} electron_g_factor;

// electron gyromag. ratio: 1.760 859 644 e11 s^-1 T^-1, u = 0.000 000 011 e11 s^-1 T^-1
inline constexpr struct electron_gyromagnetic_ratio final :
    named_constant<symbol_text{u8"γ_e", "gamma_e"}, mag_ratio<1'760'859'644, 1'000'000'000> * mag_power<10, 11> * one / si::second / si::tesla, standard_uncertainty{mag_ratio<11, 10> * mag_power<10, 3> * one / si::second / si::tesla}> {} electron_gyromagnetic_ratio;

// electron-helion mass ratio: 1.819 543 074 854 e-4, u = 0.000 000 000 088 e-4
inline constexpr struct electron_helion_mass_ratio final :
    named_constant<"electron_helion_mass_ratio", mag_ratio<1'819'543'074'854, 1'000'000'000'000> * mag_power<10, -4> * one, standard_uncertainty{mag_ratio<88, 10> * mag_power<10, -15> * one}> {} electron_helion_mass_ratio;

// electron mag. mom.: -928.476 4620 e-26 J T^-1, u = 0.000 0057 e-26 J T^-1
inline constexpr struct electron_magnetic_moment final :
    named_constant<symbol_text{u8"μ_e", "mu_e"}, -mag_ratio<9'284'764'620, 10'000'000> * mag_power<10, -26> * si::joule / si::tesla, standard_uncertainty{mag_ratio<57, 10> * mag_power<10, -32> * si::joule / si::tesla}> {} electron_magnetic_moment;

// electron mag. mom. anomaly: 1.159 652 180 91 e-3, u = 0.000 000 000 26 e-3
inline constexpr struct electron_magnetic_moment_anomaly final :
    named_constant<"electron_magnetic_moment_anomaly", mag_ratio<115'965'218'091, 100'000'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<26, 10> * mag_power<10, -13> * one}> {} electron_magnetic_moment_anomaly;

// electron mag. mom. to Bohr magneton ratio: -1.001 159 652 180 91, u = 0.000 000 000 000 26
inline constexpr struct electron_magnetic_moment_to_bohr_magneton_ratio final :
    named_constant<"electron_magnetic_moment_to_bohr_magneton_ratio", -mag_ratio<100'115'965'218'091, 100'000'000'000'000> * one, standard_uncertainty{mag_ratio<26, 10> * mag_power<10, -13> * one}> {} electron_magnetic_moment_to_bohr_magneton_ratio;

// electron mag. mom. to nuclear magneton ratio: -1838.281 972 34, u = 0.000 000 17
inline constexpr struct electron_magnetic_moment_to_nuclear_magneton_ratio final :
    named_constant<"electron_magnetic_moment_to_nuclear_magneton_ratio", -mag_ratio<183'828'197'234, 100'000'000> * one, standard_uncertainty{mag_ratio<17, 10> * mag_power<10, -7> * one}> {} electron_magnetic_moment_to_nuclear_magneton_ratio;

// electron molar mass: 5.485 799 090 70 e-7 kg mol^-1, u = 0.000 000 000 16 e-7 kg mol^-1
inline constexpr struct electron_molar_mass final :
    named_constant<"electron_molar_mass", mag_ratio<548'579'909'070, 100'000'000'000> * mag_power<10, -7> * si::kilogram / si::mole, standard_uncertainty{mag_ratio<16, 10> * mag_power<10, -17> * si::kilogram / si::mole}> {} electron_molar_mass;

// electron-muon mag. mom. ratio: 206.766 9880, u = 0.000 0046
inline constexpr struct electron_muon_magnetic_moment_ratio final :
    named_constant<"electron_muon_magnetic_moment_ratio", mag_ratio<2'067'669'880, 10'000'000> * one, standard_uncertainty{mag_ratio<46, 10> * mag_power<10, -6> * one}> {} electron_muon_magnetic_moment_ratio;

// electron-muon mass ratio: 4.836 331 70 e-3, u = 0.000 000 11 e-3
inline constexpr struct electron_muon_mass_ratio final :
    named_constant<"electron_muon_mass_ratio", mag_ratio<483'633'170, 100'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<11, 10> * mag_power<10, -10> * one}> {} electron_muon_mass_ratio;

// electron-neutron mag. mom. ratio: 960.920 50, u = 0.000 23
inline constexpr struct electron_neutron_magnetic_moment_ratio final :
    named_constant<"electron_neutron_magnetic_moment_ratio", mag_ratio<96'092'050, 100'000> * one, standard_uncertainty{mag_ratio<23, 10> * mag_power<10, -4> * one}> {} electron_neutron_magnetic_moment_ratio;

// electron-neutron mass ratio: 5.438 673 4428 e-4, u = 0.000 000 0027 e-4
inline constexpr struct electron_neutron_mass_ratio final :
    named_constant<"electron_neutron_mass_ratio", mag_ratio<54'386'734'428, 10'000'000'000> * mag_power<10, -4> * one, standard_uncertainty{mag_ratio<27, 10> * mag_power<10, -13> * one}> {} electron_neutron_mass_ratio;

// electron-proton mag. mom. ratio: -658.210 6866, u = 0.000 0020
inline constexpr struct electron_proton_magnetic_moment_ratio final :
    named_constant<"electron_proton_magnetic_moment_ratio", -mag_ratio<6'582'106'866, 10'000'000> * one, standard_uncertainty{mag_ratio<20, 10> * mag_power<10, -6> * one}> {} electron_proton_magnetic_moment_ratio;

// electron-proton mass ratio: 5.446 170 213 52 e-4, u = 0.000 000 000 52 e-4
inline constexpr struct electron_proton_mass_ratio final :
    named_constant<"electron_proton_mass_ratio", mag_ratio<544'617'021'352, 100'000'000'000> * mag_power<10, -4> * one, standard_uncertainty{mag_ratio<52, 10> * mag_power<10, -14> * one}> {} electron_proton_mass_ratio;

// electron-tau mass ratio: 2.875 92 e-4, u = 0.000 26 e-4
inline constexpr struct electron_tau_mass_ratio final :
    named_constant<"electron_tau_mass_ratio", mag_ratio<287'592, 100'000> * mag_power<10, -4> * one, standard_uncertainty{mag_ratio<26, 10> * mag_power<10, -8> * one}> {} electron_tau_mass_ratio;

// electron to alpha particle mass ratio: 1.370 933 554 798 e-4, u = 0.000 000 000 045 e-4
inline constexpr struct electron_to_alpha_particle_mass_ratio final :
    named_constant<"electron_to_alpha_particle_mass_ratio", mag_ratio<1'370'933'554'798, 1'000'000'000'000> * mag_power<10, -4> * one, standard_uncertainty{mag_ratio<45, 10> * mag_power<10, -15> * one}> {} electron_to_alpha_particle_mass_ratio;

// electron to shielded helion mag. mom. ratio: 864.058 257, u = 0.000 010
inline constexpr struct electron_to_shielded_helion_magnetic_moment_ratio final :
    named_constant<"electron_to_shielded_helion_magnetic_moment_ratio", mag_ratio<864'058'257, 1'000'000> * one, standard_uncertainty{mag_ratio<10, 10> * mag_power<10, -5> * one}> {} electron_to_shielded_helion_magnetic_moment_ratio;

// electron to shielded proton mag. mom. ratio: -658.227 5971, u = 0.000 0072
inline constexpr struct electron_to_shielded_proton_magnetic_moment_ratio final :
    named_constant<"electron_to_shielded_proton_magnetic_moment_ratio", -mag_ratio<6'582'275'971, 10'000'000> * one, standard_uncertainty{mag_ratio<72, 10> * mag_power<10, -6> * one}> {} electron_to_shielded_proton_magnetic_moment_ratio;

// electron-triton mass ratio: 1.819 200 062 203 e-4, u = 0.000 000 000 084 e-4
inline constexpr struct electron_triton_mass_ratio final :
    named_constant<"electron_triton_mass_ratio", mag_ratio<1'819'200'062'203, 1'000'000'000'000> * mag_power<10, -4> * one, standard_uncertainty{mag_ratio<84, 10> * mag_power<10, -15> * one}> {} electron_triton_mass_ratio;

// elementary charge over h: 2.417 989 262 e14 A J^-1, u = 0.000 000 015 e14 A J^-1
inline constexpr struct elementary_charge_over_h final :
    named_constant<"elementary_charge_over_h", mag_ratio<2'417'989'262, 1'000'000'000> * mag_power<10, 14> * si::ampere / si::joule, standard_uncertainty{mag_ratio<15, 10> * mag_power<10, 6> * si::ampere / si::joule}> {} elementary_charge_over_h;

// Fermi coupling constant: 1.166 3787 e-5 GeV^-2, u = 0.000 0006 e-5 GeV^-2
inline constexpr struct fermi_coupling_constant final :
    named_constant<"fermi_coupling_constant", mag_ratio<11'663'787, 10'000'000> * mag_power<10, -5> * one / square(si::giga<si::electronvolt>), standard_uncertainty{mag<6> * mag_power<10, -12> * one / square(si::giga<si::electronvolt>)}> {} fermi_coupling_constant;

// first radiation constant: 3.741 771 790 e-16 W m^2, u = 0.000 000 046 e-16 W m^2
inline constexpr struct first_radiation_constant final :
    named_constant<"c_1", mag_ratio<3'741'771'790, 1'000'000'000> * mag_power<10, -16> * si::watt * square(si::metre), standard_uncertainty{mag_ratio<46, 10> * mag_power<10, -24> * si::watt * square(si::metre)}> {} first_radiation_constant;

// first radiation constant for spectral radiance: 1.191 042 953 e-16 W m^2 sr^-1, u = 0.000 000 015 e-16 W m^2 sr^-1
inline constexpr struct first_radiation_constant_for_spectral_radiance final :
    named_constant<"c_1L", mag_ratio<1'191'042'953, 1'000'000'000> * mag_power<10, -16> * si::watt * square(si::metre) / si::steradian, standard_uncertainty{mag_ratio<15, 10> * mag_power<10, -24> * si::watt * square(si::metre) / si::steradian}> {} first_radiation_constant_for_spectral_radiance;

// helion-electron mass ratio: 5495.885 279 22, u = 0.000 000 27
inline constexpr struct helion_electron_mass_ratio final :
    named_constant<"helion_electron_mass_ratio", mag_ratio<549'588'527'922, 100'000'000> * one, standard_uncertainty{mag_ratio<27, 10> * mag_power<10, -7> * one}> {} helion_electron_mass_ratio;

// helion g factor: -4.255 250 616, u = 0.000 000 050
inline constexpr struct helion_g_factor final :
    named_constant<"g_h", -mag_ratio<4'255'250'616, 1'000'000'000> * one, standard_uncertainty{mag_ratio<50, 10> * mag_power<10, -8> * one}> {} helion_g_factor;

// helion mag. mom.: -1.074 617 522 e-26 J T^-1, u = 0.000 000 014 e-26 J T^-1
inline constexpr struct helion_magnetic_moment final :
    named_constant<"helion_magnetic_moment", -mag_ratio<1'074'617'522, 1'000'000'000> * mag_power<10, -26> * si::joule / si::tesla, standard_uncertainty{mag_ratio<14, 10> * mag_power<10, -34> * si::joule / si::tesla}> {} helion_magnetic_moment;

// helion mag. mom. to Bohr magneton ratio: -1.158 740 958 e-3, u = 0.000 000 014 e-3
inline constexpr struct helion_magnetic_moment_to_bohr_magneton_ratio final :
    named_constant<"helion_magnetic_moment_to_bohr_magneton_ratio", -mag_ratio<1'158'740'958, 1'000'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<14, 10> * mag_power<10, -11> * one}> {} helion_magnetic_moment_to_bohr_magneton_ratio;

// helion mag. mom. to nuclear magneton ratio: -2.127 625 308, u = 0.000 000 025
inline constexpr struct helion_magnetic_moment_to_nuclear_magneton_ratio final :
    named_constant<"helion_magnetic_moment_to_nuclear_magneton_ratio", -mag_ratio<2'127'625'308, 1'000'000'000> * one, standard_uncertainty{mag_ratio<25, 10> * mag_power<10, -8> * one}> {} helion_magnetic_moment_to_nuclear_magneton_ratio;

// helion mass: 5.006 412 700 e-27 kg, u = 0.000 000 062 e-27 kg
inline constexpr struct helion_mass final :
    named_constant<"m_h", mag_ratio<5'006'412'700, 1'000'000'000> * mag_power<10, -27> * si::kilogram, standard_uncertainty{mag_ratio<62, 10> * mag_power<10, -35> * si::kilogram}> {} helion_mass;

// helion molar mass: 3.014 932 246 73 e-3 kg mol^-1, u = 0.000 000 000 12 e-3 kg mol^-1
inline constexpr struct helion_molar_mass final :
    named_constant<"helion_molar_mass", mag_ratio<301'493'224'673, 100'000'000'000> * mag_power<10, -3> * si::kilogram / si::mole, standard_uncertainty{mag_ratio<12, 10> * mag_power<10, -13> * si::kilogram / si::mole}> {} helion_molar_mass;

// helion-proton mass ratio: 2.993 152 670 46, u = 0.000 000 000 29
inline constexpr struct helion_proton_mass_ratio final :
    named_constant<"helion_proton_mass_ratio", mag_ratio<299'315'267'046, 100'000'000'000> * one, standard_uncertainty{mag_ratio<29, 10> * mag_power<10, -10> * one}> {} helion_proton_mass_ratio;

// inverse of conductance quantum: 12 906.403 7278 ohm, u = 0.000 0029 ohm
inline constexpr struct inverse_of_conductance_quantum final :
    named_constant<"inverse_of_conductance_quantum", mag_ratio<129'064'037'278, 10'000'000> * si::ohm, standard_uncertainty{mag_ratio<29, 10> * mag_power<10, -6> * si::ohm}> {} inverse_of_conductance_quantum;

// lattice parameter of silicon: 543.102 0504 e-12 m, u = 0.000 0089 e-12 m
inline constexpr struct lattice_parameter_of_silicon final :
    named_constant<"lattice_parameter_of_silicon", mag_ratio<5'431'020'504, 10'000'000> * mag_power<10, -12> * si::metre, standard_uncertainty{mag_ratio<89, 10> * mag_power<10, -18> * si::metre}> {} lattice_parameter_of_silicon;

// Loschmidt constant (273.15 K, 100 kPa): 2.651 6467 e25 m^-3, u = 0.000 0015 e25 m^-3
inline constexpr struct loschmidt_constant_stp final :
    named_constant<"n_0", mag_ratio<26'516'467, 10'000'000> * mag_power<10, 25> * one / cubic(si::metre), standard_uncertainty{mag_ratio<15, 10> * mag_power<10, 19> * one / cubic(si::metre)}> {} loschmidt_constant_stp;

// Loschmidt constant (273.15 K, 101.325 kPa): 2.686 7811 e25 m^-3, u = 0.000 0015 e25 m^-3
inline constexpr struct loschmidt_constant_atm final :
    named_constant<"loschmidt_constant_atm", mag_ratio<26'867'811, 10'000'000> * mag_power<10, 25> * one / cubic(si::metre), standard_uncertainty{mag_ratio<15, 10> * mag_power<10, 19> * one / cubic(si::metre)}> {} loschmidt_constant_atm;

// molar mass constant: 1 e-3 kg mol^-1 (exact)
inline constexpr struct molar_mass_constant final :
    named_constant<"M_u", mag<1> * mag_power<10, -3> * si::kilogram / si::mole> {} molar_mass_constant;

// molar mass of carbon-12: 12 e-3 kg mol^-1 (exact)
inline constexpr struct molar_mass_of_carbon_12 final :
    named_constant<"molar_mass_of_carbon_12", mag<12> * mag_power<10, -3> * si::kilogram / si::mole> {} molar_mass_of_carbon_12;

// molar Planck constant: 3.990 312 7110 e-10 J s mol^-1, u = 0.000 000 0018 e-10 J s mol^-1
inline constexpr struct molar_planck_constant final :
    named_constant<"N_Ah", mag_ratio<39'903'127'110, 10'000'000'000> * mag_power<10, -10> * si::joule * si::second / si::mole, standard_uncertainty{mag_ratio<18, 10> * mag_power<10, -19> * si::joule * si::second / si::mole}> {} molar_planck_constant;

// molar Planck constant times c: 0.119 626 565 582 J m mol^-1, u = 0.000 000 000 054 J m mol^-1
inline constexpr struct molar_planck_constant_times_c final :
    named_constant<"molar_planck_constant_times_c", mag_ratio<119'626'565'582, 1'000'000'000'000> * si::joule * si::metre / si::mole, standard_uncertainty{mag_ratio<54, 10> * mag_power<10, -11> * si::joule * si::metre / si::mole}> {} molar_planck_constant_times_c;

// molar volume of ideal gas (273.15 K, 100 kPa): 22.710 947 e-3 m^3 mol^-1, u = 0.000 013 e-3 m^3 mol^-1
inline constexpr struct molar_volume_of_ideal_gas_stp final :
    named_constant<"molar_volume_of_ideal_gas_stp", mag_ratio<22'710'947, 1'000'000> * mag_power<10, -3> * cubic(si::metre) / si::mole, standard_uncertainty{mag_ratio<13, 10> * mag_power<10, -8> * cubic(si::metre) / si::mole}> {} molar_volume_of_ideal_gas_stp;

// molar volume of ideal gas (273.15 K, 101.325 kPa): 22.413 962 e-3 m^3 mol^-1, u = 0.000 013 e-3 m^3 mol^-1
inline constexpr struct molar_volume_of_ideal_gas_atm final :
    named_constant<"molar_volume_of_ideal_gas_atm", mag_ratio<22'413'962, 1'000'000> * mag_power<10, -3> * cubic(si::metre) / si::mole, standard_uncertainty{mag_ratio<13, 10> * mag_power<10, -8> * cubic(si::metre) / si::mole}> {} molar_volume_of_ideal_gas_atm;

// molar volume of silicon: 12.058 832 14 e-6 m^3 mol^-1, u = 0.000 000 61 e-6 m^3 mol^-1
inline constexpr struct molar_volume_of_silicon final :
    named_constant<"molar_volume_of_silicon", mag_ratio<1'205'883'214, 100'000'000> * mag_power<10, -6> * cubic(si::metre) / si::mole, standard_uncertainty{mag_ratio<61, 10> * mag_power<10, -13> * cubic(si::metre) / si::mole}> {} molar_volume_of_silicon;

// Mo x unit: 1.002 099 52 e-13 m, u = 0.000 000 53 e-13 m
inline constexpr struct molybdenum_x_unit final :
    named_constant<"molybdenum_x_unit", mag_ratio<100'209'952, 100'000'000> * mag_power<10, -13> * si::metre, standard_uncertainty{mag_ratio<53, 10> * mag_power<10, -20> * si::metre}> {} molybdenum_x_unit;

// muon Compton wavelength: 11.734 441 11 e-15 m, u = 0.000 000 26 e-15 m
inline constexpr struct muon_compton_wavelength final :
    named_constant<"muon_compton_wavelength", mag_ratio<1'173'444'111, 100'000'000> * mag_power<10, -15> * si::metre, standard_uncertainty{mag_ratio<26, 10> * mag_power<10, -22> * si::metre}> {} muon_compton_wavelength;

// muon-electron mass ratio: 206.768 2826, u = 0.000 0046
inline constexpr struct muon_electron_mass_ratio final :
    named_constant<"muon_electron_mass_ratio", mag_ratio<2'067'682'826, 10'000'000> * one, standard_uncertainty{mag_ratio<46, 10> * mag_power<10, -6> * one}> {} muon_electron_mass_ratio;

// muon g factor: -2.002 331 8418, u = 0.000 000 0013
inline constexpr struct muon_g_factor final :
    named_constant<symbol_text{u8"g_μ", "g_mu"}, -mag_ratio<20'023'318'418, 10'000'000'000> * one, standard_uncertainty{mag_ratio<13, 10> * mag_power<10, -9> * one}> {} muon_g_factor;

// muon mag. mom.: -4.490 448 26 e-26 J T^-1, u = 0.000 000 10 e-26 J T^-1
inline constexpr struct muon_magnetic_moment final :
    named_constant<symbol_text{u8"μ_μ", "mu_mu"}, -mag_ratio<449'044'826, 100'000'000> * mag_power<10, -26> * si::joule / si::tesla, standard_uncertainty{mag_ratio<10, 10> * mag_power<10, -33> * si::joule / si::tesla}> {} muon_magnetic_moment;

// muon mag. mom. anomaly: 1.165 920 89 e-3, u = 0.000 000 63 e-3
inline constexpr struct muon_magnetic_moment_anomaly final :
    named_constant<"muon_magnetic_moment_anomaly", mag_ratio<116'592'089, 100'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<63, 10> * mag_power<10, -10> * one}> {} muon_magnetic_moment_anomaly;

// muon mag. mom. to Bohr magneton ratio: -4.841 970 48 e-3, u = 0.000 000 11 e-3
inline constexpr struct muon_magnetic_moment_to_bohr_magneton_ratio final :
    named_constant<"muon_magnetic_moment_to_bohr_magneton_ratio", -mag_ratio<484'197'048, 100'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<11, 10> * mag_power<10, -10> * one}> {} muon_magnetic_moment_to_bohr_magneton_ratio;

// muon mag. mom. to nuclear magneton ratio: -8.890 597 05, u = 0.000 000 20
inline constexpr struct muon_magnetic_moment_to_nuclear_magneton_ratio final :
    named_constant<"muon_magnetic_moment_to_nuclear_magneton_ratio", -mag_ratio<889'059'705, 100'000'000> * one, standard_uncertainty{mag_ratio<20, 10> * mag_power<10, -7> * one}> {} muon_magnetic_moment_to_nuclear_magneton_ratio;

// muon molar mass: 0.113 428 9257 e-3 kg mol^-1, u = 0.000 000 0025 e-3 kg mol^-1
inline constexpr struct muon_molar_mass final :
    named_constant<"muon_molar_mass", mag_ratio<1'134'289'257, 10'000'000'000> * mag_power<10, -3> * si::kilogram / si::mole, standard_uncertainty{mag_ratio<25, 10> * mag_power<10, -12> * si::kilogram / si::mole}> {} muon_molar_mass;

// muon-neutron mass ratio: 0.112 454 5167, u = 0.000 000 0025
inline constexpr struct muon_neutron_mass_ratio final :
    named_constant<"muon_neutron_mass_ratio", mag_ratio<1'124'545'167, 10'000'000'000> * one, standard_uncertainty{mag_ratio<25, 10> * mag_power<10, -9> * one}> {} muon_neutron_mass_ratio;

// muon-proton mag. mom. ratio: -3.183 345 142, u = 0.000 000 071
inline constexpr struct muon_proton_magnetic_moment_ratio final :
    named_constant<"muon_proton_magnetic_moment_ratio", -mag_ratio<3'183'345'142, 1'000'000'000> * one, standard_uncertainty{mag_ratio<71, 10> * mag_power<10, -8> * one}> {} muon_proton_magnetic_moment_ratio;

// muon-proton mass ratio: 0.112 609 5262, u = 0.000 000 0025
inline constexpr struct muon_proton_mass_ratio final :
    named_constant<"muon_proton_mass_ratio", mag_ratio<1'126'095'262, 10'000'000'000> * one, standard_uncertainty{mag_ratio<25, 10> * mag_power<10, -9> * one}> {} muon_proton_mass_ratio;

// muon-tau mass ratio: 5.946 49 e-2, u = 0.000 54 e-2
inline constexpr struct muon_tau_mass_ratio final :
    named_constant<"muon_tau_mass_ratio", mag_ratio<594'649, 100'000> * mag_power<10, -2> * one, standard_uncertainty{mag_ratio<54, 10> * mag_power<10, -6> * one}> {} muon_tau_mass_ratio;

// natural unit of energy: 8.187 105 65 e-14 J, u = 0.000 000 10 e-14 J
inline constexpr struct natural_unit_of_energy final :
    named_constant<"natural_unit_of_energy", mag_ratio<818'710'565, 100'000'000> * mag_power<10, -14> * si::joule, standard_uncertainty{mag_ratio<10, 10> * mag_power<10, -21> * si::joule}> {} natural_unit_of_energy;

// natural unit of length: 386.159 267 64 e-15 m, u = 0.000 000 18 e-15 m
inline constexpr struct natural_unit_of_length final :
    named_constant<"natural_unit_of_length", mag_ratio<38'615'926'764, 100'000'000> * mag_power<10, -15> * si::metre, standard_uncertainty{mag_ratio<18, 10> * mag_power<10, -22> * si::metre}> {} natural_unit_of_length;

// natural unit of mom.um: 2.730 924 488 e-22 kg m s^-1, u = 0.000 000 034 e-22 kg m s^-1
inline constexpr struct natural_unit_of_momentum final :
    named_constant<"natural_unit_of_momentum", mag_ratio<2'730'924'488, 1'000'000'000> * mag_power<10, -22> * si::kilogram * si::metre / si::second, standard_uncertainty{mag_ratio<34, 10> * mag_power<10, -30> * si::kilogram * si::metre / si::second}> {} natural_unit_of_momentum;

// natural unit of time: 1.288 088 667 12 e-21 s, u = 0.000 000 000 58 e-21 s
inline constexpr struct natural_unit_of_time final :
    named_constant<"natural_unit_of_time", mag_ratio<128'808'866'712, 100'000'000'000> * mag_power<10, -21> * si::second, standard_uncertainty{mag_ratio<58, 10> * mag_power<10, -31> * si::second}> {} natural_unit_of_time;

// neutron Compton wavelength: 1.319 590 904 81 e-15 m, u = 0.000 000 000 88 e-15 m
inline constexpr struct neutron_compton_wavelength final :
    named_constant<"neutron_compton_wavelength", mag_ratio<131'959'090'481, 100'000'000'000> * mag_power<10, -15> * si::metre, standard_uncertainty{mag_ratio<88, 10> * mag_power<10, -25> * si::metre}> {} neutron_compton_wavelength;

// neutron-electron mag. mom. ratio: 1.040 668 82 e-3, u = 0.000 000 25 e-3
inline constexpr struct neutron_electron_magnetic_moment_ratio final :
    named_constant<"neutron_electron_magnetic_moment_ratio", mag_ratio<104'066'882, 100'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<25, 10> * mag_power<10, -10> * one}> {} neutron_electron_magnetic_moment_ratio;

// neutron-electron mass ratio: 1838.683 661 58, u = 0.000 000 90
inline constexpr struct neutron_electron_mass_ratio final :
    named_constant<"neutron_electron_mass_ratio", mag_ratio<183'868'366'158, 100'000'000> * one, standard_uncertainty{mag_ratio<90, 10> * mag_power<10, -7> * one}> {} neutron_electron_mass_ratio;

// neutron g factor: -3.826 085 45, u = 0.000 000 90
inline constexpr struct neutron_g_factor final :
    named_constant<"g_n", -mag_ratio<382'608'545, 100'000'000> * one, standard_uncertainty{mag_ratio<90, 10> * mag_power<10, -7> * one}> {} neutron_g_factor;

// neutron gyromag. ratio: 1.832 471 72 e8 s^-1 T^-1, u = 0.000 000 43 e8 s^-1 T^-1
inline constexpr struct neutron_gyromagnetic_ratio final :
    named_constant<symbol_text{u8"γ_n", "gamma_n"}, mag_ratio<183'247'172, 100'000'000> * mag_power<10, 8> * one / si::second / si::tesla, standard_uncertainty{mag_ratio<43, 10> * mag_power<10, 1> * one / si::second / si::tesla}> {} neutron_gyromagnetic_ratio;

// neutron mag. mom.: -0.966 236 50 e-26 J T^-1, u = 0.000 000 23 e-26 J T^-1
inline constexpr struct neutron_magnetic_moment final :
    named_constant<symbol_text{u8"μ_n", "mu_n"}, -mag_ratio<96'623'650, 100'000'000> * mag_power<10, -26> * si::joule / si::tesla, standard_uncertainty{mag_ratio<23, 10> * mag_power<10, -33> * si::joule / si::tesla}> {} neutron_magnetic_moment;

// neutron mag. mom. to Bohr magneton ratio: -1.041 875 63 e-3, u = 0.000 000 25 e-3
inline constexpr struct neutron_magnetic_moment_to_bohr_magneton_ratio final :
    named_constant<"neutron_magnetic_moment_to_bohr_magneton_ratio", -mag_ratio<104'187'563, 100'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<25, 10> * mag_power<10, -10> * one}> {} neutron_magnetic_moment_to_bohr_magneton_ratio;

// neutron mag. mom. to nuclear magneton ratio: -1.913 042 73, u = 0.000 000 45
inline constexpr struct neutron_magnetic_moment_to_nuclear_magneton_ratio final :
    named_constant<"neutron_magnetic_moment_to_nuclear_magneton_ratio", -mag_ratio<191'304'273, 100'000'000> * one, standard_uncertainty{mag_ratio<45, 10> * mag_power<10, -7> * one}> {} neutron_magnetic_moment_to_nuclear_magneton_ratio;

// neutron molar mass: 1.008 664 915 88 e-3 kg mol^-1, u = 0.000 000 000 49 e-3 kg mol^-1
inline constexpr struct neutron_molar_mass final :
    named_constant<"neutron_molar_mass", mag_ratio<100'866'491'588, 100'000'000'000> * mag_power<10, -3> * si::kilogram / si::mole, standard_uncertainty{mag_ratio<49, 10> * mag_power<10, -13> * si::kilogram / si::mole}> {} neutron_molar_mass;

// neutron-muon mass ratio: 8.892 484 08, u = 0.000 000 20
inline constexpr struct neutron_muon_mass_ratio final :
    named_constant<"neutron_muon_mass_ratio", mag_ratio<889'248'408, 100'000'000> * one, standard_uncertainty{mag_ratio<20, 10> * mag_power<10, -7> * one}> {} neutron_muon_mass_ratio;

// neutron-proton mag. mom. ratio: -0.684 979 34, u = 0.000 000 16
inline constexpr struct neutron_proton_magnetic_moment_ratio final :
    named_constant<"neutron_proton_magnetic_moment_ratio", -mag_ratio<68'497'934, 100'000'000> * one, standard_uncertainty{mag_ratio<16, 10> * mag_power<10, -7> * one}> {} neutron_proton_magnetic_moment_ratio;

// neutron-proton mass difference: 2.305 573 77 e-30, u = 0.000 000 85 e-30
inline constexpr struct neutron_proton_mass_difference final :
    named_constant<"neutron_proton_mass_difference", mag_ratio<230'557'377, 100'000'000> * mag_power<10, -30> * one, standard_uncertainty{mag_ratio<85, 10> * mag_power<10, -37> * one}> {} neutron_proton_mass_difference;

// neutron-proton mass ratio: 1.001 378 418 98, u = 0.000 000 000 51
inline constexpr struct neutron_proton_mass_ratio final :
    named_constant<"neutron_proton_mass_ratio", mag_ratio<100'137'841'898, 100'000'000'000> * one, standard_uncertainty{mag_ratio<51, 10> * mag_power<10, -10> * one}> {} neutron_proton_mass_ratio;

// neutron-tau mass ratio: 0.528 790, u = 0.000 048
inline constexpr struct neutron_tau_mass_ratio final :
    named_constant<"neutron_tau_mass_ratio", mag_ratio<528'790, 1'000'000> * one, standard_uncertainty{mag_ratio<48, 10> * mag_power<10, -5> * one}> {} neutron_tau_mass_ratio;

// neutron to shielded proton mag. mom. ratio: -0.684 996 94, u = 0.000 000 16
inline constexpr struct neutron_to_shielded_proton_magnetic_moment_ratio final :
    named_constant<"neutron_to_shielded_proton_magnetic_moment_ratio", -mag_ratio<68'499'694, 100'000'000> * one, standard_uncertainty{mag_ratio<16, 10> * mag_power<10, -7> * one}> {} neutron_to_shielded_proton_magnetic_moment_ratio;

// Planck length: 1.616 229 e-35 m, u = 0.000 038 e-35 m
inline constexpr struct planck_length final :
    named_constant<"l_P", mag_ratio<1'616'229, 1'000'000> * mag_power<10, -35> * si::metre, standard_uncertainty{mag_ratio<38, 10> * mag_power<10, -40> * si::metre}> {} planck_length;

// Planck mass: 2.176 470 e-8 kg, u = 0.000 051 e-8 kg
inline constexpr struct planck_mass final :
    named_constant<"m_P", mag_ratio<2'176'470, 1'000'000> * mag_power<10, -8> * si::kilogram, standard_uncertainty{mag_ratio<51, 10> * mag_power<10, -13> * si::kilogram}> {} planck_mass;

// Planck temperature: 1.416 808 e32 K, u = 0.000 033 e32 K
inline constexpr struct planck_temperature final :
    named_constant<"T_P", mag_ratio<1'416'808, 1'000'000> * mag_power<10, 32> * si::kelvin, standard_uncertainty{mag_ratio<33, 10> * mag_power<10, 27> * si::kelvin}> {} planck_temperature;

// Planck time: 5.391 16 e-44 s, u = 0.000 13 e-44 s
inline constexpr struct planck_time final :
    named_constant<"t_P", mag_ratio<539'116, 100'000> * mag_power<10, -44> * si::second, standard_uncertainty{mag_ratio<13, 10> * mag_power<10, -48> * si::second}> {} planck_time;

// proton charge to mass quotient: 9.578 833 226 e7 C kg^-1, u = 0.000 000 059 e7 C kg^-1
inline constexpr struct proton_charge_to_mass_quotient final :
    named_constant<"proton_charge_to_mass_quotient", mag_ratio<9'578'833'226, 1'000'000'000> * mag_power<10, 7> * si::coulomb / si::kilogram, standard_uncertainty{mag_ratio<59, 10> * mag_power<10, -1> * si::coulomb / si::kilogram}> {} proton_charge_to_mass_quotient;

// proton Compton wavelength: 1.321 409 853 96 e-15 m, u = 0.000 000 000 61 e-15 m
inline constexpr struct proton_compton_wavelength final :
    named_constant<"proton_compton_wavelength", mag_ratio<132'140'985'396, 100'000'000'000> * mag_power<10, -15> * si::metre, standard_uncertainty{mag_ratio<61, 10> * mag_power<10, -25> * si::metre}> {} proton_compton_wavelength;

// proton g factor: 5.585 694 702, u = 0.000 000 017
inline constexpr struct proton_g_factor final :
    named_constant<"g_p", mag_ratio<5'585'694'702, 1'000'000'000> * one, standard_uncertainty{mag_ratio<17, 10> * mag_power<10, -8> * one}> {} proton_g_factor;

// proton gyromag. ratio: 2.675 221 900 e8 s^-1 T^-1, u = 0.000 000 018 e8 s^-1 T^-1
inline constexpr struct proton_gyromagnetic_ratio final :
    named_constant<symbol_text{u8"γ_p", "gamma_p"}, mag_ratio<2'675'221'900, 1'000'000'000> * mag_power<10, 8> * one / si::second / si::tesla, standard_uncertainty{mag_ratio<18, 10> * one / si::second / si::tesla}> {} proton_gyromagnetic_ratio;

// proton mag. mom.: 1.410 606 7873 e-26 J T^-1, u = 0.000 000 0097 e-26 J T^-1
inline constexpr struct proton_magnetic_moment final :
    named_constant<symbol_text{u8"μ_p", "mu_p"}, mag_ratio<14'106'067'873, 10'000'000'000> * mag_power<10, -26> * si::joule / si::tesla, standard_uncertainty{mag_ratio<97, 10> * mag_power<10, -35> * si::joule / si::tesla}> {} proton_magnetic_moment;

// proton mag. mom. to Bohr magneton ratio: 1.521 032 2053 e-3, u = 0.000 000 0046 e-3
inline constexpr struct proton_magnetic_moment_to_bohr_magneton_ratio final :
    named_constant<"proton_magnetic_moment_to_bohr_magneton_ratio", mag_ratio<15'210'322'053, 10'000'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<46, 10> * mag_power<10, -12> * one}> {} proton_magnetic_moment_to_bohr_magneton_ratio;

// proton mag. mom. to nuclear magneton ratio: 2.792 847 3508, u = 0.000 000 0085
inline constexpr struct proton_magnetic_moment_to_nuclear_magneton_ratio final :
    named_constant<"proton_magnetic_moment_to_nuclear_magneton_ratio", mag_ratio<27'928'473'508, 10'000'000'000> * one, standard_uncertainty{mag_ratio<85, 10> * mag_power<10, -9> * one}> {} proton_magnetic_moment_to_nuclear_magneton_ratio;

// proton mag. shielding correction: 25.691 e-6, u = 0.011 e-6
inline constexpr struct proton_magnetic_shielding_correction final :
    named_constant<"proton_magnetic_shielding_correction", mag_ratio<25'691, 1'000> * mag_power<10, -6> * one, standard_uncertainty{mag_ratio<11, 10> * mag_power<10, -8> * one}> {} proton_magnetic_shielding_correction;

// proton molar mass: 1.007 276 466 879 e-3 kg mol^-1, u = 0.000 000 000 091 e-3 kg mol^-1
inline constexpr struct proton_molar_mass final :
    named_constant<"proton_molar_mass", mag_ratio<1'007'276'466'879, 1'000'000'000'000> * mag_power<10, -3> * si::kilogram / si::mole, standard_uncertainty{mag_ratio<91, 10> * mag_power<10, -14> * si::kilogram / si::mole}> {} proton_molar_mass;

// proton-muon mass ratio: 8.880 243 38, u = 0.000 000 20
inline constexpr struct proton_muon_mass_ratio final :
    named_constant<"proton_muon_mass_ratio", mag_ratio<888'024'338, 100'000'000> * one, standard_uncertainty{mag_ratio<20, 10> * mag_power<10, -7> * one}> {} proton_muon_mass_ratio;

// proton-neutron mag. mom. ratio: -1.459 898 05, u = 0.000 000 34
inline constexpr struct proton_neutron_magnetic_moment_ratio final :
    named_constant<"proton_neutron_magnetic_moment_ratio", -mag_ratio<145'989'805, 100'000'000> * one, standard_uncertainty{mag_ratio<34, 10> * mag_power<10, -7> * one}> {} proton_neutron_magnetic_moment_ratio;

// proton-neutron mass ratio: 0.998 623 478 44, u = 0.000 000 000 51
inline constexpr struct proton_neutron_mass_ratio final :
    named_constant<"proton_neutron_mass_ratio", mag_ratio<99'862'347'844, 100'000'000'000> * one, standard_uncertainty{mag_ratio<51, 10> * mag_power<10, -10> * one}> {} proton_neutron_mass_ratio;

// proton rms charge radius: 0.8751 e-15 m, u = 0.0061 e-15 m
inline constexpr struct proton_rms_charge_radius final :
    named_constant<"r_p", mag_ratio<8'751, 10'000> * mag_power<10, -15> * si::metre, standard_uncertainty{mag_ratio<61, 10> * mag_power<10, -18> * si::metre}> {} proton_rms_charge_radius;

// proton-tau mass ratio: 0.528 063, u = 0.000 048
inline constexpr struct proton_tau_mass_ratio final :
    named_constant<"proton_tau_mass_ratio", mag_ratio<528'063, 1'000'000> * one, standard_uncertainty{mag_ratio<48, 10> * mag_power<10, -5> * one}> {} proton_tau_mass_ratio;

// quantum of circulation: 3.636 947 5486 e-4 m^2 s^-1, u = 0.000 000 0017 e-4 m^2 s^-1
inline constexpr struct quantum_of_circulation final :
    named_constant<"quantum_of_circulation", mag_ratio<36'369'475'486, 10'000'000'000> * mag_power<10, -4> * square(si::metre) / si::second, standard_uncertainty{mag_ratio<17, 10> * mag_power<10, -13> * square(si::metre) / si::second}> {} quantum_of_circulation;

// quantum of circulation times 2: 7.273 895 0972 e-4 m^2 s^-1, u = 0.000 000 0033 e-4 m^2 s^-1
inline constexpr struct quantum_of_circulation_times_2 final :
    named_constant<"quantum_of_circulation_times_2", mag_ratio<72'738'950'972, 10'000'000'000> * mag_power<10, -4> * square(si::metre) / si::second, standard_uncertainty{mag_ratio<33, 10> * mag_power<10, -13> * square(si::metre) / si::second}> {} quantum_of_circulation_times_2;

// Sackur-Tetrode constant (1 K, 100 kPa): -1.151 7084, u = 0.000 0014
inline constexpr struct sackur_tetrode_constant_100_kpa final :
    named_constant<"sackur_tetrode_constant_100_kpa", -mag_ratio<11'517'084, 10'000'000> * one, standard_uncertainty{mag_ratio<14, 10> * mag_power<10, -6> * one}> {} sackur_tetrode_constant_100_kpa;

// Sackur-Tetrode constant (1 K, 101.325 kPa): -1.164 8714, u = 0.000 0014
inline constexpr struct sackur_tetrode_constant_101_325_kpa final :
    named_constant<"sackur_tetrode_constant_101_325_kpa", -mag_ratio<11'648'714, 10'000'000> * one, standard_uncertainty{mag_ratio<14, 10> * mag_power<10, -6> * one}> {} sackur_tetrode_constant_101_325_kpa;

// second radiation constant: 1.438 777 36 e-2 m K, u = 0.000 000 83 e-2 m K
inline constexpr struct second_radiation_constant final :
    named_constant<"c_2", mag_ratio<143'877'736, 100'000'000> * mag_power<10, -2> * si::metre * si::kelvin, standard_uncertainty{mag_ratio<83, 10> * mag_power<10, -9> * si::metre * si::kelvin}> {} second_radiation_constant;

// shielded helion gyromag. ratio: 2.037 894 585 e8 s^-1 T^-1, u = 0.000 000 027 e8 s^-1 T^-1
inline constexpr struct shielded_helion_gyromagnetic_ratio final :
    named_constant<"shielded_helion_gyromagnetic_ratio", mag_ratio<2'037'894'585, 1'000'000'000> * mag_power<10, 8> * one / si::second / si::tesla, standard_uncertainty{mag_ratio<27, 10> * one / si::second / si::tesla}> {} shielded_helion_gyromagnetic_ratio;

// shielded helion mag. mom.: -1.074 553 080 e-26 J T^-1, u = 0.000 000 014 e-26 J T^-1
inline constexpr struct shielded_helion_magnetic_moment final :
    named_constant<"shielded_helion_magnetic_moment", -mag_ratio<1'074'553'080, 1'000'000'000> * mag_power<10, -26> * si::joule / si::tesla, standard_uncertainty{mag_ratio<14, 10> * mag_power<10, -34> * si::joule / si::tesla}> {} shielded_helion_magnetic_moment;

// shielded helion mag. mom. to Bohr magneton ratio: -1.158 671 471 e-3, u = 0.000 000 014 e-3
inline constexpr struct shielded_helion_magnetic_moment_to_bohr_magneton_ratio final :
    named_constant<"shielded_helion_magnetic_moment_to_bohr_magneton_ratio", -mag_ratio<1'158'671'471, 1'000'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<14, 10> * mag_power<10, -11> * one}> {} shielded_helion_magnetic_moment_to_bohr_magneton_ratio;

// shielded helion mag. mom. to nuclear magneton ratio: -2.127 497 720, u = 0.000 000 025
inline constexpr struct shielded_helion_magnetic_moment_to_nuclear_magneton_ratio final :
    named_constant<"shielded_helion_magnetic_moment_to_nuclear_magneton_ratio", -mag_ratio<2'127'497'720, 1'000'000'000> * one, standard_uncertainty{mag_ratio<25, 10> * mag_power<10, -8> * one}> {} shielded_helion_magnetic_moment_to_nuclear_magneton_ratio;

// shielded helion to proton mag. mom. ratio: -0.761 766 5603, u = 0.000 000 0092
inline constexpr struct shielded_helion_to_proton_magnetic_moment_ratio final :
    named_constant<"shielded_helion_to_proton_magnetic_moment_ratio", -mag_ratio<7'617'665'603, 10'000'000'000> * one, standard_uncertainty{mag_ratio<92, 10> * mag_power<10, -9> * one}> {} shielded_helion_to_proton_magnetic_moment_ratio;

// shielded helion to shielded proton mag. mom. ratio: -0.761 786 1313, u = 0.000 000 0033
inline constexpr struct shielded_helion_to_shielded_proton_magnetic_moment_ratio final :
    named_constant<"shielded_helion_to_shielded_proton_magnetic_moment_ratio", -mag_ratio<7'617'861'313, 10'000'000'000> * one, standard_uncertainty{mag_ratio<33, 10> * mag_power<10, -9> * one}> {} shielded_helion_to_shielded_proton_magnetic_moment_ratio;

// shielded proton gyromag. ratio: 2.675 153 171 e8 s^-1 T^-1, u = 0.000 000 033 e8 s^-1 T^-1
inline constexpr struct shielded_proton_gyromagnetic_ratio final :
    named_constant<"shielded_proton_gyromagnetic_ratio", mag_ratio<2'675'153'171, 1'000'000'000> * mag_power<10, 8> * one / si::second / si::tesla, standard_uncertainty{mag_ratio<33, 10> * one / si::second / si::tesla}> {} shielded_proton_gyromagnetic_ratio;

// shielded proton mag. mom.: 1.410 570 547 e-26 J T^-1, u = 0.000 000 018 e-26 J T^-1
inline constexpr struct shielded_proton_magnetic_moment final :
    named_constant<"shielded_proton_magnetic_moment", mag_ratio<1'410'570'547, 1'000'000'000> * mag_power<10, -26> * si::joule / si::tesla, standard_uncertainty{mag_ratio<18, 10> * mag_power<10, -34> * si::joule / si::tesla}> {} shielded_proton_magnetic_moment;

// shielded proton mag. mom. to Bohr magneton ratio: 1.520 993 128 e-3, u = 0.000 000 017 e-3
inline constexpr struct shielded_proton_magnetic_moment_to_bohr_magneton_ratio final :
    named_constant<"shielded_proton_magnetic_moment_to_bohr_magneton_ratio", mag_ratio<1'520'993'128, 1'000'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<17, 10> * mag_power<10, -11> * one}> {} shielded_proton_magnetic_moment_to_bohr_magneton_ratio;

// shielded proton mag. mom. to nuclear magneton ratio: 2.792 775 600, u = 0.000 000 030
inline constexpr struct shielded_proton_magnetic_moment_to_nuclear_magneton_ratio final :
    named_constant<"shielded_proton_magnetic_moment_to_nuclear_magneton_ratio", mag_ratio<2'792'775'600, 1'000'000'000> * one, standard_uncertainty{mag_ratio<30, 10> * mag_power<10, -8> * one}> {} shielded_proton_magnetic_moment_to_nuclear_magneton_ratio;

// tau Compton wavelength: 0.697 787 e-15 m, u = 0.000 063 e-15 m
inline constexpr struct tau_compton_wavelength final :
    named_constant<"tau_compton_wavelength", mag_ratio<697'787, 1'000'000> * mag_power<10, -15> * si::metre, standard_uncertainty{mag_ratio<63, 10> * mag_power<10, -20> * si::metre}> {} tau_compton_wavelength;

// tau-electron mass ratio: 3477.15, u = 0.31
inline constexpr struct tau_electron_mass_ratio final :
    named_constant<"tau_electron_mass_ratio", mag_ratio<347'715, 100> * one, standard_uncertainty{mag_ratio<31, 10> * mag_power<10, -1> * one}> {} tau_electron_mass_ratio;

// tau mass: 3.167 47 e-27 kg, u = 0.000 29 e-27 kg
inline constexpr struct tau_mass final :
    named_constant<symbol_text{u8"m_τ", "m_tau"}, mag_ratio<316'747, 100'000> * mag_power<10, -27> * si::kilogram, standard_uncertainty{mag_ratio<29, 10> * mag_power<10, -31> * si::kilogram}> {} tau_mass;

// tau molar mass: 1.907 49 e-3 kg mol^-1, u = 0.000 17 e-3 kg mol^-1
inline constexpr struct tau_molar_mass final :
    named_constant<"tau_molar_mass", mag_ratio<190'749, 100'000> * mag_power<10, -3> * si::kilogram / si::mole, standard_uncertainty{mag_ratio<17, 10> * mag_power<10, -7> * si::kilogram / si::mole}> {} tau_molar_mass;

// tau-muon mass ratio: 16.8167, u = 0.0015
inline constexpr struct tau_muon_mass_ratio final :
    named_constant<"tau_muon_mass_ratio", mag_ratio<168'167, 10'000> * one, standard_uncertainty{mag_ratio<15, 10> * mag_power<10, -3> * one}> {} tau_muon_mass_ratio;

// tau-neutron mass ratio: 1.891 11, u = 0.000 17
inline constexpr struct tau_neutron_mass_ratio final :
    named_constant<"tau_neutron_mass_ratio", mag_ratio<189'111, 100'000> * one, standard_uncertainty{mag_ratio<17, 10> * mag_power<10, -4> * one}> {} tau_neutron_mass_ratio;

// tau-proton mass ratio: 1.893 72, u = 0.000 17
inline constexpr struct tau_proton_mass_ratio final :
    named_constant<"tau_proton_mass_ratio", mag_ratio<189'372, 100'000> * one, standard_uncertainty{mag_ratio<17, 10> * mag_power<10, -4> * one}> {} tau_proton_mass_ratio;

// Thomson cross section: 0.665 245 871 58 e-28 m^2, u = 0.000 000 000 91 e-28 m^2
inline constexpr struct thomson_cross_section final :
    named_constant<symbol_text{u8"σ_e", "sigma_e"}, mag_ratio<66'524'587'158, 100'000'000'000> * mag_power<10, -28> * square(si::metre), standard_uncertainty{mag_ratio<91, 10> * mag_power<10, -38> * square(si::metre)}> {} thomson_cross_section;

// triton-electron mass ratio: 5496.921 535 88, u = 0.000 000 26
inline constexpr struct triton_electron_mass_ratio final :
    named_constant<"triton_electron_mass_ratio", mag_ratio<549'692'153'588, 100'000'000> * one, standard_uncertainty{mag_ratio<26, 10> * mag_power<10, -7> * one}> {} triton_electron_mass_ratio;

// triton g factor: 5.957 924 920, u = 0.000 000 028
inline constexpr struct triton_g_factor final :
    named_constant<"g_t", mag_ratio<5'957'924'920, 1'000'000'000> * one, standard_uncertainty{mag_ratio<28, 10> * mag_power<10, -8> * one}> {} triton_g_factor;

// triton mag. mom.: 1.504 609 503 e-26 J T^-1, u = 0.000 000 012 e-26 J T^-1
inline constexpr struct triton_magnetic_moment final :
    named_constant<symbol_text{u8"μ_t", "mu_t"}, mag_ratio<1'504'609'503, 1'000'000'000> * mag_power<10, -26> * si::joule / si::tesla, standard_uncertainty{mag_ratio<12, 10> * mag_power<10, -34> * si::joule / si::tesla}> {} triton_magnetic_moment;

// triton mag. mom. to Bohr magneton ratio: 1.622 393 6616 e-3, u = 0.000 000 0076 e-3
inline constexpr struct triton_magnetic_moment_to_bohr_magneton_ratio final :
    named_constant<"triton_magnetic_moment_to_bohr_magneton_ratio", mag_ratio<16'223'936'616, 10'000'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<76, 10> * mag_power<10, -12> * one}> {} triton_magnetic_moment_to_bohr_magneton_ratio;

// triton mag. mom. to nuclear magneton ratio: 2.978 962 460, u = 0.000 000 014
inline constexpr struct triton_magnetic_moment_to_nuclear_magneton_ratio final :
    named_constant<"triton_magnetic_moment_to_nuclear_magneton_ratio", mag_ratio<2'978'962'460, 1'000'000'000> * one, standard_uncertainty{mag_ratio<14, 10> * mag_power<10, -8> * one}> {} triton_magnetic_moment_to_nuclear_magneton_ratio;

// triton mass: 5.007 356 665 e-27 kg, u = 0.000 000 062 e-27 kg
inline constexpr struct triton_mass final :
    named_constant<"m_t", mag_ratio<5'007'356'665, 1'000'000'000> * mag_power<10, -27> * si::kilogram, standard_uncertainty{mag_ratio<62, 10> * mag_power<10, -35> * si::kilogram}> {} triton_mass;

// triton molar mass: 3.015 500 716 32 e-3 kg mol^-1, u = 0.000 000 000 11 e-3 kg mol^-1
inline constexpr struct triton_molar_mass final :
    named_constant<"triton_molar_mass", mag_ratio<301'550'071'632, 100'000'000'000> * mag_power<10, -3> * si::kilogram / si::mole, standard_uncertainty{mag_ratio<11, 10> * mag_power<10, -13> * si::kilogram / si::mole}> {} triton_molar_mass;

// triton-proton mass ratio: 2.993 717 033 48, u = 0.000 000 000 22
inline constexpr struct triton_proton_mass_ratio final :
    named_constant<"triton_proton_mass_ratio", mag_ratio<299'371'703'348, 100'000'000'000> * one, standard_uncertainty{mag_ratio<22, 10> * mag_power<10, -10> * one}> {} triton_proton_mass_ratio;

// weak mixing angle: 0.2223, u = 0.0021
inline constexpr struct weak_mixing_angle final :
    named_constant<"weak_mixing_angle", mag_ratio<2'223, 10'000> * one, standard_uncertainty{mag_ratio<21, 10> * mag_power<10, -3> * one}> {} weak_mixing_angle;

// Wien frequency displacement law constant: 5.878 9238 e10 Hz K^-1, u = 0.000 0034 e10 Hz K^-1
inline constexpr struct wien_frequency_displacement_law_constant final :
    named_constant<symbol_text{u8"b′", "b_prime"}, mag_ratio<58'789'238, 10'000'000> * mag_power<10, 10> * si::hertz / si::kelvin, standard_uncertainty{mag_ratio<34, 10> * mag_power<10, 4> * si::hertz / si::kelvin}> {} wien_frequency_displacement_law_constant;

// Wien wavelength displacement law constant: 2.897 7729 e-3 m K, u = 0.000 0017 e-3 m K
inline constexpr struct wien_wavelength_displacement_law_constant final :
    named_constant<"b", mag_ratio<28'977'729, 10'000'000> * mag_power<10, -3> * si::metre * si::kelvin, standard_uncertainty{mag_ratio<17, 10> * mag_power<10, -9> * si::metre * si::kelvin}> {} wien_wavelength_displacement_law_constant;

// characteristic impedance of vacuum: 376.730 313 461... ohm (exact)
inline constexpr struct characteristic_impedance_of_vacuum final :
    named_constant<"Z_0", magnetic_constant * speed_of_light_in_vacuum> {} characteristic_impedance_of_vacuum;

// atomic unit of permittivity: 1.112 650 056... e-10 F m^-1 (exact)
// 4 π ε₀; exact only while μ₀ was exact, hence a relation only pre-2019.
inline constexpr struct atomic_unit_of_permittivity final :
    named_constant<"atomic_unit_of_permittivity", mag<4> * π / magnetic_constant / square(speed_of_light_in_vacuum)> {} atomic_unit_of_permittivity;

// atomic unit of action: 1.054 571 800 e-34 J s, u = 0.000 000 013 e-34 J s
inline constexpr auto atomic_unit_of_action = reduced_planck_constant;

// atomic unit of charge: 1.602 176 6208 e-19 C, u = 0.000 000 0098 e-19 C
inline constexpr auto atomic_unit_of_charge = elementary_charge;

// atomic unit of energy: 4.359 744 650 e-18 J, u = 0.000 000 054 e-18 J
inline constexpr auto atomic_unit_of_energy = hartree_energy;

// atomic unit of length: 0.529 177 210 67 e-10 m, u = 0.000 000 000 12 e-10 m
inline constexpr auto atomic_unit_of_length = bohr_radius;

// atomic unit of mass: 9.109 383 56 e-31 kg, u = 0.000 000 11 e-31 kg
inline constexpr auto atomic_unit_of_mass = electron_mass;

// natural unit of action: 1.054 571 800 e-34 J s, u = 0.000 000 013 e-34 J s
inline constexpr auto natural_unit_of_action = reduced_planck_constant;

// natural unit of mass: 9.109 383 56 e-31 kg, u = 0.000 000 11 e-31 kg
inline constexpr auto natural_unit_of_mass = electron_mass;

// natural unit of velocity: 299 792 458 m s^-1 (exact)
inline constexpr auto natural_unit_of_velocity = speed_of_light_in_vacuum;

// unified atomic mass unit: 1.660 539 040 e-27 kg, u = 0.000 000 020 e-27 kg
inline constexpr auto unified_atomic_mass_unit = atomic_mass_constant;
// clang-format on

}  // namespace codata2014

}  // namespace mp_units::codata
