// The MIT License (MIT)
//
// Copyright (c) 2018 Mateusz Pusz
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#pragma once

// This file is GENERATED by `scripts/codata_constants.py` from the NIST "allascii"
// tables checked in under `scripts/codata/`. Do not edit it manually; rerun the script.
//
// The CODATA 2022 adjustment (the current one, hence the `inline` namespace).
//
// This is the `essential` tier: the NIST "Frequently used constants" selection, kept in its
// own header because the complete table costs two orders of magnitude more to compile. The
// full <mp-units/systems/codata/codataYYYY.h> includes this header, so both spell the very
// same constant types and may be mixed freely.
// See <mp-units/systems/codata.h> for the full description of the system.

#include <mp-units/bits/module_macros.h>
#include <mp-units/systems/codata/adopted_values.h>
#include <mp-units/systems/si/constants.h>
#include <mp-units/systems/si/units.h>

#ifndef MP_UNITS_IN_MODULE_INTERFACE
#include <mp-units/framework/unit.h>
#endif

MP_UNITS_EXPORT
namespace mp_units::codata {

inline namespace codata2022 {

// clang-format off

// atomic mass constant: 1.660 539 068 92 e-27 kg, u = 0.000 000 000 52 e-27 kg
inline constexpr struct atomic_mass_constant final :
    named_constant<"m_u", mag_ratio<166'053'906'892, 100'000'000'000> * mag_power<10, -27> * si::kilogram, standard_uncertainty{mag_ratio<52, 10> * mag_power<10, -37> * si::kilogram}> {} atomic_mass_constant;

// Avogadro constant: 6.022 140 76 e23 mol^-1 (exact)
using si::si2019::avogadro_constant;

// Bohr magneton: 9.274 010 0657 e-24 J T^-1, u = 0.000 000 0029 e-24 J T^-1
inline constexpr struct bohr_magneton final :
    named_constant<symbol_text{u8"μ_B", "mu_B"}, mag_ratio<92'740'100'657, 10'000'000'000> * mag_power<10, -24> * si::joule / si::tesla, standard_uncertainty{mag_ratio<29, 10> * mag_power<10, -33> * si::joule / si::tesla}> {} bohr_magneton;

// Bohr radius: 5.291 772 105 44 e-11 m, u = 0.000 000 000 82 e-11 m
inline constexpr struct bohr_radius final :
    named_constant<"a_0", mag_ratio<529'177'210'544, 100'000'000'000> * mag_power<10, -11> * si::metre, standard_uncertainty{mag_ratio<82, 10> * mag_power<10, -21> * si::metre}> {} bohr_radius;

// Boltzmann constant: 1.380 649 e-23 J K^-1 (exact)
using si::si2019::boltzmann_constant;

// Compton wavelength: 2.426 310 235 38 e-12 m, u = 0.000 000 000 76 e-12 m
inline constexpr struct electron_compton_wavelength final :
    named_constant<symbol_text{u8"λ_C", "lambda_C"}, mag_ratio<242'631'023'538, 100'000'000'000> * mag_power<10, -12> * si::metre, standard_uncertainty{mag_ratio<76, 10> * mag_power<10, -22> * si::metre}> {} electron_compton_wavelength;

// electron mass: 9.109 383 7139 e-31 kg, u = 0.000 000 0028 e-31 kg
inline constexpr struct electron_mass final :
    named_constant<"m_e", mag_ratio<91'093'837'139, 10'000'000'000> * mag_power<10, -31> * si::kilogram, standard_uncertainty{mag_ratio<28, 10> * mag_power<10, -40> * si::kilogram}> {} electron_mass;

// elementary charge: 1.602 176 634 e-19 C (exact)
using si::si2019::elementary_charge;

// fine-structure constant: 7.297 352 5643 e-3, u = 0.000 000 0011 e-3
inline constexpr struct fine_structure_constant final :
    named_constant<symbol_text{u8"α", "alpha"}, mag_ratio<72'973'525'643, 10'000'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<11, 10> * mag_power<10, -12> * one}> {} fine_structure_constant;

// Hartree energy: 4.359 744 722 2060 e-18 J, u = 0.000 000 000 0048 e-18 J
inline constexpr struct hartree_energy final :
    named_constant<"E_h", mag_ratio<43'597'447'222'060, 10'000'000'000'000> * mag_power<10, -18> * si::joule, standard_uncertainty{mag_ratio<48, 10> * mag_power<10, -30> * si::joule}> {} hartree_energy;

// hyperfine transition frequency of Cs-133: 9 192 631 770 Hz (exact)
using si::si2019::hyperfine_structure_transition_frequency_of_cs;

// inverse fine-structure constant: 137.035 999 177, u = 0.000 000 021
inline constexpr struct inverse_fine_structure_constant final :
    named_constant<"inverse_fine_structure_constant", mag_ratio<137'035'999'177, 1'000'000'000> * one, standard_uncertainty{mag_ratio<21, 10> * mag_power<10, -8> * one}> {} inverse_fine_structure_constant;

// luminous efficacy: 683 lm W^-1 (exact)
using si::si2019::luminous_efficacy;

// muon mass: 1.883 531 627 e-28 kg, u = 0.000 000 042 e-28 kg
inline constexpr struct muon_mass final :
    named_constant<symbol_text{u8"m_μ", "m_mu"}, mag_ratio<1'883'531'627, 1'000'000'000> * mag_power<10, -28> * si::kilogram, standard_uncertainty{mag_ratio<42, 10> * mag_power<10, -36> * si::kilogram}> {} muon_mass;

// neutron mass: 1.674 927 500 56 e-27 kg, u = 0.000 000 000 85 e-27 kg
inline constexpr struct neutron_mass final :
    named_constant<"m_n", mag_ratio<167'492'750'056, 100'000'000'000> * mag_power<10, -27> * si::kilogram, standard_uncertainty{mag_ratio<85, 10> * mag_power<10, -37> * si::kilogram}> {} neutron_mass;

// Newtonian constant of gravitation: 6.674 30 e-11 m^3 kg^-1 s^-2, u = 0.000 15 e-11 m^3 kg^-1 s^-2
// Unchanged from the 2018 adjustment.
inline constexpr struct newtonian_constant_of_gravitation final :
    named_constant<"G", mag_ratio<667'430, 100'000> * mag_power<10, -11> * cubic(si::metre) / si::kilogram / square(si::second), standard_uncertainty{mag_ratio<15, 10> * mag_power<10, -15> * cubic(si::metre) / si::kilogram / square(si::second)}> {} newtonian_constant_of_gravitation;

// nuclear magneton: 5.050 783 7393 e-27 J T^-1, u = 0.000 000 0016 e-27 J T^-1
inline constexpr struct nuclear_magneton final :
    named_constant<symbol_text{u8"μ_N", "mu_N"}, mag_ratio<50'507'837'393, 10'000'000'000> * mag_power<10, -27> * si::joule / si::tesla, standard_uncertainty{mag_ratio<16, 10> * mag_power<10, -36> * si::joule / si::tesla}> {} nuclear_magneton;

// Planck constant: 6.626 070 15 e-34 J Hz^-1 (exact)
using si::si2019::planck_constant;

// proton-electron mass ratio: 1836.152 673 426, u = 0.000 000 032
inline constexpr struct proton_electron_mass_ratio final :
    named_constant<"proton_electron_mass_ratio", mag_ratio<1'836'152'673'426, 1'000'000'000> * one, standard_uncertainty{mag_ratio<32, 10> * mag_power<10, -8> * one}> {} proton_electron_mass_ratio;

// proton mass: 1.672 621 925 95 e-27 kg, u = 0.000 000 000 52 e-27 kg
inline constexpr struct proton_mass final :
    named_constant<"m_p", mag_ratio<167'262'192'595, 100'000'000'000> * mag_power<10, -27> * si::kilogram, standard_uncertainty{mag_ratio<52, 10> * mag_power<10, -37> * si::kilogram}> {} proton_mass;

// Rydberg constant: 10 973 731.568 157 m^-1, u = 0.000 012 m^-1
inline constexpr struct rydberg_constant final :
    named_constant<symbol_text{u8"R_∞", "R_inf"}, mag_ratio<10'973'731'568'157, 1'000'000> * one / si::metre, standard_uncertainty{mag_ratio<12, 10> * mag_power<10, -5> * one / si::metre}> {} rydberg_constant;

// speed of light in vacuum: 299 792 458 m s^-1 (exact)
using si::si2019::speed_of_light_in_vacuum;

// vacuum electric permittivity: 8.854 187 8188 e-12 F m^-1, u = 0.000 000 0014 e-12 F m^-1
inline constexpr struct vacuum_electric_permittivity final :
    named_constant<symbol_text{u8"ε₀", "eps_0"}, mag_ratio<88'541'878'188, 10'000'000'000> * mag_power<10, -12> * si::farad / si::metre, standard_uncertainty{mag_ratio<14, 10> * mag_power<10, -21> * si::farad / si::metre}> {} vacuum_electric_permittivity;

// vacuum mag. permeability: 1.256 637 061 27 e-6 N A^-2, u = 0.000 000 000 20 e-6 N A^-2
inline constexpr struct magnetic_constant final :
    named_constant<symbol_text{u8"μ₀", "u_0"}, mag_ratio<125'663'706'127, 100'000'000'000> * mag_power<10, -6> * si::newton / square(si::ampere), standard_uncertainty{mag_ratio<20, 10> * mag_power<10, -16> * si::newton / square(si::ampere)}> {} magnetic_constant;

// reduced Planck constant: 1.054 571 817... e-34 J s (exact)
inline constexpr struct reduced_planck_constant final :
    named_constant<symbol_text{u8"ℏ", "hbar"}, planck_constant / (mag<2> * π)> {} reduced_planck_constant;

// Josephson constant: 483 597.848 4... e9 Hz V^-1 (exact)
inline constexpr struct josephson_constant final :
    named_constant<"K_J", mag<2> * elementary_charge / planck_constant> {} josephson_constant;

// von Klitzing constant: 25 812.807 45... ohm (exact)
inline constexpr struct von_klitzing_constant final :
    named_constant<"R_K", planck_constant / square(elementary_charge)> {} von_klitzing_constant;

// conductance quantum: 7.748 091 729... e-5 S (exact)
inline constexpr struct conductance_quantum final :
    named_constant<"G_0", mag<2> * square(elementary_charge) / planck_constant> {} conductance_quantum;

// mag. flux quantum: 2.067 833 848... e-15 Wb (exact)
inline constexpr struct magnetic_flux_quantum final :
    named_constant<symbol_text{u8"Φ₀", "Phi_0"}, planck_constant / (mag<2> * elementary_charge)> {} magnetic_flux_quantum;

// Faraday constant: 96 485.332 12... C mol^-1 (exact)
inline constexpr struct faraday_constant final :
    named_constant<"F", avogadro_constant * elementary_charge> {} faraday_constant;

// molar gas constant: 8.314 462 618... J mol^-1 K^-1 (exact)
inline constexpr struct molar_gas_constant final :
    named_constant<"R", avogadro_constant * boltzmann_constant> {} molar_gas_constant;

// Stefan-Boltzmann constant: 5.670 374 419... e-8 W m^-2 K^-4 (exact)
inline constexpr struct stefan_boltzmann_constant final :
    named_constant<symbol_text{u8"σ", "sigma"}, mag_ratio<2, 15> * pow<5>(π) * pow<4>(boltzmann_constant) / cubic(planck_constant) / square(speed_of_light_in_vacuum)> {} stefan_boltzmann_constant;
// clang-format on

}  // namespace codata2022

}  // namespace mp_units::codata
