// The MIT License (MIT)
//
// Copyright (c) 2018 Mateusz Pusz
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#pragma once

// This file is GENERATED by `scripts/codata_constants.py` from the NIST "allascii"
// tables checked in under `scripts/codata/`. Do not edit it manually; rerun the script.
//
// The CODATA 2022 adjustment (the current one, hence the `inline` namespace).
// See <mp-units/systems/codata.h> for the full description of the system.

#include <mp-units/bits/module_macros.h>
#include <mp-units/systems/codata/codata2022_essential.h>
#include <mp-units/systems/codata/math_constants.h>
#include <mp-units/systems/si/constants.h>
#include <mp-units/systems/si/units.h>

#ifndef MP_UNITS_IN_MODULE_INTERFACE
#include <mp-units/framework/unit.h>
#endif

MP_UNITS_EXPORT
namespace mp_units::codata {

inline namespace codata2022 {

// clang-format off

// alpha particle-electron mass ratio: 7294.299 541 71, u = 0.000 000 17
inline constexpr struct alpha_particle_electron_mass_ratio final :
    named_constant<"alpha_particle_electron_mass_ratio", mag_ratio<729'429'954'171, 100'000'000> * one, standard_uncertainty{mag_ratio<17, 10> * mag_power<10, -7> * one}> {} alpha_particle_electron_mass_ratio;

// alpha particle mass: 6.644 657 3450 e-27 kg, u = 0.000 000 0021 e-27 kg
inline constexpr struct alpha_particle_mass final :
    named_constant<symbol_text{u8"m_α", "m_alpha"}, mag_ratio<66'446'573'450, 10'000'000'000> * mag_power<10, -27> * si::kilogram, standard_uncertainty{mag_ratio<21, 10> * mag_power<10, -36> * si::kilogram}> {} alpha_particle_mass;

// alpha particle molar mass: 4.001 506 1833 e-3 kg mol^-1, u = 0.000 000 0012 e-3 kg mol^-1
inline constexpr struct alpha_particle_molar_mass final :
    named_constant<"alpha_particle_molar_mass", mag_ratio<40'015'061'833, 10'000'000'000> * mag_power<10, -3> * si::kilogram / si::mole, standard_uncertainty{mag_ratio<12, 10> * mag_power<10, -12> * si::kilogram / si::mole}> {} alpha_particle_molar_mass;

// alpha particle-proton mass ratio: 3.972 599 690 252, u = 0.000 000 000 070
inline constexpr struct alpha_particle_proton_mass_ratio final :
    named_constant<"alpha_particle_proton_mass_ratio", mag_ratio<3'972'599'690'252, 1'000'000'000'000> * one, standard_uncertainty{mag_ratio<70, 10> * mag_power<10, -11> * one}> {} alpha_particle_proton_mass_ratio;

// alpha particle relative atomic mass: 4.001 506 179 129, u = 0.000 000 000 062
inline constexpr struct alpha_particle_relative_atomic_mass final :
    named_constant<"alpha_particle_relative_atomic_mass", mag_ratio<4'001'506'179'129, 1'000'000'000'000> * one, standard_uncertainty{mag_ratio<62, 10> * mag_power<10, -11> * one}> {} alpha_particle_relative_atomic_mass;

// alpha particle rms charge radius: 1.6785 e-15 m, u = 0.0021 e-15 m
inline constexpr struct alpha_particle_rms_charge_radius final :
    named_constant<"alpha_particle_rms_charge_radius", mag_ratio<16'785, 10'000> * mag_power<10, -15> * si::metre, standard_uncertainty{mag_ratio<21, 10> * mag_power<10, -18> * si::metre}> {} alpha_particle_rms_charge_radius;

// Angstrom star: 1.000 014 95 e-10 m, u = 0.000 000 90 e-10 m
inline constexpr struct angstrom_star final :
    named_constant<"angstrom_star", mag_ratio<100'001'495, 100'000'000> * mag_power<10, -10> * si::metre, standard_uncertainty{mag_ratio<90, 10> * mag_power<10, -17> * si::metre}> {} angstrom_star;

// atomic unit of 1st hyperpolarizability: 3.206 361 2996 e-53 C^3 m^3 J^-2, u = 0.000 000 0015 e-53 C^3 m^3 J^-2
inline constexpr struct atomic_unit_of_1st_hyperpolarizability final :
    named_constant<"atomic_unit_of_1st_hyperpolarizability", mag_ratio<32'063'612'996, 10'000'000'000> * mag_power<10, -53> * cubic(si::coulomb) * cubic(si::metre) / square(si::joule), standard_uncertainty{mag_ratio<15, 10> * mag_power<10, -62> * cubic(si::coulomb) * cubic(si::metre) / square(si::joule)}> {} atomic_unit_of_1st_hyperpolarizability;

// atomic unit of 2nd hyperpolarizability: 6.235 379 9735 e-65 C^4 m^4 J^-3, u = 0.000 000 0039 e-65 C^4 m^4 J^-3
inline constexpr struct atomic_unit_of_2nd_hyperpolarizability final :
    named_constant<"atomic_unit_of_2nd_hyperpolarizability", mag_ratio<62'353'799'735, 10'000'000'000> * mag_power<10, -65> * pow<4>(si::coulomb) * pow<4>(si::metre) / cubic(si::joule), standard_uncertainty{mag_ratio<39, 10> * mag_power<10, -74> * pow<4>(si::coulomb) * pow<4>(si::metre) / cubic(si::joule)}> {} atomic_unit_of_2nd_hyperpolarizability;

// atomic unit of charge density: 1.081 202 386 77 e12 C m^-3, u = 0.000 000 000 51 e12 C m^-3
inline constexpr struct atomic_unit_of_charge_density final :
    named_constant<"atomic_unit_of_charge_density", mag_ratio<108'120'238'677, 100'000'000'000> * mag_power<10, 12> * si::coulomb / cubic(si::metre), standard_uncertainty{mag_ratio<51, 10> * mag_power<10, 2> * si::coulomb / cubic(si::metre)}> {} atomic_unit_of_charge_density;

// atomic unit of current: 6.623 618 237 5082 e-3 A, u = 0.000 000 000 0072 e-3 A
inline constexpr struct atomic_unit_of_current final :
    named_constant<"atomic_unit_of_current", mag_ratio<66'236'182'375'082, 10'000'000'000'000> * mag_power<10, -3> * si::ampere, standard_uncertainty{mag_ratio<72, 10> * mag_power<10, -15> * si::ampere}> {} atomic_unit_of_current;

// atomic unit of electric dipole mom.: 8.478 353 6198 e-30 C m, u = 0.000 000 0013 e-30 C m
inline constexpr struct atomic_unit_of_electric_dipole_moment final :
    named_constant<"atomic_unit_of_electric_dipole_moment", mag_ratio<84'783'536'198, 10'000'000'000> * mag_power<10, -30> * si::coulomb * si::metre, standard_uncertainty{mag_ratio<13, 10> * mag_power<10, -39> * si::coulomb * si::metre}> {} atomic_unit_of_electric_dipole_moment;

// atomic unit of electric field: 5.142 206 751 12 e11 V m^-1, u = 0.000 000 000 80 e11 V m^-1
inline constexpr struct atomic_unit_of_electric_field final :
    named_constant<"atomic_unit_of_electric_field", mag_ratio<514'220'675'112, 100'000'000'000> * mag_power<10, 11> * si::volt / si::metre, standard_uncertainty{mag_ratio<80, 10> * mag_power<10, 1> * si::volt / si::metre}> {} atomic_unit_of_electric_field;

// atomic unit of electric field gradient: 9.717 362 4424 e21 V m^-2, u = 0.000 000 0030 e21 V m^-2
inline constexpr struct atomic_unit_of_electric_field_gradient final :
    named_constant<"atomic_unit_of_electric_field_gradient", mag_ratio<97'173'624'424, 10'000'000'000> * mag_power<10, 21> * si::volt / square(si::metre), standard_uncertainty{mag_ratio<30, 10> * mag_power<10, 12> * si::volt / square(si::metre)}> {} atomic_unit_of_electric_field_gradient;

// atomic unit of electric polarizability: 1.648 777 272 12 e-41 C^2 m^2 J^-1, u = 0.000 000 000 51 e-41 C^2 m^2 J^-1
inline constexpr struct atomic_unit_of_electric_polarizability final :
    named_constant<"atomic_unit_of_electric_polarizability", mag_ratio<164'877'727'212, 100'000'000'000> * mag_power<10, -41> * square(si::coulomb) * square(si::metre) / si::joule, standard_uncertainty{mag_ratio<51, 10> * mag_power<10, -51> * square(si::coulomb) * square(si::metre) / si::joule}> {} atomic_unit_of_electric_polarizability;

// atomic unit of electric potential: 27.211 386 245 981 V, u = 0.000 000 000 030 V
inline constexpr struct atomic_unit_of_electric_potential final :
    named_constant<"atomic_unit_of_electric_potential", mag_ratio<27'211'386'245'981, 1'000'000'000'000> * si::volt, standard_uncertainty{mag_ratio<30, 10> * mag_power<10, -11> * si::volt}> {} atomic_unit_of_electric_potential;

// atomic unit of electric quadrupole mom.: 4.486 551 5185 e-40 C m^2, u = 0.000 000 0014 e-40 C m^2
inline constexpr struct atomic_unit_of_electric_quadrupole_moment final :
    named_constant<"atomic_unit_of_electric_quadrupole_moment", mag_ratio<44'865'515'185, 10'000'000'000> * mag_power<10, -40> * si::coulomb * square(si::metre), standard_uncertainty{mag_ratio<14, 10> * mag_power<10, -49> * si::coulomb * square(si::metre)}> {} atomic_unit_of_electric_quadrupole_moment;

// atomic unit of force: 8.238 723 5038 e-8 N, u = 0.000 000 0013 e-8 N
inline constexpr struct atomic_unit_of_force final :
    named_constant<"atomic_unit_of_force", mag_ratio<82'387'235'038, 10'000'000'000> * mag_power<10, -8> * si::newton, standard_uncertainty{mag_ratio<13, 10> * mag_power<10, -17> * si::newton}> {} atomic_unit_of_force;

// atomic unit of mag. dipole mom.: 1.854 802 013 15 e-23 J T^-1, u = 0.000 000 000 58 e-23 J T^-1
inline constexpr struct atomic_unit_of_magnetic_dipole_moment final :
    named_constant<"atomic_unit_of_magnetic_dipole_moment", mag_ratio<185'480'201'315, 100'000'000'000> * mag_power<10, -23> * si::joule / si::tesla, standard_uncertainty{mag_ratio<58, 10> * mag_power<10, -33> * si::joule / si::tesla}> {} atomic_unit_of_magnetic_dipole_moment;

// atomic unit of mag. flux density: 2.350 517 570 77 e5 T, u = 0.000 000 000 73 e5 T
inline constexpr struct atomic_unit_of_magnetic_flux_density final :
    named_constant<"atomic_unit_of_magnetic_flux_density", mag_ratio<235'051'757'077, 100'000'000'000> * mag_power<10, 5> * si::tesla, standard_uncertainty{mag_ratio<73, 10> * mag_power<10, -5> * si::tesla}> {} atomic_unit_of_magnetic_flux_density;

// atomic unit of magnetizability: 7.891 036 5794 e-29 J T^-2, u = 0.000 000 0049 e-29 J T^-2
inline constexpr struct atomic_unit_of_magnetizability final :
    named_constant<"atomic_unit_of_magnetizability", mag_ratio<78'910'365'794, 10'000'000'000> * mag_power<10, -29> * si::joule / square(si::tesla), standard_uncertainty{mag_ratio<49, 10> * mag_power<10, -38> * si::joule / square(si::tesla)}> {} atomic_unit_of_magnetizability;

// atomic unit of momentum: 1.992 851 915 45 e-24 kg m s^-1, u = 0.000 000 000 31 e-24 kg m s^-1
inline constexpr struct atomic_unit_of_momentum final :
    named_constant<"atomic_unit_of_momentum", mag_ratio<199'285'191'545, 100'000'000'000> * mag_power<10, -24> * si::kilogram * si::metre / si::second, standard_uncertainty{mag_ratio<31, 10> * mag_power<10, -34> * si::kilogram * si::metre / si::second}> {} atomic_unit_of_momentum;

// atomic unit of permittivity: 1.112 650 056 20 e-10 F m^-1, u = 0.000 000 000 17 e-10 F m^-1
inline constexpr struct atomic_unit_of_permittivity final :
    named_constant<"atomic_unit_of_permittivity", mag_ratio<111'265'005'620, 100'000'000'000> * mag_power<10, -10> * si::farad / si::metre, standard_uncertainty{mag_ratio<17, 10> * mag_power<10, -20> * si::farad / si::metre}> {} atomic_unit_of_permittivity;

// atomic unit of time: 2.418 884 326 5864 e-17 s, u = 0.000 000 000 0026 e-17 s
inline constexpr struct atomic_unit_of_time final :
    named_constant<"atomic_unit_of_time", mag_ratio<24'188'843'265'864, 10'000'000'000'000> * mag_power<10, -17> * si::second, standard_uncertainty{mag_ratio<26, 10> * mag_power<10, -29> * si::second}> {} atomic_unit_of_time;

// atomic unit of velocity: 2.187 691 262 16 e6 m s^-1, u = 0.000 000 000 34 e6 m s^-1
inline constexpr struct atomic_unit_of_velocity final :
    named_constant<"atomic_unit_of_velocity", mag_ratio<218'769'126'216, 100'000'000'000> * mag_power<10, 6> * si::metre / si::second, standard_uncertainty{mag_ratio<34, 10> * mag_power<10, -4> * si::metre / si::second}> {} atomic_unit_of_velocity;

// characteristic impedance of vacuum: 376.730 313 412 ohm, u = 0.000 000 059 ohm
inline constexpr struct characteristic_impedance_of_vacuum final :
    named_constant<"Z_0", mag_ratio<376'730'313'412, 1'000'000'000> * si::ohm, standard_uncertainty{mag_ratio<59, 10> * mag_power<10, -8> * si::ohm}> {} characteristic_impedance_of_vacuum;

// classical electron radius: 2.817 940 3205 e-15 m, u = 0.000 000 0013 e-15 m
inline constexpr struct classical_electron_radius final :
    named_constant<"r_e", mag_ratio<28'179'403'205, 10'000'000'000> * mag_power<10, -15> * si::metre, standard_uncertainty{mag_ratio<13, 10> * mag_power<10, -24> * si::metre}> {} classical_electron_radius;

// Copper x unit: 1.002 076 97 e-13 m, u = 0.000 000 28 e-13 m
inline constexpr struct copper_x_unit final :
    named_constant<"copper_x_unit", mag_ratio<100'207'697, 100'000'000> * mag_power<10, -13> * si::metre, standard_uncertainty{mag_ratio<28, 10> * mag_power<10, -20> * si::metre}> {} copper_x_unit;

// deuteron-electron mag. mom. ratio: -4.664 345 550 e-4, u = 0.000 000 012 e-4
inline constexpr struct deuteron_electron_magnetic_moment_ratio final :
    named_constant<"deuteron_electron_magnetic_moment_ratio", -mag_ratio<4'664'345'550, 1'000'000'000> * mag_power<10, -4> * one, standard_uncertainty{mag_ratio<12, 10> * mag_power<10, -12> * one}> {} deuteron_electron_magnetic_moment_ratio;

// deuteron-electron mass ratio: 3670.482 967 655, u = 0.000 000 063
inline constexpr struct deuteron_electron_mass_ratio final :
    named_constant<"deuteron_electron_mass_ratio", mag_ratio<3'670'482'967'655, 1'000'000'000> * one, standard_uncertainty{mag_ratio<63, 10> * mag_power<10, -8> * one}> {} deuteron_electron_mass_ratio;

// deuteron g factor: 0.857 438 2335, u = 0.000 000 0022
inline constexpr struct deuteron_g_factor final :
    named_constant<"g_d", mag_ratio<8'574'382'335, 10'000'000'000> * one, standard_uncertainty{mag_ratio<22, 10> * mag_power<10, -9> * one}> {} deuteron_g_factor;

// deuteron mag. mom.: 4.330 735 087 e-27 J T^-1, u = 0.000 000 011 e-27 J T^-1
inline constexpr struct deuteron_magnetic_moment final :
    named_constant<symbol_text{u8"μ_d", "mu_d"}, mag_ratio<4'330'735'087, 1'000'000'000> * mag_power<10, -27> * si::joule / si::tesla, standard_uncertainty{mag_ratio<11, 10> * mag_power<10, -35> * si::joule / si::tesla}> {} deuteron_magnetic_moment;

// deuteron mag. mom. to Bohr magneton ratio: 4.669 754 568 e-4, u = 0.000 000 012 e-4
inline constexpr struct deuteron_magnetic_moment_to_bohr_magneton_ratio final :
    named_constant<"deuteron_magnetic_moment_to_bohr_magneton_ratio", mag_ratio<4'669'754'568, 1'000'000'000> * mag_power<10, -4> * one, standard_uncertainty{mag_ratio<12, 10> * mag_power<10, -12> * one}> {} deuteron_magnetic_moment_to_bohr_magneton_ratio;

// deuteron mag. mom. to nuclear magneton ratio: 0.857 438 2335, u = 0.000 000 0022
inline constexpr struct deuteron_magnetic_moment_to_nuclear_magneton_ratio final :
    named_constant<"deuteron_magnetic_moment_to_nuclear_magneton_ratio", mag_ratio<8'574'382'335, 10'000'000'000> * one, standard_uncertainty{mag_ratio<22, 10> * mag_power<10, -9> * one}> {} deuteron_magnetic_moment_to_nuclear_magneton_ratio;

// deuteron mass: 3.343 583 7768 e-27 kg, u = 0.000 000 0010 e-27 kg
inline constexpr struct deuteron_mass final :
    named_constant<"m_d", mag_ratio<33'435'837'768, 10'000'000'000> * mag_power<10, -27> * si::kilogram, standard_uncertainty{mag_ratio<10, 10> * mag_power<10, -36> * si::kilogram}> {} deuteron_mass;

// deuteron molar mass: 2.013 553 214 66 e-3 kg mol^-1, u = 0.000 000 000 63 e-3 kg mol^-1
inline constexpr struct deuteron_molar_mass final :
    named_constant<"deuteron_molar_mass", mag_ratio<201'355'321'466, 100'000'000'000> * mag_power<10, -3> * si::kilogram / si::mole, standard_uncertainty{mag_ratio<63, 10> * mag_power<10, -13> * si::kilogram / si::mole}> {} deuteron_molar_mass;

// deuteron-neutron mag. mom. ratio: -0.448 206 52, u = 0.000 000 11
inline constexpr struct deuteron_neutron_magnetic_moment_ratio final :
    named_constant<"deuteron_neutron_magnetic_moment_ratio", -mag_ratio<44'820'652, 100'000'000> * one, standard_uncertainty{mag_ratio<11, 10> * mag_power<10, -7> * one}> {} deuteron_neutron_magnetic_moment_ratio;

// deuteron-proton mag. mom. ratio: 0.307 012 209 30, u = 0.000 000 000 79
inline constexpr struct deuteron_proton_magnetic_moment_ratio final :
    named_constant<"deuteron_proton_magnetic_moment_ratio", mag_ratio<30'701'220'930, 100'000'000'000> * one, standard_uncertainty{mag_ratio<79, 10> * mag_power<10, -10> * one}> {} deuteron_proton_magnetic_moment_ratio;

// deuteron-proton mass ratio: 1.999 007 501 2699, u = 0.000 000 000 0084
inline constexpr struct deuteron_proton_mass_ratio final :
    named_constant<"deuteron_proton_mass_ratio", mag_ratio<19'990'075'012'699, 10'000'000'000'000> * one, standard_uncertainty{mag_ratio<84, 10> * mag_power<10, -12> * one}> {} deuteron_proton_mass_ratio;

// deuteron relative atomic mass: 2.013 553 212 544, u = 0.000 000 000 015
inline constexpr struct deuteron_relative_atomic_mass final :
    named_constant<"deuteron_relative_atomic_mass", mag_ratio<2'013'553'212'544, 1'000'000'000'000> * one, standard_uncertainty{mag_ratio<15, 10> * mag_power<10, -11> * one}> {} deuteron_relative_atomic_mass;

// deuteron rms charge radius: 2.127 78 e-15 m, u = 0.000 27 e-15 m
inline constexpr struct deuteron_rms_charge_radius final :
    named_constant<"r_d", mag_ratio<212'778, 100'000> * mag_power<10, -15> * si::metre, standard_uncertainty{mag_ratio<27, 10> * mag_power<10, -19> * si::metre}> {} deuteron_rms_charge_radius;

// electron charge to mass quotient: -1.758 820 008 38 e11 C kg^-1, u = 0.000 000 000 55 e11 C kg^-1
inline constexpr struct electron_charge_to_mass_quotient final :
    named_constant<"electron_charge_to_mass_quotient", -mag_ratio<175'882'000'838, 100'000'000'000> * mag_power<10, 11> * si::coulomb / si::kilogram, standard_uncertainty{mag_ratio<55, 10> * mag_power<10, 1> * si::coulomb / si::kilogram}> {} electron_charge_to_mass_quotient;

// electron-deuteron mag. mom. ratio: -2143.923 4921, u = 0.000 0056
inline constexpr struct electron_deuteron_magnetic_moment_ratio final :
    named_constant<"electron_deuteron_magnetic_moment_ratio", -mag_ratio<21'439'234'921, 10'000'000> * one, standard_uncertainty{mag_ratio<56, 10> * mag_power<10, -6> * one}> {} electron_deuteron_magnetic_moment_ratio;

// electron-deuteron mass ratio: 2.724 437 107 629 e-4, u = 0.000 000 000 047 e-4
inline constexpr struct electron_deuteron_mass_ratio final :
    named_constant<"electron_deuteron_mass_ratio", mag_ratio<2'724'437'107'629, 1'000'000'000'000> * mag_power<10, -4> * one, standard_uncertainty{mag_ratio<47, 10> * mag_power<10, -15> * one}> {} electron_deuteron_mass_ratio;

// electron g factor: -2.002 319 304 360 92, u = 0.000 000 000 000 36
inline constexpr struct electron_g_factor final :
    named_constant<"g_e", -mag_ratio<200'231'930'436'092, 100'000'000'000'000> * one, standard_uncertainty{mag_ratio<36, 10> * mag_power<10, -13> * one}> {} electron_g_factor;

// electron gyromag. ratio: 1.760 859 627 84 e11 s^-1 T^-1, u = 0.000 000 000 55 e11 s^-1 T^-1
inline constexpr struct electron_gyromagnetic_ratio final :
    named_constant<symbol_text{u8"γ_e", "gamma_e"}, mag_ratio<176'085'962'784, 100'000'000'000> * mag_power<10, 11> * one / si::second / si::tesla, standard_uncertainty{mag_ratio<55, 10> * mag_power<10, 1> * one / si::second / si::tesla}> {} electron_gyromagnetic_ratio;

// electron-helion mass ratio: 1.819 543 074 649 e-4, u = 0.000 000 000 053 e-4
inline constexpr struct electron_helion_mass_ratio final :
    named_constant<"electron_helion_mass_ratio", mag_ratio<1'819'543'074'649, 1'000'000'000'000> * mag_power<10, -4> * one, standard_uncertainty{mag_ratio<53, 10> * mag_power<10, -15> * one}> {} electron_helion_mass_ratio;

// electron mag. mom.: -9.284 764 6917 e-24 J T^-1, u = 0.000 000 0029 e-24 J T^-1
inline constexpr struct electron_magnetic_moment final :
    named_constant<symbol_text{u8"μ_e", "mu_e"}, -mag_ratio<92'847'646'917, 10'000'000'000> * mag_power<10, -24> * si::joule / si::tesla, standard_uncertainty{mag_ratio<29, 10> * mag_power<10, -33> * si::joule / si::tesla}> {} electron_magnetic_moment;

// electron mag. mom. anomaly: 1.159 652 180 46 e-3, u = 0.000 000 000 18 e-3
inline constexpr struct electron_magnetic_moment_anomaly final :
    named_constant<"electron_magnetic_moment_anomaly", mag_ratio<115'965'218'046, 100'000'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<18, 10> * mag_power<10, -13> * one}> {} electron_magnetic_moment_anomaly;

// electron mag. mom. to Bohr magneton ratio: -1.001 159 652 180 46, u = 0.000 000 000 000 18
inline constexpr struct electron_magnetic_moment_to_bohr_magneton_ratio final :
    named_constant<"electron_magnetic_moment_to_bohr_magneton_ratio", -mag_ratio<100'115'965'218'046, 100'000'000'000'000> * one, standard_uncertainty{mag_ratio<18, 10> * mag_power<10, -13> * one}> {} electron_magnetic_moment_to_bohr_magneton_ratio;

// electron mag. mom. to nuclear magneton ratio: -1838.281 971 877, u = 0.000 000 032
inline constexpr struct electron_magnetic_moment_to_nuclear_magneton_ratio final :
    named_constant<"electron_magnetic_moment_to_nuclear_magneton_ratio", -mag_ratio<1'838'281'971'877, 1'000'000'000> * one, standard_uncertainty{mag_ratio<32, 10> * mag_power<10, -8> * one}> {} electron_magnetic_moment_to_nuclear_magneton_ratio;

// electron molar mass: 5.485 799 0962 e-7 kg mol^-1, u = 0.000 000 0017 e-7 kg mol^-1
inline constexpr struct electron_molar_mass final :
    named_constant<"electron_molar_mass", mag_ratio<54'857'990'962, 10'000'000'000> * mag_power<10, -7> * si::kilogram / si::mole, standard_uncertainty{mag_ratio<17, 10> * mag_power<10, -16> * si::kilogram / si::mole}> {} electron_molar_mass;

// electron-muon mag. mom. ratio: 206.766 9881, u = 0.000 0046
inline constexpr struct electron_muon_magnetic_moment_ratio final :
    named_constant<"electron_muon_magnetic_moment_ratio", mag_ratio<2'067'669'881, 10'000'000> * one, standard_uncertainty{mag_ratio<46, 10> * mag_power<10, -6> * one}> {} electron_muon_magnetic_moment_ratio;

// electron-muon mass ratio: 4.836 331 70 e-3, u = 0.000 000 11 e-3
inline constexpr struct electron_muon_mass_ratio final :
    named_constant<"electron_muon_mass_ratio", mag_ratio<483'633'170, 100'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<11, 10> * mag_power<10, -10> * one}> {} electron_muon_mass_ratio;

// electron-neutron mag. mom. ratio: 960.920 48, u = 0.000 23
inline constexpr struct electron_neutron_magnetic_moment_ratio final :
    named_constant<"electron_neutron_magnetic_moment_ratio", mag_ratio<96'092'048, 100'000> * one, standard_uncertainty{mag_ratio<23, 10> * mag_power<10, -4> * one}> {} electron_neutron_magnetic_moment_ratio;

// electron-neutron mass ratio: 5.438 673 4416 e-4, u = 0.000 000 0022 e-4
inline constexpr struct electron_neutron_mass_ratio final :
    named_constant<"electron_neutron_mass_ratio", mag_ratio<54'386'734'416, 10'000'000'000> * mag_power<10, -4> * one, standard_uncertainty{mag_ratio<22, 10> * mag_power<10, -13> * one}> {} electron_neutron_mass_ratio;

// electron-proton mag. mom. ratio: -658.210 687 89, u = 0.000 000 19
inline constexpr struct electron_proton_magnetic_moment_ratio final :
    named_constant<"electron_proton_magnetic_moment_ratio", -mag_ratio<65'821'068'789, 100'000'000> * one, standard_uncertainty{mag_ratio<19, 10> * mag_power<10, -7> * one}> {} electron_proton_magnetic_moment_ratio;

// electron-proton mass ratio: 5.446 170 214 889 e-4, u = 0.000 000 000 094 e-4
inline constexpr struct electron_proton_mass_ratio final :
    named_constant<"electron_proton_mass_ratio", mag_ratio<5'446'170'214'889, 1'000'000'000'000> * mag_power<10, -4> * one, standard_uncertainty{mag_ratio<94, 10> * mag_power<10, -15> * one}> {} electron_proton_mass_ratio;

// electron relative atomic mass: 5.485 799 090 441 e-4, u = 0.000 000 000 097 e-4
inline constexpr struct electron_relative_atomic_mass final :
    named_constant<"electron_relative_atomic_mass", mag_ratio<5'485'799'090'441, 1'000'000'000'000> * mag_power<10, -4> * one, standard_uncertainty{mag_ratio<97, 10> * mag_power<10, -15> * one}> {} electron_relative_atomic_mass;

// electron-tau mass ratio: 2.875 85 e-4, u = 0.000 19 e-4
inline constexpr struct electron_tau_mass_ratio final :
    named_constant<"electron_tau_mass_ratio", mag_ratio<287'585, 100'000> * mag_power<10, -4> * one, standard_uncertainty{mag_ratio<19, 10> * mag_power<10, -8> * one}> {} electron_tau_mass_ratio;

// electron to alpha particle mass ratio: 1.370 933 554 733 e-4, u = 0.000 000 000 032 e-4
inline constexpr struct electron_to_alpha_particle_mass_ratio final :
    named_constant<"electron_to_alpha_particle_mass_ratio", mag_ratio<1'370'933'554'733, 1'000'000'000'000> * mag_power<10, -4> * one, standard_uncertainty{mag_ratio<32, 10> * mag_power<10, -15> * one}> {} electron_to_alpha_particle_mass_ratio;

// electron to shielded helion mag. mom. ratio: 864.058 239 86, u = 0.000 000 70
inline constexpr struct electron_to_shielded_helion_magnetic_moment_ratio final :
    named_constant<"electron_to_shielded_helion_magnetic_moment_ratio", mag_ratio<86'405'823'986, 100'000'000> * one, standard_uncertainty{mag_ratio<70, 10> * mag_power<10, -7> * one}> {} electron_to_shielded_helion_magnetic_moment_ratio;

// electron to shielded proton mag. mom. ratio: -658.227 5856, u = 0.000 0027
inline constexpr struct electron_to_shielded_proton_magnetic_moment_ratio final :
    named_constant<"electron_to_shielded_proton_magnetic_moment_ratio", -mag_ratio<6'582'275'856, 10'000'000> * one, standard_uncertainty{mag_ratio<27, 10> * mag_power<10, -6> * one}> {} electron_to_shielded_proton_magnetic_moment_ratio;

// electron-triton mass ratio: 1.819 200 062 327 e-4, u = 0.000 000 000 068 e-4
inline constexpr struct electron_triton_mass_ratio final :
    named_constant<"electron_triton_mass_ratio", mag_ratio<1'819'200'062'327, 1'000'000'000'000> * mag_power<10, -4> * one, standard_uncertainty{mag_ratio<68, 10> * mag_power<10, -15> * one}> {} electron_triton_mass_ratio;

// Fermi coupling constant: 1.166 3787 e-5 GeV^-2, u = 0.000 0006 e-5 GeV^-2
inline constexpr struct fermi_coupling_constant final :
    named_constant<"fermi_coupling_constant", mag_ratio<11'663'787, 10'000'000> * mag_power<10, -5> * one / square(si::giga<si::electronvolt>), standard_uncertainty{mag<6> * mag_power<10, -12> * one / square(si::giga<si::electronvolt>)}> {} fermi_coupling_constant;

// helion-electron mass ratio: 5495.885 279 84, u = 0.000 000 16
inline constexpr struct helion_electron_mass_ratio final :
    named_constant<"helion_electron_mass_ratio", mag_ratio<549'588'527'984, 100'000'000> * one, standard_uncertainty{mag_ratio<16, 10> * mag_power<10, -7> * one}> {} helion_electron_mass_ratio;

// helion g factor: -4.255 250 6995, u = 0.000 000 0034
inline constexpr struct helion_g_factor final :
    named_constant<"g_h", -mag_ratio<42'552'506'995, 10'000'000'000> * one, standard_uncertainty{mag_ratio<34, 10> * mag_power<10, -9> * one}> {} helion_g_factor;

// helion mag. mom.: -1.074 617 551 98 e-26 J T^-1, u = 0.000 000 000 93 e-26 J T^-1
inline constexpr struct helion_magnetic_moment final :
    named_constant<"helion_magnetic_moment", -mag_ratio<107'461'755'198, 100'000'000'000> * mag_power<10, -26> * si::joule / si::tesla, standard_uncertainty{mag_ratio<93, 10> * mag_power<10, -36> * si::joule / si::tesla}> {} helion_magnetic_moment;

// helion mag. mom. to Bohr magneton ratio: -1.158 740 980 83 e-3, u = 0.000 000 000 94 e-3
inline constexpr struct helion_magnetic_moment_to_bohr_magneton_ratio final :
    named_constant<"helion_magnetic_moment_to_bohr_magneton_ratio", -mag_ratio<115'874'098'083, 100'000'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<94, 10> * mag_power<10, -13> * one}> {} helion_magnetic_moment_to_bohr_magneton_ratio;

// helion mag. mom. to nuclear magneton ratio: -2.127 625 3498, u = 0.000 000 0017
inline constexpr struct helion_magnetic_moment_to_nuclear_magneton_ratio final :
    named_constant<"helion_magnetic_moment_to_nuclear_magneton_ratio", -mag_ratio<21'276'253'498, 10'000'000'000> * one, standard_uncertainty{mag_ratio<17, 10> * mag_power<10, -9> * one}> {} helion_magnetic_moment_to_nuclear_magneton_ratio;

// helion mass: 5.006 412 7862 e-27 kg, u = 0.000 000 0016 e-27 kg
inline constexpr struct helion_mass final :
    named_constant<"m_h", mag_ratio<50'064'127'862, 10'000'000'000> * mag_power<10, -27> * si::kilogram, standard_uncertainty{mag_ratio<16, 10> * mag_power<10, -36> * si::kilogram}> {} helion_mass;

// helion molar mass: 3.014 932 250 10 e-3 kg mol^-1, u = 0.000 000 000 94 e-3 kg mol^-1
inline constexpr struct helion_molar_mass final :
    named_constant<"helion_molar_mass", mag_ratio<301'493'225'010, 100'000'000'000> * mag_power<10, -3> * si::kilogram / si::mole, standard_uncertainty{mag_ratio<94, 10> * mag_power<10, -13> * si::kilogram / si::mole}> {} helion_molar_mass;

// helion-proton mass ratio: 2.993 152 671 552, u = 0.000 000 000 070
inline constexpr struct helion_proton_mass_ratio final :
    named_constant<"helion_proton_mass_ratio", mag_ratio<2'993'152'671'552, 1'000'000'000'000> * one, standard_uncertainty{mag_ratio<70, 10> * mag_power<10, -11> * one}> {} helion_proton_mass_ratio;

// helion relative atomic mass: 3.014 932 246 932, u = 0.000 000 000 074
inline constexpr struct helion_relative_atomic_mass final :
    named_constant<"helion_relative_atomic_mass", mag_ratio<3'014'932'246'932, 1'000'000'000'000> * one, standard_uncertainty{mag_ratio<74, 10> * mag_power<10, -11> * one}> {} helion_relative_atomic_mass;

// helion shielding shift: 5.996 7029 e-5, u = 0.000 0023 e-5
inline constexpr struct helion_shielding_shift final :
    named_constant<"helion_shielding_shift", mag_ratio<59'967'029, 10'000'000> * mag_power<10, -5> * one, standard_uncertainty{mag_ratio<23, 10> * mag_power<10, -11> * one}> {} helion_shielding_shift;

// lattice parameter of silicon: 5.431 020 511 e-10 m, u = 0.000 000 089 e-10 m
inline constexpr struct lattice_parameter_of_silicon final :
    named_constant<"lattice_parameter_of_silicon", mag_ratio<5'431'020'511, 1'000'000'000> * mag_power<10, -10> * si::metre, standard_uncertainty{mag_ratio<89, 10> * mag_power<10, -18> * si::metre}> {} lattice_parameter_of_silicon;

// lattice spacing of ideal Si (220): 1.920 155 716 e-10 m, u = 0.000 000 032 e-10 m
inline constexpr struct lattice_spacing_of_silicon_220 final :
    named_constant<"lattice_spacing_of_silicon_220", mag_ratio<1'920'155'716, 1'000'000'000> * mag_power<10, -10> * si::metre, standard_uncertainty{mag_ratio<32, 10> * mag_power<10, -18> * si::metre}> {} lattice_spacing_of_silicon_220;

// molar mass constant: 1.000 000 001 05 e-3 kg mol^-1, u = 0.000 000 000 31 e-3 kg mol^-1
inline constexpr struct molar_mass_constant final :
    named_constant<"M_u", mag_ratio<100'000'000'105, 100'000'000'000> * mag_power<10, -3> * si::kilogram / si::mole, standard_uncertainty{mag_ratio<31, 10> * mag_power<10, -13> * si::kilogram / si::mole}> {} molar_mass_constant;

// molar mass of carbon-12: 12.000 000 0126 e-3 kg mol^-1, u = 0.000 000 0037 e-3 kg mol^-1
inline constexpr struct molar_mass_of_carbon_12 final :
    named_constant<"molar_mass_of_carbon_12", mag_ratio<120'000'000'126, 10'000'000'000> * mag_power<10, -3> * si::kilogram / si::mole, standard_uncertainty{mag_ratio<37, 10> * mag_power<10, -12> * si::kilogram / si::mole}> {} molar_mass_of_carbon_12;

// molar volume of silicon: 1.205 883 199 e-5 m^3 mol^-1, u = 0.000 000 060 e-5 m^3 mol^-1
inline constexpr struct molar_volume_of_silicon final :
    named_constant<"molar_volume_of_silicon", mag_ratio<1'205'883'199, 1'000'000'000> * mag_power<10, -5> * cubic(si::metre) / si::mole, standard_uncertainty{mag_ratio<60, 10> * mag_power<10, -13> * cubic(si::metre) / si::mole}> {} molar_volume_of_silicon;

// Molybdenum x unit: 1.002 099 52 e-13 m, u = 0.000 000 53 e-13 m
inline constexpr struct molybdenum_x_unit final :
    named_constant<"molybdenum_x_unit", mag_ratio<100'209'952, 100'000'000> * mag_power<10, -13> * si::metre, standard_uncertainty{mag_ratio<53, 10> * mag_power<10, -20> * si::metre}> {} molybdenum_x_unit;

// muon Compton wavelength: 1.173 444 110 e-14 m, u = 0.000 000 026 e-14 m
inline constexpr struct muon_compton_wavelength final :
    named_constant<"muon_compton_wavelength", mag_ratio<1'173'444'110, 1'000'000'000> * mag_power<10, -14> * si::metre, standard_uncertainty{mag_ratio<26, 10> * mag_power<10, -22> * si::metre}> {} muon_compton_wavelength;

// muon-electron mass ratio: 206.768 2827, u = 0.000 0046
inline constexpr struct muon_electron_mass_ratio final :
    named_constant<"muon_electron_mass_ratio", mag_ratio<2'067'682'827, 10'000'000> * one, standard_uncertainty{mag_ratio<46, 10> * mag_power<10, -6> * one}> {} muon_electron_mass_ratio;

// muon g factor: -2.002 331 841 23, u = 0.000 000 000 82
inline constexpr struct muon_g_factor final :
    named_constant<symbol_text{u8"g_μ", "g_mu"}, -mag_ratio<200'233'184'123, 100'000'000'000> * one, standard_uncertainty{mag_ratio<82, 10> * mag_power<10, -10> * one}> {} muon_g_factor;

// muon mag. mom.: -4.490 448 30 e-26 J T^-1, u = 0.000 000 10 e-26 J T^-1
inline constexpr struct muon_magnetic_moment final :
    named_constant<symbol_text{u8"μ_μ", "mu_mu"}, -mag_ratio<449'044'830, 100'000'000> * mag_power<10, -26> * si::joule / si::tesla, standard_uncertainty{mag_ratio<10, 10> * mag_power<10, -33> * si::joule / si::tesla}> {} muon_magnetic_moment;

// muon mag. mom. anomaly: 1.165 920 62 e-3, u = 0.000 000 41 e-3
inline constexpr struct muon_magnetic_moment_anomaly final :
    named_constant<"muon_magnetic_moment_anomaly", mag_ratio<116'592'062, 100'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<41, 10> * mag_power<10, -10> * one}> {} muon_magnetic_moment_anomaly;

// muon mag. mom. to Bohr magneton ratio: -4.841 970 48 e-3, u = 0.000 000 11 e-3
inline constexpr struct muon_magnetic_moment_to_bohr_magneton_ratio final :
    named_constant<"muon_magnetic_moment_to_bohr_magneton_ratio", -mag_ratio<484'197'048, 100'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<11, 10> * mag_power<10, -10> * one}> {} muon_magnetic_moment_to_bohr_magneton_ratio;

// muon mag. mom. to nuclear magneton ratio: -8.890 597 04, u = 0.000 000 20
inline constexpr struct muon_magnetic_moment_to_nuclear_magneton_ratio final :
    named_constant<"muon_magnetic_moment_to_nuclear_magneton_ratio", -mag_ratio<889'059'704, 100'000'000> * one, standard_uncertainty{mag_ratio<20, 10> * mag_power<10, -7> * one}> {} muon_magnetic_moment_to_nuclear_magneton_ratio;

// muon molar mass: 1.134 289 258 e-4 kg mol^-1, u = 0.000 000 025 e-4 kg mol^-1
inline constexpr struct muon_molar_mass final :
    named_constant<"muon_molar_mass", mag_ratio<1'134'289'258, 1'000'000'000> * mag_power<10, -4> * si::kilogram / si::mole, standard_uncertainty{mag_ratio<25, 10> * mag_power<10, -12> * si::kilogram / si::mole}> {} muon_molar_mass;

// muon-neutron mass ratio: 0.112 454 5168, u = 0.000 000 0025
inline constexpr struct muon_neutron_mass_ratio final :
    named_constant<"muon_neutron_mass_ratio", mag_ratio<1'124'545'168, 10'000'000'000> * one, standard_uncertainty{mag_ratio<25, 10> * mag_power<10, -9> * one}> {} muon_neutron_mass_ratio;

// muon-proton mag. mom. ratio: -3.183 345 146, u = 0.000 000 071
inline constexpr struct muon_proton_magnetic_moment_ratio final :
    named_constant<"muon_proton_magnetic_moment_ratio", -mag_ratio<3'183'345'146, 1'000'000'000> * one, standard_uncertainty{mag_ratio<71, 10> * mag_power<10, -8> * one}> {} muon_proton_magnetic_moment_ratio;

// muon-proton mass ratio: 0.112 609 5262, u = 0.000 000 0025
inline constexpr struct muon_proton_mass_ratio final :
    named_constant<"muon_proton_mass_ratio", mag_ratio<1'126'095'262, 10'000'000'000> * one, standard_uncertainty{mag_ratio<25, 10> * mag_power<10, -9> * one}> {} muon_proton_mass_ratio;

// muon-tau mass ratio: 5.946 35 e-2, u = 0.000 40 e-2
inline constexpr struct muon_tau_mass_ratio final :
    named_constant<"muon_tau_mass_ratio", mag_ratio<594'635, 100'000> * mag_power<10, -2> * one, standard_uncertainty{mag_ratio<40, 10> * mag_power<10, -6> * one}> {} muon_tau_mass_ratio;

// natural unit of energy: 8.187 105 7880 e-14 J, u = 0.000 000 0026 e-14 J
inline constexpr struct natural_unit_of_energy final :
    named_constant<"natural_unit_of_energy", mag_ratio<81'871'057'880, 10'000'000'000> * mag_power<10, -14> * si::joule, standard_uncertainty{mag_ratio<26, 10> * mag_power<10, -23> * si::joule}> {} natural_unit_of_energy;

// natural unit of momentum: 2.730 924 534 46 e-22 kg m s^-1, u = 0.000 000 000 85 e-22 kg m s^-1
inline constexpr struct natural_unit_of_momentum final :
    named_constant<"natural_unit_of_momentum", mag_ratio<273'092'453'446, 100'000'000'000> * mag_power<10, -22> * si::kilogram * si::metre / si::second, standard_uncertainty{mag_ratio<85, 10> * mag_power<10, -32> * si::kilogram * si::metre / si::second}> {} natural_unit_of_momentum;

// natural unit of time: 1.288 088 666 44 e-21 s, u = 0.000 000 000 40 e-21 s
inline constexpr struct natural_unit_of_time final :
    named_constant<"natural_unit_of_time", mag_ratio<128'808'866'644, 100'000'000'000> * mag_power<10, -21> * si::second, standard_uncertainty{mag_ratio<40, 10> * mag_power<10, -31> * si::second}> {} natural_unit_of_time;

// neutron Compton wavelength: 1.319 590 903 82 e-15 m, u = 0.000 000 000 67 e-15 m
inline constexpr struct neutron_compton_wavelength final :
    named_constant<"neutron_compton_wavelength", mag_ratio<131'959'090'382, 100'000'000'000> * mag_power<10, -15> * si::metre, standard_uncertainty{mag_ratio<67, 10> * mag_power<10, -25> * si::metre}> {} neutron_compton_wavelength;

// neutron-electron mag. mom. ratio: 1.040 668 84 e-3, u = 0.000 000 24 e-3
inline constexpr struct neutron_electron_magnetic_moment_ratio final :
    named_constant<"neutron_electron_magnetic_moment_ratio", mag_ratio<104'066'884, 100'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<24, 10> * mag_power<10, -10> * one}> {} neutron_electron_magnetic_moment_ratio;

// neutron-electron mass ratio: 1838.683 662 00, u = 0.000 000 74
inline constexpr struct neutron_electron_mass_ratio final :
    named_constant<"neutron_electron_mass_ratio", mag_ratio<183'868'366'200, 100'000'000> * one, standard_uncertainty{mag_ratio<74, 10> * mag_power<10, -7> * one}> {} neutron_electron_mass_ratio;

// neutron g factor: -3.826 085 52, u = 0.000 000 90
inline constexpr struct neutron_g_factor final :
    named_constant<"g_n", -mag_ratio<382'608'552, 100'000'000> * one, standard_uncertainty{mag_ratio<90, 10> * mag_power<10, -7> * one}> {} neutron_g_factor;

// neutron gyromag. ratio: 1.832 471 74 e8 s^-1 T^-1, u = 0.000 000 43 e8 s^-1 T^-1
inline constexpr struct neutron_gyromagnetic_ratio final :
    named_constant<symbol_text{u8"γ_n", "gamma_n"}, mag_ratio<183'247'174, 100'000'000> * mag_power<10, 8> * one / si::second / si::tesla, standard_uncertainty{mag_ratio<43, 10> * mag_power<10, 1> * one / si::second / si::tesla}> {} neutron_gyromagnetic_ratio;

// neutron mag. mom.: -9.662 3653 e-27 J T^-1, u = 0.000 0023 e-27 J T^-1
inline constexpr struct neutron_magnetic_moment final :
    named_constant<symbol_text{u8"μ_n", "mu_n"}, -mag_ratio<96'623'653, 10'000'000> * mag_power<10, -27> * si::joule / si::tesla, standard_uncertainty{mag_ratio<23, 10> * mag_power<10, -33> * si::joule / si::tesla}> {} neutron_magnetic_moment;

// neutron mag. mom. to Bohr magneton ratio: -1.041 875 65 e-3, u = 0.000 000 25 e-3
inline constexpr struct neutron_magnetic_moment_to_bohr_magneton_ratio final :
    named_constant<"neutron_magnetic_moment_to_bohr_magneton_ratio", -mag_ratio<104'187'565, 100'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<25, 10> * mag_power<10, -10> * one}> {} neutron_magnetic_moment_to_bohr_magneton_ratio;

// neutron mag. mom. to nuclear magneton ratio: -1.913 042 76, u = 0.000 000 45
inline constexpr struct neutron_magnetic_moment_to_nuclear_magneton_ratio final :
    named_constant<"neutron_magnetic_moment_to_nuclear_magneton_ratio", -mag_ratio<191'304'276, 100'000'000> * one, standard_uncertainty{mag_ratio<45, 10> * mag_power<10, -7> * one}> {} neutron_magnetic_moment_to_nuclear_magneton_ratio;

// neutron molar mass: 1.008 664 917 12 e-3 kg mol^-1, u = 0.000 000 000 51 e-3 kg mol^-1
inline constexpr struct neutron_molar_mass final :
    named_constant<"neutron_molar_mass", mag_ratio<100'866'491'712, 100'000'000'000> * mag_power<10, -3> * si::kilogram / si::mole, standard_uncertainty{mag_ratio<51, 10> * mag_power<10, -13> * si::kilogram / si::mole}> {} neutron_molar_mass;

// neutron-muon mass ratio: 8.892 484 08, u = 0.000 000 20
inline constexpr struct neutron_muon_mass_ratio final :
    named_constant<"neutron_muon_mass_ratio", mag_ratio<889'248'408, 100'000'000> * one, standard_uncertainty{mag_ratio<20, 10> * mag_power<10, -7> * one}> {} neutron_muon_mass_ratio;

// neutron-proton mag. mom. ratio: -0.684 979 35, u = 0.000 000 16
inline constexpr struct neutron_proton_magnetic_moment_ratio final :
    named_constant<"neutron_proton_magnetic_moment_ratio", -mag_ratio<68'497'935, 100'000'000> * one, standard_uncertainty{mag_ratio<16, 10> * mag_power<10, -7> * one}> {} neutron_proton_magnetic_moment_ratio;

// neutron-proton mass difference: 2.305 574 61 e-30 kg, u = 0.000 000 67 e-30 kg
inline constexpr struct neutron_proton_mass_difference final :
    named_constant<"neutron_proton_mass_difference", mag_ratio<230'557'461, 100'000'000> * mag_power<10, -30> * si::kilogram, standard_uncertainty{mag_ratio<67, 10> * mag_power<10, -37> * si::kilogram}> {} neutron_proton_mass_difference;

// neutron-proton mass ratio: 1.001 378 419 46, u = 0.000 000 000 40
inline constexpr struct neutron_proton_mass_ratio final :
    named_constant<"neutron_proton_mass_ratio", mag_ratio<100'137'841'946, 100'000'000'000> * one, standard_uncertainty{mag_ratio<40, 10> * mag_power<10, -10> * one}> {} neutron_proton_mass_ratio;

// neutron relative atomic mass: 1.008 664 916 06, u = 0.000 000 000 40
inline constexpr struct neutron_relative_atomic_mass final :
    named_constant<"neutron_relative_atomic_mass", mag_ratio<100'866'491'606, 100'000'000'000> * one, standard_uncertainty{mag_ratio<40, 10> * mag_power<10, -10> * one}> {} neutron_relative_atomic_mass;

// neutron-tau mass ratio: 0.528 779, u = 0.000 036
inline constexpr struct neutron_tau_mass_ratio final :
    named_constant<"neutron_tau_mass_ratio", mag_ratio<528'779, 1'000'000> * one, standard_uncertainty{mag_ratio<36, 10> * mag_power<10, -5> * one}> {} neutron_tau_mass_ratio;

// neutron to shielded proton mag. mom. ratio: -0.684 996 94, u = 0.000 000 16
inline constexpr struct neutron_to_shielded_proton_magnetic_moment_ratio final :
    named_constant<"neutron_to_shielded_proton_magnetic_moment_ratio", -mag_ratio<68'499'694, 100'000'000> * one, standard_uncertainty{mag_ratio<16, 10> * mag_power<10, -7> * one}> {} neutron_to_shielded_proton_magnetic_moment_ratio;

// Planck length: 1.616 255 e-35 m, u = 0.000 018 e-35 m
inline constexpr struct planck_length final :
    named_constant<"l_P", mag_ratio<1'616'255, 1'000'000> * mag_power<10, -35> * si::metre, standard_uncertainty{mag_ratio<18, 10> * mag_power<10, -40> * si::metre}> {} planck_length;

// Planck mass: 2.176 434 e-8 kg, u = 0.000 024 e-8 kg
inline constexpr struct planck_mass final :
    named_constant<"m_P", mag_ratio<2'176'434, 1'000'000> * mag_power<10, -8> * si::kilogram, standard_uncertainty{mag_ratio<24, 10> * mag_power<10, -13> * si::kilogram}> {} planck_mass;

// Planck temperature: 1.416 784 e32 K, u = 0.000 016 e32 K
inline constexpr struct planck_temperature final :
    named_constant<"T_P", mag_ratio<1'416'784, 1'000'000> * mag_power<10, 32> * si::kelvin, standard_uncertainty{mag_ratio<16, 10> * mag_power<10, 27> * si::kelvin}> {} planck_temperature;

// Planck time: 5.391 247 e-44 s, u = 0.000 060 e-44 s
inline constexpr struct planck_time final :
    named_constant<"t_P", mag_ratio<5'391'247, 1'000'000> * mag_power<10, -44> * si::second, standard_uncertainty{mag_ratio<60, 10> * mag_power<10, -49> * si::second}> {} planck_time;

// proton charge to mass quotient: 9.578 833 1430 e7 C kg^-1, u = 0.000 000 0030 e7 C kg^-1
inline constexpr struct proton_charge_to_mass_quotient final :
    named_constant<"proton_charge_to_mass_quotient", mag_ratio<95'788'331'430, 10'000'000'000> * mag_power<10, 7> * si::coulomb / si::kilogram, standard_uncertainty{mag_ratio<30, 10> * mag_power<10, -2> * si::coulomb / si::kilogram}> {} proton_charge_to_mass_quotient;

// proton Compton wavelength: 1.321 409 853 60 e-15 m, u = 0.000 000 000 41 e-15 m
inline constexpr struct proton_compton_wavelength final :
    named_constant<"proton_compton_wavelength", mag_ratio<132'140'985'360, 100'000'000'000> * mag_power<10, -15> * si::metre, standard_uncertainty{mag_ratio<41, 10> * mag_power<10, -25> * si::metre}> {} proton_compton_wavelength;

// proton g factor: 5.585 694 6893, u = 0.000 000 0016
inline constexpr struct proton_g_factor final :
    named_constant<"g_p", mag_ratio<55'856'946'893, 10'000'000'000> * one, standard_uncertainty{mag_ratio<16, 10> * mag_power<10, -9> * one}> {} proton_g_factor;

// proton gyromag. ratio: 2.675 221 8708 e8 s^-1 T^-1, u = 0.000 000 0011 e8 s^-1 T^-1
inline constexpr struct proton_gyromagnetic_ratio final :
    named_constant<symbol_text{u8"γ_p", "gamma_p"}, mag_ratio<26'752'218'708, 10'000'000'000> * mag_power<10, 8> * one / si::second / si::tesla, standard_uncertainty{mag_ratio<11, 10> * mag_power<10, -1> * one / si::second / si::tesla}> {} proton_gyromagnetic_ratio;

// proton mag. mom.: 1.410 606 795 45 e-26 J T^-1, u = 0.000 000 000 60 e-26 J T^-1
inline constexpr struct proton_magnetic_moment final :
    named_constant<symbol_text{u8"μ_p", "mu_p"}, mag_ratio<141'060'679'545, 100'000'000'000> * mag_power<10, -26> * si::joule / si::tesla, standard_uncertainty{mag_ratio<60, 10> * mag_power<10, -36> * si::joule / si::tesla}> {} proton_magnetic_moment;

// proton mag. mom. to Bohr magneton ratio: 1.521 032 202 30 e-3, u = 0.000 000 000 45 e-3
inline constexpr struct proton_magnetic_moment_to_bohr_magneton_ratio final :
    named_constant<"proton_magnetic_moment_to_bohr_magneton_ratio", mag_ratio<152'103'220'230, 100'000'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<45, 10> * mag_power<10, -13> * one}> {} proton_magnetic_moment_to_bohr_magneton_ratio;

// proton mag. mom. to nuclear magneton ratio: 2.792 847 344 63, u = 0.000 000 000 82
inline constexpr struct proton_magnetic_moment_to_nuclear_magneton_ratio final :
    named_constant<"proton_magnetic_moment_to_nuclear_magneton_ratio", mag_ratio<279'284'734'463, 100'000'000'000> * one, standard_uncertainty{mag_ratio<82, 10> * mag_power<10, -10> * one}> {} proton_magnetic_moment_to_nuclear_magneton_ratio;

// proton mag. shielding correction: 2.567 15 e-5, u = 0.000 41 e-5
inline constexpr struct proton_magnetic_shielding_correction final :
    named_constant<"proton_magnetic_shielding_correction", mag_ratio<256'715, 100'000> * mag_power<10, -5> * one, standard_uncertainty{mag_ratio<41, 10> * mag_power<10, -9> * one}> {} proton_magnetic_shielding_correction;

// proton molar mass: 1.007 276 467 64 e-3 kg mol^-1, u = 0.000 000 000 31 e-3 kg mol^-1
inline constexpr struct proton_molar_mass final :
    named_constant<"proton_molar_mass", mag_ratio<100'727'646'764, 100'000'000'000> * mag_power<10, -3> * si::kilogram / si::mole, standard_uncertainty{mag_ratio<31, 10> * mag_power<10, -13> * si::kilogram / si::mole}> {} proton_molar_mass;

// proton-muon mass ratio: 8.880 243 38, u = 0.000 000 20
inline constexpr struct proton_muon_mass_ratio final :
    named_constant<"proton_muon_mass_ratio", mag_ratio<888'024'338, 100'000'000> * one, standard_uncertainty{mag_ratio<20, 10> * mag_power<10, -7> * one}> {} proton_muon_mass_ratio;

// proton-neutron mag. mom. ratio: -1.459 898 02, u = 0.000 000 34
inline constexpr struct proton_neutron_magnetic_moment_ratio final :
    named_constant<"proton_neutron_magnetic_moment_ratio", -mag_ratio<145'989'802, 100'000'000> * one, standard_uncertainty{mag_ratio<34, 10> * mag_power<10, -7> * one}> {} proton_neutron_magnetic_moment_ratio;

// proton-neutron mass ratio: 0.998 623 477 97, u = 0.000 000 000 40
inline constexpr struct proton_neutron_mass_ratio final :
    named_constant<"proton_neutron_mass_ratio", mag_ratio<99'862'347'797, 100'000'000'000> * one, standard_uncertainty{mag_ratio<40, 10> * mag_power<10, -10> * one}> {} proton_neutron_mass_ratio;

// proton relative atomic mass: 1.007 276 466 5789, u = 0.000 000 000 0083
inline constexpr struct proton_relative_atomic_mass final :
    named_constant<"proton_relative_atomic_mass", mag_ratio<10'072'764'665'789, 10'000'000'000'000> * one, standard_uncertainty{mag_ratio<83, 10> * mag_power<10, -12> * one}> {} proton_relative_atomic_mass;

// proton rms charge radius: 8.4075 e-16 m, u = 0.0064 e-16 m
inline constexpr struct proton_rms_charge_radius final :
    named_constant<"r_p", mag_ratio<84'075, 10'000> * mag_power<10, -16> * si::metre, standard_uncertainty{mag_ratio<64, 10> * mag_power<10, -19> * si::metre}> {} proton_rms_charge_radius;

// proton-tau mass ratio: 0.528 051, u = 0.000 036
inline constexpr struct proton_tau_mass_ratio final :
    named_constant<"proton_tau_mass_ratio", mag_ratio<528'051, 1'000'000> * one, standard_uncertainty{mag_ratio<36, 10> * mag_power<10, -5> * one}> {} proton_tau_mass_ratio;

// quantum of circulation: 3.636 947 5467 e-4 m^2 s^-1, u = 0.000 000 0011 e-4 m^2 s^-1
inline constexpr struct quantum_of_circulation final :
    named_constant<"quantum_of_circulation", mag_ratio<36'369'475'467, 10'000'000'000> * mag_power<10, -4> * square(si::metre) / si::second, standard_uncertainty{mag_ratio<11, 10> * mag_power<10, -13> * square(si::metre) / si::second}> {} quantum_of_circulation;

// quantum of circulation times 2: 7.273 895 0934 e-4 m^2 s^-1, u = 0.000 000 0023 e-4 m^2 s^-1
inline constexpr struct quantum_of_circulation_times_2 final :
    named_constant<"quantum_of_circulation_times_2", mag_ratio<72'738'950'934, 10'000'000'000> * mag_power<10, -4> * square(si::metre) / si::second, standard_uncertainty{mag_ratio<23, 10> * mag_power<10, -13> * square(si::metre) / si::second}> {} quantum_of_circulation_times_2;

// reduced Compton wavelength: 3.861 592 6744 e-13 m, u = 0.000 000 0012 e-13 m
inline constexpr struct reduced_electron_compton_wavelength final :
    named_constant<symbol_text{u8"ƛ_C", "lambdabar_C"}, mag_ratio<38'615'926'744, 10'000'000'000> * mag_power<10, -13> * si::metre, standard_uncertainty{mag_ratio<12, 10> * mag_power<10, -22> * si::metre}> {} reduced_electron_compton_wavelength;

// reduced muon Compton wavelength: 1.867 594 306 e-15 m, u = 0.000 000 042 e-15 m
inline constexpr struct reduced_muon_compton_wavelength final :
    named_constant<"reduced_muon_compton_wavelength", mag_ratio<1'867'594'306, 1'000'000'000> * mag_power<10, -15> * si::metre, standard_uncertainty{mag_ratio<42, 10> * mag_power<10, -23> * si::metre}> {} reduced_muon_compton_wavelength;

// reduced neutron Compton wavelength: 2.100 194 1520 e-16 m, u = 0.000 000 0011 e-16 m
inline constexpr struct reduced_neutron_compton_wavelength final :
    named_constant<"reduced_neutron_compton_wavelength", mag_ratio<21'001'941'520, 10'000'000'000> * mag_power<10, -16> * si::metre, standard_uncertainty{mag_ratio<11, 10> * mag_power<10, -25> * si::metre}> {} reduced_neutron_compton_wavelength;

// reduced proton Compton wavelength: 2.103 089 100 51 e-16 m, u = 0.000 000 000 66 e-16 m
inline constexpr struct reduced_proton_compton_wavelength final :
    named_constant<"reduced_proton_compton_wavelength", mag_ratio<210'308'910'051, 100'000'000'000> * mag_power<10, -16> * si::metre, standard_uncertainty{mag_ratio<66, 10> * mag_power<10, -26> * si::metre}> {} reduced_proton_compton_wavelength;

// reduced tau Compton wavelength: 1.110 538 e-16 m, u = 0.000 075 e-16 m
inline constexpr struct reduced_tau_compton_wavelength final :
    named_constant<"reduced_tau_compton_wavelength", mag_ratio<1'110'538, 1'000'000> * mag_power<10, -16> * si::metre, standard_uncertainty{mag_ratio<75, 10> * mag_power<10, -21> * si::metre}> {} reduced_tau_compton_wavelength;

// Sackur-Tetrode constant (1 K, 100 kPa): -1.151 707 534 96, u = 0.000 000 000 47
inline constexpr struct sackur_tetrode_constant_100_kpa final :
    named_constant<"sackur_tetrode_constant_100_kpa", -mag_ratio<115'170'753'496, 100'000'000'000> * one, standard_uncertainty{mag_ratio<47, 10> * mag_power<10, -10> * one}> {} sackur_tetrode_constant_100_kpa;

// Sackur-Tetrode constant (1 K, 101.325 kPa): -1.164 870 521 49, u = 0.000 000 000 47
inline constexpr struct sackur_tetrode_constant_101_325_kpa final :
    named_constant<"sackur_tetrode_constant_101_325_kpa", -mag_ratio<116'487'052'149, 100'000'000'000> * one, standard_uncertainty{mag_ratio<47, 10> * mag_power<10, -10> * one}> {} sackur_tetrode_constant_101_325_kpa;

// shielded helion gyromag. ratio: 2.037 894 6078 e8 s^-1 T^-1, u = 0.000 000 0018 e8 s^-1 T^-1
inline constexpr struct shielded_helion_gyromagnetic_ratio final :
    named_constant<"shielded_helion_gyromagnetic_ratio", mag_ratio<20'378'946'078, 10'000'000'000> * mag_power<10, 8> * one / si::second / si::tesla, standard_uncertainty{mag_ratio<18, 10> * mag_power<10, -1> * one / si::second / si::tesla}> {} shielded_helion_gyromagnetic_ratio;

// shielded helion mag. mom.: -1.074 553 110 35 e-26 J T^-1, u = 0.000 000 000 93 e-26 J T^-1
inline constexpr struct shielded_helion_magnetic_moment final :
    named_constant<"shielded_helion_magnetic_moment", -mag_ratio<107'455'311'035, 100'000'000'000> * mag_power<10, -26> * si::joule / si::tesla, standard_uncertainty{mag_ratio<93, 10> * mag_power<10, -36> * si::joule / si::tesla}> {} shielded_helion_magnetic_moment;

// shielded helion mag. mom. to Bohr magneton ratio: -1.158 671 494 57 e-3, u = 0.000 000 000 94 e-3
inline constexpr struct shielded_helion_magnetic_moment_to_bohr_magneton_ratio final :
    named_constant<"shielded_helion_magnetic_moment_to_bohr_magneton_ratio", -mag_ratio<115'867'149'457, 100'000'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<94, 10> * mag_power<10, -13> * one}> {} shielded_helion_magnetic_moment_to_bohr_magneton_ratio;

// shielded helion mag. mom. to nuclear magneton ratio: -2.127 497 7624, u = 0.000 000 0017
inline constexpr struct shielded_helion_magnetic_moment_to_nuclear_magneton_ratio final :
    named_constant<"shielded_helion_magnetic_moment_to_nuclear_magneton_ratio", -mag_ratio<21'274'977'624, 10'000'000'000> * one, standard_uncertainty{mag_ratio<17, 10> * mag_power<10, -9> * one}> {} shielded_helion_magnetic_moment_to_nuclear_magneton_ratio;

// shielded helion to proton mag. mom. ratio: -0.761 766 577 21, u = 0.000 000 000 66
inline constexpr struct shielded_helion_to_proton_magnetic_moment_ratio final :
    named_constant<"shielded_helion_to_proton_magnetic_moment_ratio", -mag_ratio<76'176'657'721, 100'000'000'000> * one, standard_uncertainty{mag_ratio<66, 10> * mag_power<10, -10> * one}> {} shielded_helion_to_proton_magnetic_moment_ratio;

// shielded helion to shielded proton mag. mom. ratio: -0.761 786 1334, u = 0.000 000 0031
inline constexpr struct shielded_helion_to_shielded_proton_magnetic_moment_ratio final :
    named_constant<"shielded_helion_to_shielded_proton_magnetic_moment_ratio", -mag_ratio<7'617'861'334, 10'000'000'000> * one, standard_uncertainty{mag_ratio<31, 10> * mag_power<10, -9> * one}> {} shielded_helion_to_shielded_proton_magnetic_moment_ratio;

// shielded proton gyromag. ratio: 2.675 153 194 e8 s^-1 T^-1, u = 0.000 000 011 e8 s^-1 T^-1
inline constexpr struct shielded_proton_gyromagnetic_ratio final :
    named_constant<"shielded_proton_gyromagnetic_ratio", mag_ratio<2'675'153'194, 1'000'000'000> * mag_power<10, 8> * one / si::second / si::tesla, standard_uncertainty{mag_ratio<11, 10> * one / si::second / si::tesla}> {} shielded_proton_gyromagnetic_ratio;

// shielded proton mag. mom.: 1.410 570 5830 e-26 J T^-1, u = 0.000 000 0058 e-26 J T^-1
inline constexpr struct shielded_proton_magnetic_moment final :
    named_constant<"shielded_proton_magnetic_moment", mag_ratio<14'105'705'830, 10'000'000'000> * mag_power<10, -26> * si::joule / si::tesla, standard_uncertainty{mag_ratio<58, 10> * mag_power<10, -35> * si::joule / si::tesla}> {} shielded_proton_magnetic_moment;

// shielded proton mag. mom. to Bohr magneton ratio: 1.520 993 1551 e-3, u = 0.000 000 0062 e-3
inline constexpr struct shielded_proton_magnetic_moment_to_bohr_magneton_ratio final :
    named_constant<"shielded_proton_magnetic_moment_to_bohr_magneton_ratio", mag_ratio<15'209'931'551, 10'000'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<62, 10> * mag_power<10, -12> * one}> {} shielded_proton_magnetic_moment_to_bohr_magneton_ratio;

// shielded proton mag. mom. to nuclear magneton ratio: 2.792 775 648, u = 0.000 000 011
inline constexpr struct shielded_proton_magnetic_moment_to_nuclear_magneton_ratio final :
    named_constant<"shielded_proton_magnetic_moment_to_nuclear_magneton_ratio", mag_ratio<2'792'775'648, 1'000'000'000> * one, standard_uncertainty{mag_ratio<11, 10> * mag_power<10, -8> * one}> {} shielded_proton_magnetic_moment_to_nuclear_magneton_ratio;

// shielding difference of d and p in HD: 1.987 70 e-8, u = 0.000 10 e-8
inline constexpr struct shielding_difference_of_d_and_p_in_hd final :
    named_constant<"shielding_difference_of_d_and_p_in_hd", mag_ratio<198'770, 100'000> * mag_power<10, -8> * one, standard_uncertainty{mag_ratio<10, 10> * mag_power<10, -12> * one}> {} shielding_difference_of_d_and_p_in_hd;

// shielding difference of t and p in HT: 2.394 50 e-8, u = 0.000 20 e-8
inline constexpr struct shielding_difference_of_t_and_p_in_ht final :
    named_constant<"shielding_difference_of_t_and_p_in_ht", mag_ratio<239'450, 100'000> * mag_power<10, -8> * one, standard_uncertainty{mag_ratio<20, 10> * mag_power<10, -12> * one}> {} shielding_difference_of_t_and_p_in_ht;

// tau Compton wavelength: 6.977 71 e-16 m, u = 0.000 47 e-16 m
inline constexpr struct tau_compton_wavelength final :
    named_constant<"tau_compton_wavelength", mag_ratio<697'771, 100'000> * mag_power<10, -16> * si::metre, standard_uncertainty{mag_ratio<47, 10> * mag_power<10, -20> * si::metre}> {} tau_compton_wavelength;

// tau-electron mass ratio: 3477.23, u = 0.23
inline constexpr struct tau_electron_mass_ratio final :
    named_constant<"tau_electron_mass_ratio", mag_ratio<347'723, 100> * one, standard_uncertainty{mag_ratio<23, 10> * mag_power<10, -1> * one}> {} tau_electron_mass_ratio;

// tau mass: 3.167 54 e-27 kg, u = 0.000 21 e-27 kg
inline constexpr struct tau_mass final :
    named_constant<symbol_text{u8"m_τ", "m_tau"}, mag_ratio<316'754, 100'000> * mag_power<10, -27> * si::kilogram, standard_uncertainty{mag_ratio<21, 10> * mag_power<10, -31> * si::kilogram}> {} tau_mass;

// tau molar mass: 1.907 54 e-3 kg mol^-1, u = 0.000 13 e-3 kg mol^-1
inline constexpr struct tau_molar_mass final :
    named_constant<"tau_molar_mass", mag_ratio<190'754, 100'000> * mag_power<10, -3> * si::kilogram / si::mole, standard_uncertainty{mag_ratio<13, 10> * mag_power<10, -7> * si::kilogram / si::mole}> {} tau_molar_mass;

// tau-muon mass ratio: 16.8170, u = 0.0011
inline constexpr struct tau_muon_mass_ratio final :
    named_constant<"tau_muon_mass_ratio", mag_ratio<168'170, 10'000> * one, standard_uncertainty{mag_ratio<11, 10> * mag_power<10, -3> * one}> {} tau_muon_mass_ratio;

// tau-neutron mass ratio: 1.891 15, u = 0.000 13
inline constexpr struct tau_neutron_mass_ratio final :
    named_constant<"tau_neutron_mass_ratio", mag_ratio<189'115, 100'000> * one, standard_uncertainty{mag_ratio<13, 10> * mag_power<10, -4> * one}> {} tau_neutron_mass_ratio;

// tau-proton mass ratio: 1.893 76, u = 0.000 13
inline constexpr struct tau_proton_mass_ratio final :
    named_constant<"tau_proton_mass_ratio", mag_ratio<189'376, 100'000> * one, standard_uncertainty{mag_ratio<13, 10> * mag_power<10, -4> * one}> {} tau_proton_mass_ratio;

// Thomson cross section: 6.652 458 7051 e-29 m^2, u = 0.000 000 0062 e-29 m^2
inline constexpr struct thomson_cross_section final :
    named_constant<symbol_text{u8"σ_e", "sigma_e"}, mag_ratio<66'524'587'051, 10'000'000'000> * mag_power<10, -29> * square(si::metre), standard_uncertainty{mag_ratio<62, 10> * mag_power<10, -38> * square(si::metre)}> {} thomson_cross_section;

// triton-electron mass ratio: 5496.921 535 51, u = 0.000 000 21
inline constexpr struct triton_electron_mass_ratio final :
    named_constant<"triton_electron_mass_ratio", mag_ratio<549'692'153'551, 100'000'000> * one, standard_uncertainty{mag_ratio<21, 10> * mag_power<10, -7> * one}> {} triton_electron_mass_ratio;

// triton g factor: 5.957 924 930, u = 0.000 000 012
inline constexpr struct triton_g_factor final :
    named_constant<"g_t", mag_ratio<5'957'924'930, 1'000'000'000> * one, standard_uncertainty{mag_ratio<12, 10> * mag_power<10, -8> * one}> {} triton_g_factor;

// triton mag. mom.: 1.504 609 5178 e-26 J T^-1, u = 0.000 000 0030 e-26 J T^-1
inline constexpr struct triton_magnetic_moment final :
    named_constant<symbol_text{u8"μ_t", "mu_t"}, mag_ratio<15'046'095'178, 10'000'000'000> * mag_power<10, -26> * si::joule / si::tesla, standard_uncertainty{mag_ratio<30, 10> * mag_power<10, -35> * si::joule / si::tesla}> {} triton_magnetic_moment;

// triton mag. mom. to Bohr magneton ratio: 1.622 393 6648 e-3, u = 0.000 000 0032 e-3
inline constexpr struct triton_magnetic_moment_to_bohr_magneton_ratio final :
    named_constant<"triton_magnetic_moment_to_bohr_magneton_ratio", mag_ratio<16'223'936'648, 10'000'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<32, 10> * mag_power<10, -12> * one}> {} triton_magnetic_moment_to_bohr_magneton_ratio;

// triton mag. mom. to nuclear magneton ratio: 2.978 962 4650, u = 0.000 000 0059
inline constexpr struct triton_magnetic_moment_to_nuclear_magneton_ratio final :
    named_constant<"triton_magnetic_moment_to_nuclear_magneton_ratio", mag_ratio<29'789'624'650, 10'000'000'000> * one, standard_uncertainty{mag_ratio<59, 10> * mag_power<10, -9> * one}> {} triton_magnetic_moment_to_nuclear_magneton_ratio;

// triton mass: 5.007 356 7512 e-27 kg, u = 0.000 000 0016 e-27 kg
inline constexpr struct triton_mass final :
    named_constant<"m_t", mag_ratio<50'073'567'512, 10'000'000'000> * mag_power<10, -27> * si::kilogram, standard_uncertainty{mag_ratio<16, 10> * mag_power<10, -36> * si::kilogram}> {} triton_mass;

// triton molar mass: 3.015 500 719 13 e-3 kg mol^-1, u = 0.000 000 000 94 e-3 kg mol^-1
inline constexpr struct triton_molar_mass final :
    named_constant<"triton_molar_mass", mag_ratio<301'550'071'913, 100'000'000'000> * mag_power<10, -3> * si::kilogram / si::mole, standard_uncertainty{mag_ratio<94, 10> * mag_power<10, -13> * si::kilogram / si::mole}> {} triton_molar_mass;

// triton-proton mass ratio: 2.993 717 034 03, u = 0.000 000 000 10
inline constexpr struct triton_proton_mass_ratio final :
    named_constant<"triton_proton_mass_ratio", mag_ratio<299'371'703'403, 100'000'000'000> * one, standard_uncertainty{mag_ratio<10, 10> * mag_power<10, -10> * one}> {} triton_proton_mass_ratio;

// triton relative atomic mass: 3.015 500 715 97, u = 0.000 000 000 10
inline constexpr struct triton_relative_atomic_mass final :
    named_constant<"triton_relative_atomic_mass", mag_ratio<301'550'071'597, 100'000'000'000> * one, standard_uncertainty{mag_ratio<10, 10> * mag_power<10, -10> * one}> {} triton_relative_atomic_mass;

// triton to proton mag. mom. ratio: 1.066 639 9189, u = 0.000 000 0021
inline constexpr struct triton_to_proton_magnetic_moment_ratio final :
    named_constant<"triton_to_proton_magnetic_moment_ratio", mag_ratio<10'666'399'189, 10'000'000'000> * one, standard_uncertainty{mag_ratio<21, 10> * mag_power<10, -9> * one}> {} triton_to_proton_magnetic_moment_ratio;

// weak mixing angle: 0.223 05, u = 0.000 23
inline constexpr struct weak_mixing_angle final :
    named_constant<"weak_mixing_angle", mag_ratio<22'305, 100'000> * one, standard_uncertainty{mag_ratio<23, 10> * mag_power<10, -4> * one}> {} weak_mixing_angle;

// W to Z mass ratio: 0.881 45, u = 0.000 13
inline constexpr struct w_to_z_mass_ratio final :
    named_constant<"w_to_z_mass_ratio", mag_ratio<88'145, 100'000> * one, standard_uncertainty{mag_ratio<13, 10> * mag_power<10, -4> * one}> {} w_to_z_mass_ratio;

// elementary charge over h-bar: 1.519 267 447... e15 A J^-1 (exact)
inline constexpr struct elementary_charge_over_h_bar final :
    named_constant<"elementary_charge_over_h_bar", elementary_charge / reduced_planck_constant> {} elementary_charge_over_h_bar;

// inverse of conductance quantum: 12 906.403 72... ohm (exact)
inline constexpr struct inverse_of_conductance_quantum final :
    named_constant<"inverse_of_conductance_quantum", planck_constant / (mag<2> * square(elementary_charge))> {} inverse_of_conductance_quantum;

// molar Planck constant: 3.990 312 712... e-10 J Hz^-1 mol^-1 (exact)
inline constexpr struct molar_planck_constant final :
    named_constant<"N_Ah", avogadro_constant * planck_constant> {} molar_planck_constant;

// first radiation constant: 3.741 771 852... e-16 W m^2 (exact)
inline constexpr struct first_radiation_constant final :
    named_constant<"c_1", mag<2> * π * planck_constant * square(speed_of_light_in_vacuum)> {} first_radiation_constant;

// first radiation constant for spectral radiance: 1.191 042 972... e-16 W m^2 sr^-1 (exact)
inline constexpr struct first_radiation_constant_for_spectral_radiance final :
    named_constant<"c_1L", mag<2> * planck_constant * square(speed_of_light_in_vacuum) / si::steradian> {} first_radiation_constant_for_spectral_radiance;

// second radiation constant: 1.438 776 877... e-2 m K (exact)
inline constexpr struct second_radiation_constant final :
    named_constant<"c_2", planck_constant * speed_of_light_in_vacuum / boltzmann_constant> {} second_radiation_constant;

// Wien wavelength displacement law constant: 2.897 771 955... e-3 m K (exact)
// b = c₂ / x, where x solves the transcendental equation x = 5 (1 - e^-x); see `wien_x_wavelength` above.
inline constexpr struct wien_wavelength_displacement_law_constant final :
    named_constant<"b", second_radiation_constant / wien_x_wavelength> {} wien_wavelength_displacement_law_constant;

// Wien frequency displacement law constant: 5.878 925 757... e10 Hz K^-1 (exact)
// b' = x k / h, where x solves the transcendental equation x = 3 (1 - e^-x); see `wien_x_frequency` above.
inline constexpr struct wien_frequency_displacement_law_constant final :
    named_constant<symbol_text{u8"b′", "b_prime"}, wien_x_frequency * boltzmann_constant / planck_constant> {} wien_frequency_displacement_law_constant;

// Loschmidt constant (273.15 K, 100 kPa): 2.651 645 804... e25 m^-3 (exact)
inline constexpr struct loschmidt_constant_stp final :
    named_constant<"n_0", mag_ratio<10'000'000, 27'315> * si::pascal / boltzmann_constant / si::kelvin> {} loschmidt_constant_stp;

// Loschmidt constant (273.15 K, 101.325 kPa): 2.686 780 111... e25 m^-3 (exact)
inline constexpr struct loschmidt_constant_atm final :
    named_constant<"loschmidt_constant_atm", mag_ratio<10'132'500, 27'315> * si::pascal / boltzmann_constant / si::kelvin> {} loschmidt_constant_atm;

// molar volume of ideal gas (273.15 K, 100 kPa): 22.710 954 64... e-3 m^3 mol^-1 (exact)
inline constexpr struct molar_volume_of_ideal_gas_stp final :
    named_constant<"molar_volume_of_ideal_gas_stp", mag_ratio<27'315, 10'000'000> * avogadro_constant * boltzmann_constant * si::kelvin / si::pascal> {} molar_volume_of_ideal_gas_stp;

// molar volume of ideal gas (273.15 K, 101.325 kPa): 22.413 969 54... e-3 m^3 mol^-1 (exact)
inline constexpr struct molar_volume_of_ideal_gas_atm final :
    named_constant<"molar_volume_of_ideal_gas_atm", mag_ratio<27'315, 10'132'500> * avogadro_constant * boltzmann_constant * si::kelvin / si::pascal> {} molar_volume_of_ideal_gas_atm;

// conventional value of ampere-90: 1.000 000 088 87... A (exact)
// A_90 = V_90 / Ω_90 = (K_J-90/K_J) (R_K-90/R_K) A.
inline constexpr struct conventional_value_of_ampere_90 final :
    named_constant<"conventional_value_of_ampere_90", conventional_value_of_josephson_constant / josephson_constant * conventional_value_of_von_klitzing_constant / von_klitzing_constant * si::ampere> {} conventional_value_of_ampere_90;

// conventional value of coulomb-90: 1.000 000 088 87... C (exact)
inline constexpr struct conventional_value_of_coulomb_90 final :
    named_constant<"conventional_value_of_coulomb_90", conventional_value_of_josephson_constant / josephson_constant * conventional_value_of_von_klitzing_constant / von_klitzing_constant * si::coulomb> {} conventional_value_of_coulomb_90;

// conventional value of farad-90: 0.999 999 982 20... F (exact)
inline constexpr struct conventional_value_of_farad_90 final :
    named_constant<"conventional_value_of_farad_90", conventional_value_of_von_klitzing_constant / von_klitzing_constant * si::farad> {} conventional_value_of_farad_90;

// conventional value of henry-90: 1.000 000 017 79... H (exact)
inline constexpr struct conventional_value_of_henry_90 final :
    named_constant<"conventional_value_of_henry_90", von_klitzing_constant / conventional_value_of_von_klitzing_constant * si::henry> {} conventional_value_of_henry_90;

// conventional value of ohm-90: 1.000 000 017 79... ohm (exact)
inline constexpr struct conventional_value_of_ohm_90 final :
    named_constant<"conventional_value_of_ohm_90", von_klitzing_constant / conventional_value_of_von_klitzing_constant * si::ohm> {} conventional_value_of_ohm_90;

// conventional value of volt-90: 1.000 000 106 66... V (exact)
inline constexpr struct conventional_value_of_volt_90 final :
    named_constant<"conventional_value_of_volt_90", conventional_value_of_josephson_constant / josephson_constant * si::volt> {} conventional_value_of_volt_90;

// conventional value of watt-90: 1.000 000 195 53... W (exact)
// W_90 = V_90 A_90 = (K_J-90/K_J)² (R_K-90/R_K) W.
inline constexpr struct conventional_value_of_watt_90 final :
    named_constant<"conventional_value_of_watt_90", square(conventional_value_of_josephson_constant / josephson_constant) * conventional_value_of_von_klitzing_constant / von_klitzing_constant * si::watt> {} conventional_value_of_watt_90;

// atomic unit of action: 1.054 571 817... e-34 J s (exact)
inline constexpr auto atomic_unit_of_action = reduced_planck_constant;

// atomic unit of charge: 1.602 176 634 e-19 C (exact)
inline constexpr auto atomic_unit_of_charge = elementary_charge;

// atomic unit of energy: 4.359 744 722 2060 e-18 J, u = 0.000 000 000 0048 e-18 J
inline constexpr auto atomic_unit_of_energy = hartree_energy;

// atomic unit of length: 5.291 772 105 44 e-11 m, u = 0.000 000 000 82 e-11 m
inline constexpr auto atomic_unit_of_length = bohr_radius;

// atomic unit of mass: 9.109 383 7139 e-31 kg, u = 0.000 000 0028 e-31 kg
inline constexpr auto atomic_unit_of_mass = electron_mass;

// natural unit of action: 1.054 571 817... e-34 J s (exact)
inline constexpr auto natural_unit_of_action = reduced_planck_constant;

// natural unit of length: 3.861 592 6744 e-13 m, u = 0.000 000 0012 e-13 m
inline constexpr auto natural_unit_of_length = reduced_electron_compton_wavelength;

// natural unit of mass: 9.109 383 7139 e-31 kg, u = 0.000 000 0028 e-31 kg
inline constexpr auto natural_unit_of_mass = electron_mass;

// natural unit of velocity: 299 792 458 m s^-1 (exact)
inline constexpr auto natural_unit_of_velocity = speed_of_light_in_vacuum;

// unified atomic mass unit: 1.660 539 068 92 e-27 kg, u = 0.000 000 000 52 e-27 kg
inline constexpr auto unified_atomic_mass_unit = atomic_mass_constant;
// clang-format on

}  // namespace codata2022

}  // namespace mp_units::codata
