// The MIT License (MIT)
//
// Copyright (c) 2018 Mateusz Pusz
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#pragma once

// This file is GENERATED by `scripts/codata_constants.py` from the NIST "allascii"
// tables checked in under `scripts/codata/`. Do not edit it manually; rerun the script.
//
// The CODATA 2014 adjustment: the last one before the 2019 SI redefinition, so h, e,
// k, and N_A are measured here and μ₀ is exact.
//
// This is the `essential` tier: the NIST "Frequently used constants" selection, kept in its
// own header because the complete table costs two orders of magnitude more to compile. The
// full <mp-units/systems/codata/codataYYYY.h> includes this header, so both spell the very
// same constant types and may be mixed freely.
// See <mp-units/systems/codata.h> for the full description of the system.

#include <mp-units/bits/module_macros.h>
#include <mp-units/systems/codata/adopted_values.h>
#include <mp-units/systems/si/constants.h>
#include <mp-units/systems/si/units.h>

#ifndef MP_UNITS_IN_MODULE_INTERFACE
#include <mp-units/framework/unit.h>
#endif

MP_UNITS_EXPORT
namespace mp_units::codata {

namespace codata2014 {

// clang-format off

// atomic mass constant: 1.660 539 040 e-27 kg, u = 0.000 000 020 e-27 kg
inline constexpr struct atomic_mass_constant final :
    named_constant<"m_u", mag_ratio<1'660'539'040, 1'000'000'000> * mag_power<10, -27> * si::kilogram, standard_uncertainty{mag_ratio<20, 10> * mag_power<10, -35> * si::kilogram}> {} atomic_mass_constant;

// Avogadro constant: 6.022 140 857 e23 mol^-1, u = 0.000 000 074 e23 mol^-1
inline constexpr struct avogadro_constant final :
    named_constant<"N_A", mag_ratio<6'022'140'857, 1'000'000'000> * mag_power<10, 23> * one / si::mole, standard_uncertainty{mag_ratio<74, 10> * mag_power<10, 15> * one / si::mole}> {} avogadro_constant;

// Bohr magneton: 927.400 9994 e-26 J T^-1, u = 0.000 0057 e-26 J T^-1
inline constexpr struct bohr_magneton final :
    named_constant<symbol_text{u8"μ_B", "mu_B"}, mag_ratio<9'274'009'994, 10'000'000> * mag_power<10, -26> * si::joule / si::tesla, standard_uncertainty{mag_ratio<57, 10> * mag_power<10, -32> * si::joule / si::tesla}> {} bohr_magneton;

// Bohr radius: 0.529 177 210 67 e-10 m, u = 0.000 000 000 12 e-10 m
inline constexpr struct bohr_radius final :
    named_constant<"a_0", mag_ratio<52'917'721'067, 100'000'000'000> * mag_power<10, -10> * si::metre, standard_uncertainty{mag_ratio<12, 10> * mag_power<10, -20> * si::metre}> {} bohr_radius;

// Boltzmann constant: 1.380 648 52 e-23 J K^-1, u = 0.000 000 79 e-23 J K^-1
inline constexpr struct boltzmann_constant final :
    named_constant<"k", mag_ratio<138'064'852, 100'000'000> * mag_power<10, -23> * si::joule / si::kelvin, standard_uncertainty{mag_ratio<79, 10> * mag_power<10, -30> * si::joule / si::kelvin}> {} boltzmann_constant;

// Compton wavelength: 2.426 310 2367 e-12 m, u = 0.000 000 0011 e-12 m
inline constexpr struct electron_compton_wavelength final :
    named_constant<symbol_text{u8"λ_C", "lambda_C"}, mag_ratio<24'263'102'367, 10'000'000'000> * mag_power<10, -12> * si::metre, standard_uncertainty{mag_ratio<11, 10> * mag_power<10, -21> * si::metre}> {} electron_compton_wavelength;

// conductance quantum: 7.748 091 7310 e-5 S, u = 0.000 000 0018 e-5 S
inline constexpr struct conductance_quantum final :
    named_constant<"G_0", mag_ratio<77'480'917'310, 10'000'000'000> * mag_power<10, -5> * si::siemens, standard_uncertainty{mag_ratio<18, 10> * mag_power<10, -14> * si::siemens}> {} conductance_quantum;

// electron mass: 9.109 383 56 e-31 kg, u = 0.000 000 11 e-31 kg
inline constexpr struct electron_mass final :
    named_constant<"m_e", mag_ratio<910'938'356, 100'000'000> * mag_power<10, -31> * si::kilogram, standard_uncertainty{mag_ratio<11, 10> * mag_power<10, -38> * si::kilogram}> {} electron_mass;

// elementary charge: 1.602 176 6208 e-19 C, u = 0.000 000 0098 e-19 C
inline constexpr struct elementary_charge final :
    named_constant<"e", mag_ratio<16'021'766'208, 10'000'000'000> * mag_power<10, -19> * si::coulomb, standard_uncertainty{mag_ratio<98, 10> * mag_power<10, -28> * si::coulomb}> {} elementary_charge;

// Faraday constant: 96 485.332 89 C mol^-1, u = 0.000 59 C mol^-1
inline constexpr struct faraday_constant final :
    named_constant<"F", mag_ratio<9'648'533'289, 100'000> * si::coulomb / si::mole, standard_uncertainty{mag_ratio<59, 10> * mag_power<10, -4> * si::coulomb / si::mole}> {} faraday_constant;

// fine-structure constant: 7.297 352 5664 e-3, u = 0.000 000 0017 e-3
inline constexpr struct fine_structure_constant final :
    named_constant<symbol_text{u8"α", "alpha"}, mag_ratio<72'973'525'664, 10'000'000'000> * mag_power<10, -3> * one, standard_uncertainty{mag_ratio<17, 10> * mag_power<10, -12> * one}> {} fine_structure_constant;

// Hartree energy: 4.359 744 650 e-18 J, u = 0.000 000 054 e-18 J
inline constexpr struct hartree_energy final :
    named_constant<"E_h", mag_ratio<4'359'744'650, 1'000'000'000> * mag_power<10, -18> * si::joule, standard_uncertainty{mag_ratio<54, 10> * mag_power<10, -26> * si::joule}> {} hartree_energy;

// inverse fine-structure constant: 137.035 999 139, u = 0.000 000 031
inline constexpr struct inverse_fine_structure_constant final :
    named_constant<"inverse_fine_structure_constant", mag_ratio<137'035'999'139, 1'000'000'000> * one, standard_uncertainty{mag_ratio<31, 10> * mag_power<10, -8> * one}> {} inverse_fine_structure_constant;

// Josephson constant: 483 597.8525 e9 Hz V^-1, u = 0.0030 e9 Hz V^-1
inline constexpr struct josephson_constant final :
    named_constant<"K_J", mag_ratio<4'835'978'525, 10'000> * mag_power<10, 9> * si::hertz / si::volt, standard_uncertainty{mag_ratio<30, 10> * mag_power<10, 6> * si::hertz / si::volt}> {} josephson_constant;

// mag. flux quantum: 2.067 833 831 e-15 Wb, u = 0.000 000 013 e-15 Wb
inline constexpr struct magnetic_flux_quantum final :
    named_constant<symbol_text{u8"Φ₀", "Phi_0"}, mag_ratio<2'067'833'831, 1'000'000'000> * mag_power<10, -15> * si::weber, standard_uncertainty{mag_ratio<13, 10> * mag_power<10, -23> * si::weber}> {} magnetic_flux_quantum;

// molar gas constant: 8.314 4598 J mol^-1 K^-1, u = 0.000 0048 J mol^-1 K^-1
inline constexpr struct molar_gas_constant final :
    named_constant<"R", mag_ratio<83'144'598, 10'000'000> * si::joule / si::mole / si::kelvin, standard_uncertainty{mag_ratio<48, 10> * mag_power<10, -6> * si::joule / si::mole / si::kelvin}> {} molar_gas_constant;

// muon mass: 1.883 531 594 e-28 kg, u = 0.000 000 048 e-28 kg
inline constexpr struct muon_mass final :
    named_constant<symbol_text{u8"m_μ", "m_mu"}, mag_ratio<1'883'531'594, 1'000'000'000> * mag_power<10, -28> * si::kilogram, standard_uncertainty{mag_ratio<48, 10> * mag_power<10, -36> * si::kilogram}> {} muon_mass;

// neutron mass: 1.674 927 471 e-27 kg, u = 0.000 000 021 e-27 kg
inline constexpr struct neutron_mass final :
    named_constant<"m_n", mag_ratio<1'674'927'471, 1'000'000'000> * mag_power<10, -27> * si::kilogram, standard_uncertainty{mag_ratio<21, 10> * mag_power<10, -35> * si::kilogram}> {} neutron_mass;

// Newtonian constant of gravitation: 6.674 08 e-11 m^3 kg^-1 s^-2, u = 0.000 31 e-11 m^3 kg^-1 s^-2
inline constexpr struct newtonian_constant_of_gravitation final :
    named_constant<"G", mag_ratio<667'408, 100'000> * mag_power<10, -11> * cubic(si::metre) / si::kilogram / square(si::second), standard_uncertainty{mag_ratio<31, 10> * mag_power<10, -15> * cubic(si::metre) / si::kilogram / square(si::second)}> {} newtonian_constant_of_gravitation;

// nuclear magneton: 5.050 783 699 e-27 J T^-1, u = 0.000 000 031 e-27 J T^-1
inline constexpr struct nuclear_magneton final :
    named_constant<symbol_text{u8"μ_N", "mu_N"}, mag_ratio<5'050'783'699, 1'000'000'000> * mag_power<10, -27> * si::joule / si::tesla, standard_uncertainty{mag_ratio<31, 10> * mag_power<10, -35> * si::joule / si::tesla}> {} nuclear_magneton;

// Planck constant: 6.626 070 040 e-34 J s, u = 0.000 000 081 e-34 J s
inline constexpr struct planck_constant final :
    named_constant<"h", mag_ratio<6'626'070'040, 1'000'000'000> * mag_power<10, -34> * si::joule * si::second, standard_uncertainty{mag_ratio<81, 10> * mag_power<10, -42> * si::joule * si::second}> {} planck_constant;

// Planck constant over 2 pi: 1.054 571 800 e-34 J s, u = 0.000 000 013 e-34 J s
inline constexpr struct reduced_planck_constant final :
    named_constant<symbol_text{u8"ℏ", "hbar"}, mag_ratio<1'054'571'800, 1'000'000'000> * mag_power<10, -34> * si::joule * si::second, standard_uncertainty{mag_ratio<13, 10> * mag_power<10, -42> * si::joule * si::second}> {} reduced_planck_constant;

// proton-electron mass ratio: 1836.152 673 89, u = 0.000 000 17
inline constexpr struct proton_electron_mass_ratio final :
    named_constant<"proton_electron_mass_ratio", mag_ratio<183'615'267'389, 100'000'000> * one, standard_uncertainty{mag_ratio<17, 10> * mag_power<10, -7> * one}> {} proton_electron_mass_ratio;

// proton mass: 1.672 621 898 e-27 kg, u = 0.000 000 021 e-27 kg
inline constexpr struct proton_mass final :
    named_constant<"m_p", mag_ratio<1'672'621'898, 1'000'000'000> * mag_power<10, -27> * si::kilogram, standard_uncertainty{mag_ratio<21, 10> * mag_power<10, -35> * si::kilogram}> {} proton_mass;

// Rydberg constant: 10 973 731.568 508 m^-1, u = 0.000 065 m^-1
inline constexpr struct rydberg_constant final :
    named_constant<symbol_text{u8"R_∞", "R_inf"}, mag_ratio<10'973'731'568'508, 1'000'000> * one / si::metre, standard_uncertainty{mag_ratio<65, 10> * mag_power<10, -5> * one / si::metre}> {} rydberg_constant;

// speed of light in vacuum: 299 792 458 m s^-1 (exact)
using si::si2019::speed_of_light_in_vacuum;

// Stefan-Boltzmann constant: 5.670 367 e-8 W m^-2 K^-4, u = 0.000 013 e-8 W m^-2 K^-4
inline constexpr struct stefan_boltzmann_constant final :
    named_constant<symbol_text{u8"σ", "sigma"}, mag_ratio<5'670'367, 1'000'000> * mag_power<10, -8> * si::watt / square(si::metre) / pow<4>(si::kelvin), standard_uncertainty{mag_ratio<13, 10> * mag_power<10, -13> * si::watt / square(si::metre) / pow<4>(si::kelvin)}> {} stefan_boltzmann_constant;

// von Klitzing constant: 25 812.807 4555 ohm, u = 0.000 0059 ohm
inline constexpr struct von_klitzing_constant final :
    named_constant<"R_K", mag_ratio<258'128'074'555, 10'000'000> * si::ohm, standard_uncertainty{mag_ratio<59, 10> * mag_power<10, -6> * si::ohm}> {} von_klitzing_constant;

// mag. constant: 12.566 370 614... e-7 N A^-2 (exact)
// Exact by definition: until the 2019 redefinition the ampere was defined through this constant.
inline constexpr struct magnetic_constant final :
    named_constant<symbol_text{u8"μ₀", "u_0"}, mag<4> * mag_power<10, -7> * π * si::henry / si::metre> {} magnetic_constant;

// electric constant: 8.854 187 817... e-12 F m^-1 (exact)
inline constexpr struct vacuum_electric_permittivity final :
    named_constant<symbol_text{u8"ε₀", "eps_0"}, one / magnetic_constant / square(speed_of_light_in_vacuum)> {} vacuum_electric_permittivity;
// clang-format on

}  // namespace codata2014

}  // namespace mp_units::codata
