// The MIT License (MIT)
//
// Copyright (c) 2018 Mateusz Pusz
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#pragma once

// This file is GENERATED by `scripts/codata_constants.py` from the NIST "allascii"
// tables checked in under `scripts/codata/`. Do not edit it manually; rerun the script.
//
// Solutions of the Wien displacement transcendental equations `x = n (1 - exp(-x))`
// (n = 5 for the wavelength form, n = 3 for the frequency form). Like `π`, they are
// exact mathematical constants; the truncated literals below are the approximations
// used when a conversion factor is materialized into a representation type. The Wien
// displacement law constants of the post-2019 adjustments are defined through them.

#include <mp-units/bits/hacks.h>
#include <mp-units/bits/module_macros.h>

#ifndef MP_UNITS_IN_MODULE_INTERFACE
#include <mp-units/framework/unit.h>
#endif

MP_UNITS_EXPORT
namespace mp_units::codata {

// clang-format off
#if defined MP_UNITS_COMP_CLANG && MP_UNITS_COMP_CLANG < 18
inline constexpr struct wien_x_wavelength_c final : mag_constant<symbol_text{u8"x_λ", "x_lambda"}> {
  static constexpr auto _value_ = 4.965114231744276303698759131322893944L;
} wien_x_wavelength_c;
inline constexpr struct wien_x_frequency_c final : mag_constant<symbol_text{u8"x_ν", "x_nu"}> {
  static constexpr auto _value_ = 2.821439372122078893403191330294485195L;
} wien_x_frequency_c;
#else
inline constexpr struct wien_x_wavelength_c final :
    mag_constant<symbol_text{u8"x_λ", "x_lambda"}, 4.965114231744276303698759131322893944L> {} wien_x_wavelength_c;
inline constexpr struct wien_x_frequency_c final :
    mag_constant<symbol_text{u8"x_ν", "x_nu"}, 2.821439372122078893403191330294485195L> {} wien_x_frequency_c;
#endif
inline constexpr struct wien_x_wavelength final :
    named_constant<symbol_text{u8"x_λ", "x_lambda"}, mag<wien_x_wavelength_c> * one> {} wien_x_wavelength;
inline constexpr struct wien_x_frequency final :
    named_constant<symbol_text{u8"x_ν", "x_nu"}, mag<wien_x_frequency_c> * one> {} wien_x_frequency;
// clang-format on

}  // namespace mp_units::codata
