#!/bin/bash

# Sets up the full mp-units compiler matrix on a Debian/Ubuntu host: the GCC and
# clang-N toolchains (from the distro and/or apt.llvm.org, whose repository this
# script wires up itself), plus any clang versions that ship only as upstream
# LLVM release tarballs (e.g. 16).
#
# Goal: every clang-N links its OWN, version-matched libc++ -- not a single
# shared libc++ borrowed from one LLVM version (which is what apt forces and is
# neither what CI nor end users exercise per clang version).
#
# Why apt can't do this directly:
#   The libc++ runtime .so ships in UNVERSIONED packages (libc++1, libc++abi1,
#   llvm-libunwind1) in the shared multiarch dir /usr/lib/x86_64-linux-gnu, and
#   the headers are exposed through the single symlink /usr/include/c++/v1.
#   Only one libc++ version can occupy those shared paths, so installing
#   libc++-N-dev makes every clang use that one version.
#
# How this script gives each clang its own libc++ -- with NO Conan/CMake flags,
# so even a bare `clang++-N -stdlib=libc++` is correct:
#   * GCC      -> apt. Versioned g++-N packages do NOT share files; no conflict.
#   * apt clang -> apt, from the distro archive where it has the version and
#                 from apt.llvm.org otherwise (see LLVM_APT_SUITE below).
#   * apt clang libc++ -> download (do NOT install) the version-matched
#                 libc++/libc++abi/libunwind -dev .debs and copy their STATIC
#                 libraries, headers, and `import std` module sources into the
#                 per-version tree /usr/lib/llvm-N/.
#   * tarball clang -> for versions with no usable apt package (16), download the
#                 upstream LLVM release tarball, which is a self-contained
#                 toolchain (clang + its own libc++), and unpack it to
#                 /usr/lib/llvm-N, then symlink /usr/bin/clang*-N.
#   In both cases libc++ is linked STATICALLY (the unversioned runtime *.so
#   cannot coexist), so each clang is fully self-contained -- no rpath /
#   LD_LIBRARY_PATH, and it works even for a clang nightly with no release.
#   * discovery:
#       - headers + import std: clang resolves /usr/lib/llvm-N/include/c++/v1 and
#         libc++.modules.json relative to its own binary/resource dir -- found
#         with no flags.
#       - link path: older clang (<=18) adds /usr/lib/llvm-N/lib to the linker
#         search, newer clang (20+) does NOT. So we drop a per-version clang
#         configuration file <triple>-clang++.cfg into /usr/lib/llvm-N/bin/ that
#         adds `-L/usr/lib/llvm-N/lib`. clang auto-loads it from its binary dir,
#         and the path lands first, ahead of the shared multiarch dir.
#
# Run as root (or via sudo). Doubles as a Dockerfile reference: each block maps
# to a RUN step. Idempotent -- safe to re-run.

set -euo pipefail

# --- Build-matrix compiler versions (see .devcontainer/check_all.sh) ---------
GCC_VERSIONS=(12 13 14 15)
# clang libc++ sourced from apt -dev packages:
APT_CLANG_VERSIONS=(17 18 20 21 22 23 24)
# clang sourced from upstream LLVM release tarballs (version -> URL). clang-16
# has no apt package on recent Ubuntu and old-release packages conflict, so use
# the self-contained upstream build (16.0.6 has no x86_64 Linux prebuilt; 16.0.4
# is the newest that does, and runs fine on newer glibc).
declare -A TARBALL_CLANG=(
  [16]="https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.4/clang+llvm-16.0.4-x86_64-linux-gnu-ubuntu-22.04.tar.xz"
)
# clang-19 cannot compile mp-units (https://github.com/llvm/llvm-project/pull/118288).

# clang versions the distro archive does not ship, and the apt.llvm.org suite to
# take each one from. A released branch gets its own numbered suite; the
# UNVERSIONED suite is LLVM's development branch, i.e. the HEAD snapshot, which
# is where the newest clang (24) lives and the only place it can come from.
# shellcheck disable=SC1091  # /etc/os-release is generated by the distro, not part of this repo
LLVM_CODENAME="$( . /etc/os-release && echo "${UBUNTU_CODENAME:-${VERSION_CODENAME:-}}" )"
declare -A LLVM_APT_SUITE=(
  [22]="llvm-toolchain-$LLVM_CODENAME-22"
  [23]="llvm-toolchain-$LLVM_CODENAME-23"
  [24]="llvm-toolchain-$LLVM_CODENAME"
)
LLVM_APT_KEYRING=/etc/apt/keyrings/apt.llvm.org.asc
LLVM_APT_SOURCES=/etc/apt/sources.list.d/mp-units-llvm.sources

if [[ $EUID -ne 0 ]]; then
  echo "❌ Run as root: sudo $0" >&2
  exit 1
fi

# Conan profiles live in the invoking (non-root) user's home, not root's.
TARGET_USER="${SUDO_USER:-$(id -un)}"
TARGET_HOME="$(getent passwd "$TARGET_USER" | cut -d: -f6)"
fail=0
PROFILES_DIR="${CONAN_HOME:-$TARGET_HOME/.conan2}/profiles"

# ---------------------------------------------------------------------------
# 0) apt.llvm.org suites for the clang versions the distro archive lacks. Each
#    stanza goes into our OWN sources file, and only when no other file already
#    configures that suite, so one the host already has is never duplicated.
# ---------------------------------------------------------------------------
echo ""
echo "🛠️  Checking apt.llvm.org suites: ${LLVM_APT_SUITE[*]}"

# Is $1 already listed as a suite by some configured apt source?
suite_configured() {
  local suite=$1 file entry
  for file in /etc/apt/sources.list.d/*.sources; do
    [[ -f $file ]] || continue
    # word splitting is the point: one `Suites:` line may list several suites
    # shellcheck disable=SC2013
    for entry in $(sed -n 's/^Suites:[[:space:]]*//p' "$file"); do
      [[ $entry == "$suite" ]] && return 0
    done
  done
  # legacy one-line format: `deb <uri> <suite> <components...>`
  cat /etc/apt/sources.list /etc/apt/sources.list.d/*.list 2>/dev/null |
    awk -v s="$suite" '$1=="deb" && $3==s {found=1} END{exit !found}'
}

for v in "${!LLVM_APT_SUITE[@]}"; do
  suite="${LLVM_APT_SUITE[$v]}"
  if suite_configured "$suite"; then
    echo "  ✅ clang-$v: $suite already configured"
    continue
  fi
  # A branch is published only once it exists upstream -- adding a suite that is
  # not there yet would break every later apt-get update, so check first.
  if ! curl -fsI "https://apt.llvm.org/$LLVM_CODENAME/dists/$suite/Release" >/dev/null; then
    echo "  ⚠️  clang-$v: $suite not published for $LLVM_CODENAME -- skipping" >&2
    continue
  fi
  if [[ ! -f $LLVM_APT_KEYRING ]]; then
    mkdir -p "$(dirname "$LLVM_APT_KEYRING")"
    curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key -o "$LLVM_APT_KEYRING"
    chmod 644 "$LLVM_APT_KEYRING"
  fi
  printf 'Types: deb\nURIs: https://apt.llvm.org/%s/\nSuites: %s\nComponents: main\nSigned-By: %s\n\n' \
    "$LLVM_CODENAME" "$suite" "$LLVM_APT_KEYRING" >> "$LLVM_APT_SOURCES"
  echo "  ➕ clang-$v: added $suite to $LLVM_APT_SOURCES"
done

echo ""
echo "🔄 apt-get update..."
apt-get update

# ---------------------------------------------------------------------------
# 1) GCC -- versioned packages coexist cleanly.
# ---------------------------------------------------------------------------
echo ""
echo "🛠️  Installing GCC: ${GCC_VERSIONS[*]}"
gcc_pkgs=()
for v in "${GCC_VERSIONS[@]}"; do gcc_pkgs+=("gcc-$v" "g++-$v"); done
apt-get install -y --no-install-recommends "${gcc_pkgs[@]}"

# ---------------------------------------------------------------------------
# 2) apt clang toolchains. clang-tools-N comes along because it carries
#    clang-scan-deps, which CMake needs to scan C++ module and `import std`
#    dependencies -- without it those builds fail at configure time.
# ---------------------------------------------------------------------------
echo ""
echo "🛠️  Installing apt clang: ${APT_CLANG_VERSIONS[*]}"
clang_pkgs=()
for v in "${APT_CLANG_VERSIONS[@]}"; do
  if [[ -x /usr/lib/llvm-$v/bin/clang++ ]]; then
    echo "  ✅ clang-$v already present"
  else
    clang_pkgs+=("clang-$v" "clang-tools-$v")
  fi
done
if (( ${#clang_pkgs[@]} )); then
  apt-get install -y --no-install-recommends "${clang_pkgs[@]}"
fi

# ---------------------------------------------------------------------------
# 3) Tarball clang toolchains (self-contained: clang + libc++).
# ---------------------------------------------------------------------------
echo ""
echo "🛠️  Installing tarball clang toolchains: ${!TARBALL_CLANG[*]}"
for v in "${!TARBALL_CLANG[@]}"; do
  dest="/usr/lib/llvm-$v"
  if [[ -x $dest/bin/clang ]]; then
    echo "  ✅ clang-$v already present at $dest"
  else
    echo "  ⬇️  clang-$v: downloading + unpacking $(basename "${TARBALL_CLANG[$v]}")..."
    mkdir -p "$dest"
    # Stream straight into tar; --strip-components drops the top-level dir.
    curl -fsSL "${TARBALL_CLANG[$v]}" | tar -xJ --strip-components=1 -C "$dest"
    [[ ${PIPESTATUS[0]} -eq 0 ]] || { echo "  ❌ clang-$v download failed" >&2; exit 1; }
  fi
  # Expose the usual /usr/bin entry points.
  for tool in clang clang++ clang-cpp; do
    ln -sf "$dest/bin/$tool" "/usr/bin/$tool-$v"
  done
done

# ---------------------------------------------------------------------------
# 4) Per-version libc++ for apt clang -- download .debs, copy static libs +
#    headers + module sources into the versioned tree.
# ---------------------------------------------------------------------------
echo ""
echo "🛠️  Installing per-version libc++ for apt clang: ${APT_CLANG_VERSIONS[*]}"
for v in "${APT_CLANG_VERSIONS[@]}"; do
  dest="/usr/lib/llvm-$v"
  if [[ ! -d $dest/bin ]]; then
    echo "  ⚠️  $dest missing -- clang-$v not installed? Skipping." >&2
    continue
  fi

  echo "  📦 clang-$v: downloading libc++/libc++abi/libunwind -dev .debs..."
  tmp="$(mktemp -d)"
  chmod 755 "$tmp"          # let the unprivileged _apt user read the downloads
  # Pin to the installed clang's own package version. apt.llvm.org's snapshot
  # suites (22+) rotate daily, so an unpinned download pairs today's libc++ with
  # whichever clang happens to be installed. Fall back unpinned where no such
  # version exists, which is what a distro package with a differing revision does.
  pin="$(dpkg-query -W -f='=${Version}' "clang-$v" 2>/dev/null || true)"
  ( cd "$tmp"
    apt-get download "libc++-$v-dev$pin" "libc++abi-$v-dev$pin" "libunwind-$v-dev$pin" 2>/dev/null ||
      apt-get download "libc++-$v-dev" "libc++abi-$v-dev" "libunwind-$v-dev"
    mkdir extracted
    for d in *.deb; do dpkg-deb -x "$d" extracted; done )
  src="$tmp/extracted/usr/lib/llvm-$v"

  # Check the replacement is on disk BEFORE removing what is installed: a partial
  # download must not leave the compiler with no libc++ headers at all.
  if [[ ! -d "$src/include/c++/v1" ]]; then
    echo "  ❌ clang-$v: downloaded .debs carry no libc++ headers -- keeping the existing tree" >&2
    rm -rf "$tmp"; fail=1; continue
  fi

  echo "  🚚 clang-$v: installing version-matched libc++..."
  mkdir -p "$dest/include/c++"
  rm -rf "$dest/include/c++/v1"                      # drop stale cross-version symlink
  cp -RfL "$src/include/c++/v1" "$dest/include/c++/"
  if [[ -d "$src/share/libc++" ]]; then              # import std module sources
    mkdir -p "$dest/share"; rm -rf "$dest/share/libc++"
    cp -RfL "$src/share/libc++" "$dest/share/"
  fi
  # Static archives + the import-std manifest (libc++.modules.json). NOT the
  # shared .so -- step 5 enforces static linking. The manifest's paths are
  # relative to its own dir, so it must land in $dest/lib alongside ../share.
  for f in "$src"/lib/libc++*.a "$src"/lib/libunwind*.a "$src"/lib/libc++*.modules.json; do
    [[ -e $f ]] && cp -fL "$f" "$dest/lib/"
  done
  rm -rf "$tmp"
done

# ---------------------------------------------------------------------------
# 5) Make every clang link its own libc++ STATICALLY:
#      - keep only static *.a (+ modules.json); drop shared *.so / linker scripts
#      - drop <triple>-clang++.cfg with -L so the versioned lib dir is searched
#        first (newer clang does not add it on its own).
# ---------------------------------------------------------------------------
echo ""
echo "🔧 Wiring static libc++ discovery (config files)..."
ALL_CLANG=("${!TARBALL_CLANG[@]}" "${APT_CLANG_VERSIONS[@]}")
for v in "${ALL_CLANG[@]}"; do
  dest="/usr/lib/llvm-$v"
  [[ -d $dest/lib ]] || continue
  triple="$(clang++-"$v" -print-target-triple)"
  # libc++.a lives in lib/ (apt -dev copy) or lib/<triple>/ (release tarball).
  libdir="$dest/lib"; [[ -e "$dest/lib/$triple/libc++.a" ]] && libdir="$dest/lib/$triple"
  # Static-only: drop real shared objects + any .so linker scripts (recursively,
  # so the per-triple subdir is covered too) -- nothing must pull the
  # non-coexisting runtime .so.
  find "$dest/lib" \( -name 'libc++*.so*' -o -name 'libunwind*.so*' \) -delete 2>/dev/null || true
  # apt's libc++.a bundles libc++abi, so `-lc++` links it statically as-is.
  # Release-tarball libc++.a does NOT, so provide a libc++.so linker script that
  # makes `-lc++` statically pull abi + unwind as well (compile-safe -- unlike an
  # -lc++abi config arg, a linker script is only read at link time).
  # `grep -q` exits on its first match, so `nm` dies of SIGPIPE (141) and
  # `pipefail` reports the whole pipeline as failed -- which fired this branch for
  # every clang, writing the linker script exactly where apt's self-contained
  # libc++.a must not have one. Absorb `nm`'s status so only `grep` decides.
  if ! { nm "$libdir/libc++.a" 2>/dev/null || true; } | grep -q "T __cxa_throw"; then
    printf 'INPUT(%s/libc++.a %s/libc++abi.a %s/libunwind.a)\n' "$libdir" "$libdir" "$libdir" > "$libdir/libc++.so"
    echo "  🧩 clang-$v: libc++.so linker script (static abi + unwind)"
  fi
  # Config file (auto-loaded from the binary dir):
  #   -L  search clang's own libc++ dir first for linking (newer clang does not
  #       add it on its own; for tarball clang it also beats the shared dir).
  #   -B  add $dest/lib to clang's file search so CMake's
  #       `-print-file-name=libc++.modules.json` resolves the import-std manifest
  #       there. Older clang (<=18) lacks the resource-relative manifest lookup
  #       that newer clang has, and otherwise reports "libc++.modules.json: File
  #       not found". Harmless where the manifest is absent (e.g. clang-16).
  cfg="$dest/bin/$triple-clang++.cfg"
  printf -- '# mp-units: clang-%s links its own static libc++ in %s\n-L%s\n-B%s/lib\n' \
    "$v" "$libdir" "$libdir" "$dest" > "$cfg"
  echo "  🔧 clang-$v: $cfg"
done

# ---------------------------------------------------------------------------
# 6) Conan profiles -- point each clang at its REAL binary path, not the
#    /usr/bin/clang++-N symlink. clang-scan-deps (used to scan C++ module /
#    `import std` dependencies) derives the toolchain root from the compiler
#    path WITHOUT resolving symlinks: via /usr/bin/clang++-N it looks for libc++
#    under /usr/bin/../include/c++/v1 == the shared, single-version
#    /usr/include/c++/v1 instead of the versioned tree -- so `import std` breaks
#    for any clang whose version != that shared one (e.g. <flat_map> not found).
#    The real path /usr/lib/llvm-N/bin/clang++ resolves the root correctly (and
#    makes the config file above load reliably). This is a compiler PATH fix,
#    not build-flag instrumentation.
# ---------------------------------------------------------------------------
echo ""
echo "🔧 Pointing Conan clang profiles at real binary paths ($PROFILES_DIR)..."
if [[ -d $PROFILES_DIR ]]; then
  for v in "${ALL_CLANG[@]}"; do
    profile="$PROFILES_DIR/clang$v"
    [[ -f $profile ]] || { echo "  ⚠️  profile clang$v missing -- skipping"; continue; }
    sed -i -E "s#(tools.build:compiler_executables=)\{[^}]*\}#\1{\"c\": \"/usr/lib/llvm-$v/bin/clang\", \"cpp\": \"/usr/lib/llvm-$v/bin/clang++\"}#" "$profile"
    chown "$TARGET_USER:$TARGET_USER" "$profile" 2>/dev/null || true
    echo "  🔧 clang$v -> /usr/lib/llvm-$v/bin/clang++"
  done
else
  echo "  ⚠️  $PROFILES_DIR not found; ensure each clangN profile uses real paths:" >&2
  echo "     tools.build:compiler_executables={\"c\":\"/usr/lib/llvm-N/bin/clang\",\"cpp\":\"/usr/lib/llvm-N/bin/clang++\"}" >&2
fi

# ---------------------------------------------------------------------------
# 7) Verify: GCC compiles; each clang compiles AND links its own libc++ with
#    NO extra flags (exercising the real default-discovery path).
# ---------------------------------------------------------------------------
echo ""
echo "🔎 Verifying toolchains..."
t="$(mktemp --suffix=.cpp)"; out="$(mktemp -u)"
printf '#include <vector>\n#include <string>\nint main(){std::string s="x";std::vector<int> v{1,2,3};return (int)v.size()-3;}\n' > "$t"

for v in "${GCC_VERSIONS[@]}"; do
  if g++-"$v" -std=c++20 "$t" -o "$out" 2>/dev/null; then echo "  ✅ g++-$v"
  else echo "  ❌ g++-$v"; fail=1; fi
done
for v in "${ALL_CLANG[@]}"; do
  command -v clang++-"$v" >/dev/null 2>&1 || { echo "  ⚠️  clang++-$v not installed"; continue; }
  if clang++-"$v" -std=c++20 -stdlib=libc++ "$t" -o "$out" 2>/tmp/cxx_err; then
    hdr="$(echo '' | clang++-"$v" -stdlib=libc++ -x c++ -E -v - 2>&1 | grep -m1 "llvm-$v.*c++/v1" | tr -d ' ')"
    ldd "$out" 2>/dev/null | grep -qiE "libc\+\+|unwind" \
      && echo "  ⚠️  clang++-$v links libc++ dynamically (expected static)" \
      || echo "  ✅ clang++-$v (own libc++, static; headers: ${hdr:-?})"
  else
    echo "  ❌ clang++-$v failed:"; sed 's/^/        /' /tmp/cxx_err; fail=1
  fi
done
rm -f "$t" "$out" /tmp/cxx_err

echo ""
if [[ $fail -eq 0 ]]; then
  echo "🎉 Compiler infrastructure ready. Next: .devcontainer/check_all.sh build"
else
  echo "⚠️  Some toolchains failed verification (see above)." >&2; exit 1
fi
