// The MIT License (MIT)
//
// Copyright (c) 2018 Mateusz Pusz
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#pragma once

// This file is GENERATED by `scripts/codata_constants.py` from the NIST "allascii"
// tables checked in under `scripts/codata/`. Do not edit it manually; rerun the script.
//
// The CODATA recommended values of the fundamental physical constants, expressed in SI
// units, with one namespace (and one header) per adjustment. Include this umbrella for
// all of them, or `mp-units/systems/codata/codataYYYY.h` for a single adjustment.
//
// This is a system of its own rather than a part of `si`. The SI fixes exactly seven
// constants (see `si2019` in `si/constants.h`, aliased in every adjustment namespace);
// everything CODATA publishes beyond those is *measured*, so its value carries a
// standard uncertainty and shifts with each adjustment. Keeping them out of `si` means
// `mp-units/systems/si.h`, which is what most translation units reach for, does not pay
// for constants that most of them never name.
//
// Measured constants declare the absolute standard uncertainty exactly as the table
// publishes it (`standard_uncertainty`); exact-by-definition values printed by NIST as
// truncated non-terminating decimals ("...") are defined by their exact symbolic
// relation instead, so nothing in these headers is rounded by us. Rows that restate a
// constant in other units ("... in MeV", "energy equivalent", unit relationships) are
// not repeated: constants are units in this library, so those forms are a conversion at
// the point of use.
//
// The most recent adjustment is `inline`, so `codata::magnetic_constant` is the current
// value and `codata::codata2018::magnetic_constant` pins a specific one. Moving that
// `inline` to a newer adjustment is a deliberate, documented change of the default.
//
// NOTE: these are *not* interchangeable with the constants of the same name in
// `mp_units::hep`. HEP declares its own system of quantities (base dimensions L, T, Q,
// E, ...; energy is a base quantity and there is no mass dimension), so its constants
// are unrelated types. The published uncertainties differ too: before the 2019
// redefinition the elementary charge was itself measured, so a mass expressed in kg and
// the same mass expressed in MeV/c² are separate CODATA table entries with different
// uncertainties.

#include <mp-units/systems/codata/codata2014.h>
#include <mp-units/systems/codata/codata2018.h>
#include <mp-units/systems/codata/codata2022.h>
