parse:
  additional_commands:
    _jegp_common_yaml_anchors:
      kwargs:
        PUBLIC_INTERFACE_PRIVATE: &public_interface_private
          kwargs:
            PUBLIC: +
            INTERFACE: +
            PRIVATE: +
    jegp_add_standardese_sources:
      pargs:
        nargs: 1
        flags:
        - EXCLUDE_FROM_ALL
      kwargs:
        LIBRARIES: +
        APPENDICES: +
        EXTENSIONS: +
        CHECKED: 1
        PDF: &standardese_pdf
          pargs:
            flags:
            - EXCLUDE_FROM_MAIN
          kwargs:
            PATH: 1
        HTML:
          <<: *standardese_pdf
          kwargs:
            SECTION_FILE_STYLE: 1
            LATEX_REGEX_REPLACE: +
            HTML_REGEX_REPLACE: +
    jegp_add_module:
      pargs: &jegp_add_module_pargs
        nargs: 1
        flags:
        - IMPORTABLE_HEADER
      kwargs:
        SOURCES: +
        COMPILE_OPTIONS: *public_interface_private
        LINK_LIBRARIES: *public_interface_private
    jegp_cpp_module:
      pargs: *jegp_add_module_pargs
    jegp_target_link_header_units:
      pargs:
        nargs: 1+
    jegp_cpp2_target_sources:
      pargs:
        nargs: 1
      kwargs:
        JEGP_FILE_SET_KWARGS: &file_set
          kwargs:
            FILE_SET: 1
            TYPE: 1
            BASE_DIRS: +
            FILES: +
        PUBLIC: *file_set
        INTERFACE: *file_set
        PRIVATE: *file_set
    jegp_add_headers_test:
      pargs:
        nargs: 1+
      kwargs:
        PRIVATE_REGEXES: +
    jegp_add_test:
      pargs:
        nargs: 1+
        flags:
        - COMPILE_ONLY
      kwargs:
        TYPE: 1
        SOURCES: +
        COMPILE_OPTIONS: +
        LINK_LIBRARIES: +
    jegp_add_build_error:
      pargs:
        nargs: 1+
      kwargs:
        AS: 1
        TYPE: 1
        SOURCE: 1
        COMPILE_OPTIONS: +
        LINK_LIBRARIES: +
