# The MIT License (MIT)
#
# Copyright (c) 2018 Mateusz Pusz
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: CMake Test Package CI

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "docs/**"
      - "example/**"
      - "test/**"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "docs/**"
      - "example/**"
      - "test/**"
  workflow_dispatch:
    inputs:
      matrix-seed:
        description: The random seed for the subset of the full test-matrix to be run (set to '0' to select one at random)
        required: true
        type: number
        default: 0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-matrix:
    name: "Generate build matrix for ${{ github.workflow }}"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      seed: ${{ steps.set-matrix.outputs.seed }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - id: set-matrix
        run: python .github/generate-job-matrix.py --preset cmake --seed ${{ inputs.matrix-seed || 0 }} --debug combinations counts
      - name: Generate job summary
        if: always()
        env:
          MATRIX_JSON: ${{ steps.set-matrix.outputs.matrix }}
          MATRIX_SEED: ${{ steps.set-matrix.outputs.seed }}
        run: python .github/generate-matrix-summary.py >> $GITHUB_STEP_SUMMARY
  test_package:
    name: "${{ matrix.config-summary-str }}"
    runs-on: ${{ matrix.toolchain.os }}
    timeout-minutes: 120
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.generate-matrix.outputs.matrix)}}

    env:
      CC: ${{ matrix.toolchain.compiler.cc }}
      CXX: ${{ matrix.toolchain.compiler.cxx }}

    steps:
      - name: Downcase 'build_type'
        id: build_type
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ matrix.build_type }}
      - uses: actions/checkout@v4
      - name: Generate unique cache id
        shell: bash
        run: echo "cache_id=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_ENV
      - name: Cache Conan data
        uses: actions/cache@v4
        if: always()
        env:
          cache-name: cache-conan-data
        with:
          path: ~/.conan2/p
          key: cmake-${{ matrix.toolchain.os }}-${{ matrix.formatting }}-${{ matrix.contracts }}-${{ matrix.toolchain.compiler.type }}-${{ matrix.toolchain.lib }}-${{ matrix.build_type }}-${{ matrix.toolchain.compiler.version }}-${{ matrix.std }}-${{ env.cache_id }}
          restore-keys: |
            cmake-${{ matrix.toolchain.os }}-${{ matrix.formatting }}-${{ matrix.contracts }}-${{ matrix.toolchain.compiler.type }}-${{ matrix.toolchain.lib }}-${{ matrix.build_type }}-${{ matrix.toolchain.compiler.version }}-${{ matrix.std }}-
            cmake-${{ matrix.toolchain.os }}-${{ matrix.formatting }}-${{ matrix.contracts }}-${{ matrix.toolchain.compiler.type }}-${{ matrix.toolchain.lib }}-${{ matrix.build_type }}-${{ matrix.toolchain.compiler.version }}-
            cmake-${{ matrix.toolchain.os }}-${{ matrix.formatting }}-${{ matrix.contracts }}-${{ matrix.toolchain.compiler.type }}-${{ matrix.toolchain.lib }}-${{ matrix.build_type }}-
            cmake-${{ matrix.toolchain.os }}-${{ matrix.formatting }}-${{ matrix.contracts }}-${{ matrix.toolchain.compiler.type }}-${{ matrix.toolchain.lib }}-
            cmake-${{ matrix.toolchain.os }}-${{ matrix.formatting }}-${{ matrix.contracts }}-${{ matrix.toolchain.compiler.type }}-
            cmake-${{ matrix.toolchain.os }}-${{ matrix.formatting }}-${{ matrix.contracts }}-
            cmake-${{ matrix.toolchain.os }}-${{ matrix.formatting }}-
            cmake-${{ matrix.toolchain.os }}-
      - name: Install gcc-${{ matrix.toolchain.compiler.version }}
        if: matrix.toolchain.compiler.type == 'GCC'
        shell: bash
        run: |
          if [[ "${{ matrix.toolchain.compiler.version }}" -ge 15 ]]; then
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo apt update
          fi
          sudo apt install -y g++-${{ matrix.toolchain.compiler.version }}
      - name: Install Clang with apt
        if: matrix.toolchain.compiler.type == 'CLANG' && matrix.toolchain.os != 'macos-14'
        shell: bash
        working-directory: ${{ env.HOME }}
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh ${{ matrix.toolchain.compiler.version }}
          sudo apt install -y clang-tools-${{ matrix.toolchain.compiler.version }}
      - name: Install Clang using homebrew
        if: matrix.toolchain.compiler.type == 'CLANG' && matrix.toolchain.os == 'macos-14'
        shell: bash
        run: |
          brew install llvm@18
      - name: Install Libc++
        if: matrix.toolchain.compiler.type == 'CLANG' && matrix.toolchain.lib == 'libc++' && matrix.toolchain.os != 'macos-14'
        shell: bash
        run: |
          sudo apt install -y libc++-${{ matrix.toolchain.compiler.version }}-dev libc++abi-${{ matrix.toolchain.compiler.version }}-dev libunwind-${{ matrix.toolchain.compiler.version }}-dev
      - name: Fix libc++ std.cppm path for CMake
        if: matrix.import_std == 'True' && matrix.toolchain.compiler.type == 'CLANG' && matrix.toolchain.os != 'macos-14'
        shell: bash
        run: |
          sudo mkdir -p /lib/share
          sudo ln -sfn /usr/lib/llvm-${{ matrix.toolchain.compiler.version }}/share/libc++ /lib/share/libc++
      - name: Select Xcode version
        if: matrix.toolchain.compiler.type == 'APPLE_CLANG'
        shell: bash
        run: |
          sudo xcode-select -s /Applications/Xcode_${{ matrix.toolchain.compiler.xcode_version }}.app && /usr/bin/xcodebuild -version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install Ninja
        shell: bash
        run: |
          pip install -U ninja
      - name: Install Conan
        shell: bash
        run: |
          pip install -U conan
      - name: Configure Conan
        shell: bash
        run: |
          conan profile detect --force
          conan remote add artifactory https://mpusz.jfrog.io/artifactory/api/conan/conan-oss
          echo 'tools.cmake.cmake_layout:build_folder_vars=["settings.compiler", "settings.compiler.version", "settings.compiler.cppstd"]' >> ~/.conan2/global.conf
          conan profile show -pr default
      - name: Install Conan dependencies
        shell: bash
        run: |
          conan install . -b missing ${{ matrix.conan-settings }} \
                          -c tools.cmake.cmaketoolchain:generator="Ninja Multi-Config" \
                          -c user.mp-units.build:all=False ${{ matrix.conan-config }}
      - name: Provide dependencies for the build
        shell: bash
        working-directory: src
        run: |
          echo -e '{\n    "version": 4,\n    "include": [\n        "../CMakeUserPresets.json"\n    ]\n}' | cat > CMakeUserPresets.json
      - name: Configure mp-units CMake
        if: matrix.toolchain.compiler.type == 'MSVC'
        shell: cmd
        working-directory: src
        run: |
          call ..\build\${{ matrix.conan-build-folder }}\generators\conanbuild.bat
          call ..\build\${{ matrix.conan-build-folder }}\generators\conanvcvars.bat
          cmake --version
          cmake --preset conan-${{ matrix.conan-build-folder }} -DCMAKE_INSTALL_PREFIX=../out
      - name: Configure mp-units CMake
        if: matrix.toolchain.compiler.type != 'MSVC'
        shell: bash
        working-directory: src
        run: |
          source ../build/${{ matrix.conan-build-folder }}/generators/conanbuild.sh
          cmake --version
          cmake --preset conan-${{ matrix.conan-build-folder }} -DCMAKE_INSTALL_PREFIX=../out
      - name: Install mp-units
        if: matrix.toolchain.compiler.type == 'MSVC'
        shell: cmd
        working-directory: src
        run: |
          call ..\build\${{ matrix.conan-build-folder }}\generators\conanbuild.bat
          cmake --build --preset conan-${{ steps.build_type.outputs.lowercase }} --target install
      - name: Install mp-units
        if: matrix.toolchain.compiler.type != 'MSVC'
        shell: bash
        working-directory: src
        run: |
          source ../build/${{ matrix.conan-build-folder }}/generators/conanbuild.sh
          cmake --build --preset conan-${{ steps.build_type.outputs.lowercase }} --target install
      - name: Provide dependencies for test_package
        shell: bash
        working-directory: test_package
        run: |
          echo -e '{\n    "version": 4,\n    "include": [\n        "../CMakeUserPresets.json"\n    ]\n}' | cat > CMakeUserPresets.json
      - name: Build test_package CMake (local build)
        if: matrix.toolchain.compiler.type == 'MSVC'
        shell: cmd
        working-directory: test_package
        run: |
          call ..\build\${{ matrix.conan-build-folder }}\generators\conanbuild.bat
          call ..\build\${{ matrix.conan-build-folder }}\generators\conanvcvars.bat
          cmake --preset conan-${{ matrix.conan-build-folder }} -Dmp-units_DIR=../build/${{ matrix.conan-build-folder }} -Bbuild/local
          cmake --build build/local --config ${{ matrix.build_type }}
      - name: Build test_package CMake (local build)
        if: matrix.toolchain.compiler.type != 'MSVC'
        shell: bash
        working-directory: test_package
        run: |
          source ../build/${{ matrix.conan-build-folder }}/generators/conanbuild.sh
          cmake --preset conan-${{ matrix.conan-build-folder }} -Dmp-units_DIR=../build/${{ matrix.conan-build-folder }} -Bbuild/local
          cmake --build build/local --config ${{ matrix.build_type }}
      - name: Run test_package-headers (local build)
        shell: bash
        working-directory: test_package/build/local/${{ matrix.build_type }}
        run: |
          ./test_package-headers
      - name: Run test_package (local build)
        if: matrix.cxx_modules == 'True'
        shell: bash
        working-directory: test_package/build/local/${{ matrix.build_type }}
        run: |
          ./test_package
      - name: Build test_package CMake (installation)
        if: matrix.toolchain.compiler.type == 'MSVC'
        shell: cmd
        working-directory: test_package
        run: |
          call ..\build\${{ matrix.conan-build-folder }}\generators\conanbuild.bat
          call ..\build\${{ matrix.conan-build-folder }}\generators\conanvcvars.bat
          cmake --preset conan-${{ matrix.conan-build-folder }} -DCMAKE_INSTALL_PREFIX=../out -Bbuild/install
          cmake --build build/install --config ${{ matrix.build_type }}
      - name: Build test_package CMake (installation)
        if: matrix.toolchain.compiler.type != 'MSVC'
        shell: bash
        working-directory: test_package
        run: |
          source ../build/${{ matrix.conan-build-folder }}/generators/conanbuild.sh
          cmake --preset conan-${{ matrix.conan-build-folder }} -DCMAKE_INSTALL_PREFIX=../out -Bbuild/install
          cmake --build build/install --config ${{ matrix.build_type }}
      - name: Run test_package-headers (installation)
        shell: bash
        working-directory: test_package/build/install/${{ matrix.build_type }}
        run: |
          ./test_package-headers
      - name: Run test_package (installation)
        if: matrix.cxx_modules == 'True'
        shell: bash
        working-directory: test_package/build/install/${{ matrix.build_type }}
        run: |
          ./test_package
      - name: Clean Conan cache before backup
        shell: bash
        run: |
          conan remove *#~latest --confirm
          conan remove *:*#~latest --confirm
          conan cache clean "*" -s -b -d

      - name: Generate test package summary
        if: failure()
        shell: bash
        run: |
          echo "## ❌ CMake Test Package Failed: ${{ matrix.config-summary-str }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Local repro:**" >> $GITHUB_STEP_SUMMARY
          if [ "${{ matrix.toolchain.compiler.type }}" != "MSVC" ]; then
            BUILD_TYPE_LOWER=$(echo "${{ matrix.build_type }}" | tr '[:upper:]' '[:lower:]')
            echo '```sh' >> $GITHUB_STEP_SUMMARY
            echo "echo 'tools.cmake.cmake_layout:build_folder_vars=[\"settings.compiler\", \"settings.compiler.version\", \"settings.compiler.cppstd\"]' >> ~/.conan2/global.conf" >> $GITHUB_STEP_SUMMARY
            echo "conan install . -b missing ${{ matrix.conan-settings }} -c user.mp-units.build:all=False ${{ matrix.conan-config }}" >> $GITHUB_STEP_SUMMARY
            echo "echo '{\"version\":4,\"include\":[\"../CMakeUserPresets.json\"]}' > src/CMakeUserPresets.json" >> $GITHUB_STEP_SUMMARY
            echo "echo '{\"version\":4,\"include\":[\"../CMakeUserPresets.json\"]}' > test_package/CMakeUserPresets.json" >> $GITHUB_STEP_SUMMARY
            echo "(cd src && source ../build/${{ matrix.conan-build-folder }}/generators/conanbuild.sh && cmake --preset conan-${{ matrix.conan-build-folder }} -DCMAKE_INSTALL_PREFIX=../out && cmake --build --preset conan-${BUILD_TYPE_LOWER} --target install)" >> $GITHUB_STEP_SUMMARY
            echo "(cd test_package && source ../build/${{ matrix.conan-build-folder }}/generators/conanbuild.sh && cmake --preset conan-${{ matrix.conan-build-folder }} -Dmp-units_DIR=../build/${{ matrix.conan-build-folder }} -Bbuild/local && cmake --build build/local --config ${{ matrix.build_type }})" >> $GITHUB_STEP_SUMMARY
            echo "./test_package/build/local/${{ matrix.build_type }}/test_package-headers" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo "_MSVC: refer to the workflow steps in \`ci-test-package-cmake.yml\`._" >> $GITHUB_STEP_SUMMARY
          fi
